import Verso
import VersoManual
import VersoBlueprint
import LeanOA

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "C-star and W-star algebras" =>

This chapter introduces the C-star and W-star algebra structures used throughout
Sak-AI and develops the ultraweak, strong, and Mackey topologies.  The mathematical
order follows the first part of Sakai, while the linked Lean declarations expose the
more reusable organization of the formal library.

{index}[C-star algebra]
{index}[W-star algebra]
{index}[ultraweak topology]
{index}[strong topology]
{index}[Mackey topology]

:::group "cstar-foundations"
Basic C-star algebra structure and extreme-point results.
:::

# C-star algebra foundations
%%%
tag := "cstar-foundations"
%%%

:::definition "def:cstar_def" (parent := "cstar-foundations") (lean := "CStarAlgebra, NonUnitalCStarAlgebra") (tags := "mathlib")
A Banach algebra $`A` with an involution is a _C-star algebra_ when
$`\lVert x^*x\rVert=\lVert x\rVert^2` for every $`x\in A`.  The formal
hierarchy includes both unital and nonunital versions.
:::

:::lemma_ "lem:star_pres_norm_Sak_1_1_6" (parent := "cstar-foundations") (lean := "CStarRing.to_normedStarGroup") (uses := "def:cstar_def") (tags := "mathlib")
The involution on a C-star algebra preserves the norm.
:::

:::proof "lem:star_pres_norm_Sak_1_1_6"
The C-star identity and submultiplicativity give
$`\lVert x\rVert^2\leq\lVert x^*\rVert\lVert x\rVert`; applying the same
argument to $`x^*` gives the reverse inequality.
:::

:::theorem "thm:comm_cstar_cts_fcns_Sak_1_2_1" (parent := "cstar-foundations") (lean := "gelfandStarTransform") (uses := "def:cstar_def") (tags := "mathlib")
Every commutative unital C-star algebra $`A` is star-isomorphic to $`C(K)`,
where $`K` is its compact Hausdorff character space.
:::

:::proof "thm:comm_cstar_cts_fcns_Sak_1_2_1"
The Gelfand transform evaluates elements at characters.  The C-star identity
makes it isometric and star preserving.  Its closed unital self-adjoint range
separates points, so Stone--Weierstrass makes the range all of $`C(K)`.
:::

:::corollary "cor:spec_sa_homeo_spec_cstar" (parent := "cstar-foundations") (lean := "cfcₙHom, range_cfcₙHom, IsStarNormal.instNonUnitalIsometricContinuousFunctionalCalculus") (tags := "mathlib")
For a self-adjoint element $`a` in a possibly nonunital C-star algebra, the
nonunital continuous functional calculus isometrically embeds the continuous
complex-valued functions on the pointed quasispectrum $`\sigma_n(a)` that
vanish at $`0`.  Its image is the elemental nonunital C-star subalgebra
generated by $`a`, and it is surjective when $`a` generates the ambient
algebra.
:::

:::proof "cor:spec_sa_homeo_spec_cstar"
Apply the nonunital continuous functional calculus to the normal element
$`a`; its isometry and range theorems give both claims directly.
:::

:::lemma_ "lem:one_is_extreme" (parent := "cstar-foundations") (lean := "CStarAlgebra.one_mem_extremePoints_unitClosedBall") (uses := "thm:comm_cstar_cts_fcns_Sak_1_2_1, lem:star_pres_norm_Sak_1_1_6")
In a unital C-star algebra, the identity is an extreme point of the closed
unit ball.
:::

:::proof "lem:one_is_extreme"
If $`1=(a+b)/2` with $`a` and $`b` contractions, first pass to their
self-adjoint parts.  The commutative C-star algebra they generate is a
function algebra, where the pointwise scalar estimate forces both parts to
equal $`1`.  Applying the same argument to the algebra generated by $`a`
then forces its imaginary part to vanish, so $`a=b=1`.
:::

:::lemma_ "lem:fake_approx_unit" (parent := "cstar-foundations") (lean := "CStarAlgebra.exists_seq_tendsto_mul_left_sq")
For $`a` in a possibly nonunital C-star algebra, there is a sequence of
positive contractions $`y_n` such that $`ay_n\to a` and $`ay_n^2\to a` in
norm.
:::

:::proof "lem:fake_approx_unit"
Choose $`y_n` from the increasing approximate-unit filter with
$`\lVert ay_n-a\rVert<(n+1)^{-1}`.  Since
$`ay_n^2-a=(ay_n-a)y_n+(ay_n-a)` and $`\lVert y_n\rVert\leq1`, the second
error is at most twice the first.
:::

:::lemma_ "lem:extreme_partial_isom" (parent := "cstar-foundations") (lean := "isStarProjection_star_mul_self_of_mem_extremePoints_unitClosedBall")
If $`x` is an extreme point of the closed unit ball of a C-star algebra, then
$`x^*x` is a projection; equivalently, $`x` is a partial isometry in this
sense.
:::

:::proof "lem:extreme_partial_isom"
The linked formal theorem packages the C-star geometric argument: if
$`x^*x` were not idempotent, functional calculus would produce a nonzero
self-adjoint perturbation giving two distinct contractions with midpoint
$`x`, contrary to extremality.
:::

:::theorem "thm:cstar_unital_iff_extreme_Sak_1_6_1" (parent := "cstar-foundations") (lean := "CStarAlgebra.isUnital_iff") (uses := "lem:one_is_extreme, lem:extreme_partial_isom")
A C-star algebra is unital if and only if its closed unit ball has an extreme
point.
:::

:::proof "thm:cstar_unital_iff_extreme_Sak_1_6_1"
In a unital algebra, $`1` is extreme.  Conversely, the projection obtained
from an extreme contraction supplies the identity through the standard
extreme-point argument formalized by the linked characterization.
:::

:::proposition "prop:extr_pos_projs_Sak_1_6_2" (parent := "cstar-foundations") (lean := "isStarProjection_iff_mem_extremePoints_setOf_nonneg_inter_unitClosedBall")
The extreme points of the positive part of the closed unit ball are exactly
the projections.
:::

:::proof "prop:extr_pos_projs_Sak_1_6_2"
Continuous functional calculus reduces extremality of a positive contraction
to the scalar interval $`[0,1]`: only spectrum contained in $`\{0,1\}`
prevents a nontrivial self-adjoint perturbation.  That spectral condition is
equivalent to being a projection.
:::

:::proposition "prop:extr_sa_sa_unitaries_Sak_1_6_3" (parent := "cstar-foundations") (lean := "mem_extremePoints_isSelfAdjoint_and_mem_unitClosedBall_iff_isSelfAdjoint_and_mem_unitary") (uses := "prop:extr_pos_projs_Sak_1_6_2")
The extreme points of the self-adjoint part of the closed unit ball are
exactly the self-adjoint unitaries.
:::

:::proof "prop:extr_sa_sa_unitaries_Sak_1_6_3"
The affine correspondence $`h\mapsto(1+h)/2` identifies self-adjoint
contractions with positive contractions.  The preceding projection
characterization transports to self-adjoint unitaries.
:::

:::group "wstar-foundations"
Preduals, ultraweakly closed subalgebras, and unitality.
:::

# W-star algebras and the ultraweak topology
%%%
tag := "wstar-foundations"
%%%

:::definition "def:wstar_def" (parent := "wstar-foundations") (lean := "WStarAlgebra, Predual") (uses := "def:cstar_def")
A C-star algebra $`M` is a _W-star algebra_ when it is a dual Banach space:
there is a Banach space $`P` whose continuous dual is linearly isometric to
$`M`.  Such a $`P` is a specified predual.  The later uniqueness theorem
justifies the customary notation $`M_*` without building a chosen predual
into reusable statements unnecessarily.
:::

:::lemma_ "lem:sigma_closed_star_subalg_wstar" (parent := "wstar-foundations") (lean := "WStarAlgebra.of_isClosed_submodule, StarSubalgebra.IsUltraweakClosed.wStarAlgebra") (uses := "def:wstar_def, def:sigma_top")
An ultraweakly closed star subalgebra $`N` of a W-star algebra $`M` is again a
W-star algebra.  A predual is obtained from the quotient of $`M_*` by the
preannihilator of $`N`.
:::

:::proof "lem:sigma_closed_star_subalg_wstar"
The preannihilator is norm closed, and the bipolar theorem identifies $`N`
with its annihilator.  The dual of the quotient is isometric to this
annihilator.  An explicit isometry onto the ambient closed submodule supplies
the predual without relying on definitional equality of subtype structures.
:::

:::definition "def:sigma_top" (parent := "wstar-foundations") (lean := "Ultraweak") (uses := "def:wstar_def")
The weak-star topology $`\sigma(M,M_*)` associated to a specified predual is
the _ultraweak_ or _sigma_ topology on $`M`.
:::

:::lemma_ "lem:wstar_unital" (parent := "wstar-foundations") (lean := "CStarAlgebra.isUnital_of_predual") (uses := "thm:cstar_unital_iff_extreme_Sak_1_6_1")
Every C-star algebra with a Banach predual is unital.  Completeness of the
chosen predual is not needed as a separate hypothesis.
:::

:::proof "lem:wstar_unital"
The norm-closed unit ball of $`M=(M_*)^*` is nonempty, compact, and convex in
the ultraweak topology.  Krein--Milman gives an extreme point, and Sakai 1.6.1
then supplies an identity.
:::

:::group "ultraweak-algebra"
Corners, multiplication, and ultraweak closure.
:::

# Ultraweak algebra operations
%%%
tag := "ultraweak-algebra"
%%%

:::lemma_ "lem:cut_down_sigma_closed_cts" (parent := "ultraweak-algebra") (lean := "IsStarProjection.Corner.isClosed_ultraweakRange, IsStarProjection.Corner.continuous_ultraweakCutdownₗ") (uses := "def:sigma_top")
For a projection $`p\in M`, the corner $`pMp` is ultraweakly closed and the
cutdown map $`x\mapsto pxp` is ultraweakly continuous.
:::

:::proof "lem:cut_down_sigma_closed_cts"
The positive unit ball of the corner is the order interval $`[0,p]` and is
ultraweakly compact.  Decomposition into positive contractions and
Krein--Smulian give closedness of the whole corner.  Sakai's off-diagonal
dilation argument makes the range and kernel of cutdown closed; the
idempotent compact-ball criterion then gives continuity.
:::

:::lemma_ "lem:cut_down_of_wstar" (parent := "ultraweak-algebra") (lean := "IsStarProjection.Corner.wStarAlgebra") (uses := "def:sigma_top, lem:cut_down_sigma_closed_cts, lem:sigma_closed_star_subalg_wstar")
If $`p` is a projection in a W-star algebra $`M`, then $`pMp` is a W-star
algebra whose internal identity is $`p`.
:::

:::proof "lem:cut_down_of_wstar"
Use the analytic type synonym `IsStarProjection.Corner`.  Its range map is an
explicit linear isometry onto the ultraweakly closed corner submodule, so the
closed-submodule predual construction applies and its multiplicative identity
is the ambient projection $`p`.
:::

:::lemma_ "lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7" (parent := "ultraweak-algebra") (lean := "IsStarProjection.continuous_ultraweakMulLeftₗ, IsStarProjection.continuous_ultraweakMulRightₗ") (uses := "def:sigma_top, lem:cut_down_sigma_closed_cts")
For every projection $`p\in M`, the maps $`x\mapsto px` and $`x\mapsto xp`
are ultraweakly continuous.
:::

:::proof "lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7"
The compactness argument for the upper off-diagonal Peirce component, together
with compactness of the corner unit ball, closes the range of left
multiplication.  Its kernel is the complementary range, so the idempotent
compact-ball criterion yields continuity.  Right multiplication is obtained
by conjugating with the ultraweakly continuous star operation.
:::

:::lemma_ "lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8" (parent := "ultraweak-algebra") (lean := "Ultraweak.instContinuousStarComplex, Ultraweak.continuous_mulLeftₗ, Ultraweak.continuous_mulRightₗ") (uses := "def:sigma_top, lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7, lem:spec_masa_wstar_stonean_Sak_1_7_5, lem:fin_lin_approx_of_stonean_Sak_1_3_1")
The involution and fixed left and right multiplication maps
$`x\mapsto x^*`, $`x\mapsto ax`, and $`x\mapsto xa` are ultraweakly
continuous.
:::

:::proof "lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8"
The self-adjoint and skew-adjoint parts give complementary real subspaces, so
star is continuous.  Continuous left multipliers form a norm-closed complex
submodule and contain every projection.  A self-adjoint element lies in a
masa; the Stonean Gelfand spectrum approximates it in norm by linear
combinations of projections.  Thus every left multiplier is continuous, and
star conjugation gives the right-multiplier statement.
:::

:::corollary "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9" (parent := "ultraweak-algebra") (lean := "StarSubalgebra.ultraweakClosure, StarSubalgebra.ultraweakClosure_minimal, StarSubalgebra.ultraweakAdjoin, StarSubalgebra.subset_ultraweakAdjoin, StarSubalgebra.isUltraweakClosed_ultraweakAdjoin, StarSubalgebra.ultraweakAdjoin_le, StarSubalgebra.IsUltraweakClosed.wStarAlgebra") (uses := "lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7, lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8, def:sigma_top")
The ultraweak closure of the C-star subalgebra generated by a set $`H` is a
W-star subalgebra.  It is the least ultraweakly closed star subalgebra
containing $`H`, and it remains commutative when the original algebra is
commutative.
:::

:::proof "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9"
`ultraweakAdjoin` takes the ordinary star algebra generated by $`H` and then
its ultraweak closure.  The closure is stable under the algebra operations by
their separate ultraweak continuity; closedness supplies a quotient predual,
and Mathlib's closure theorem for semitopological rings preserves
commutativity.
:::

:::lemma_ "lem:wstar_of_masa" (parent := "ultraweak-algebra") (lean := "StarSubalgebra.IsMasa.isUltraweakClosed, StarSubalgebra.IsUltraweakClosed.wStarAlgebra") (uses := "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9")
A maximal abelian star subalgebra of a W-star algebra is itself a W-star
algebra.
:::

:::proof "lem:wstar_of_masa"
Its ultraweak closure is commutative and contains it.  Maximality identifies
the closure with the original masa, so it is ultraweakly closed and inherits
a predual.
:::

:::group "operator-topologies"
The continuous dual and comparison of ultraweak, strong, and Mackey topologies.
:::

# Other operator topologies
%%%
tag := "operator-topologies"
%%%

:::proposition "prop:loc_cvx_result" (parent := "operator-topologies") (lean := "Ultraweak.predualDualEquiv")
The ultraweakly continuous complex-linear functionals on $`M` are precisely
those represented by the specified predual $`M_*`.
:::

:::proof "prop:loc_cvx_result"
`Ultraweak.predualDualEquiv` is the explicit linear equivalence from the
specified predual onto the continuous dual of the transported weak topology;
evaluation is the original dual pairing.
:::

:::definition "def:Mackey_top" (parent := "operator-topologies") (lean := "MackeySpace, continuous_ofMackey")
The _Mackey topology_ $`\tau(M,M_*)` is generated by seminorms
$`p_K(x)=\sup_{\varphi\in K}|\varphi(x)|`, with $`K` ranging over absolutely
convex weakly compact subsets of $`M_*`.  It is the strongest compatible
locally convex topology: its continuous dual is exactly $`M_*`.
:::

:::definition "def:strong_top" (parent := "operator-topologies") (lean := "Ultraweak.Strong, Ultraweak.Strong.seminorm_apply")
The _strong topology_ $`s(M,M_*)` is generated by the seminorms
$`x\mapsto\varphi(x^*x)^{1/2}` as $`\varphi` ranges over positive
ultraweakly continuous functionals.
:::

:::theorem "thm:polar_decomposition_ultraweak_functional" (parent := "operator-topologies") (lean := "Ultraweak.exists_positive_comp_mulLeft_of_isSelfAdjoint") (uses := "def:sigma_top, thm:Banach_Alaoglu, prop:extr_sa_sa_unitaries_Sak_1_6_3, lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8")
If $`f` is a self-adjoint ultraweakly continuous complex-linear functional,
there are a positive ultraweakly continuous functional $`\varphi` and a
self-adjoint unitary $`u\in M` such that $`f(x)=\varphi(ux)` for all $`x`.
:::

:::proof "thm:polar_decomposition_ultraweak_functional"
Maximize the real part of $`f` on the ultraweakly compact self-adjoint unit
ball and pass to an extreme point of the exposed face.  It is a self-adjoint
unitary $`u`.  The phase argument gives $`f(u)=\lVert f\rVert`, so
$`x\mapsto f(ux)` is positive and remains ultraweakly continuous.  Since
$`u^2=1`, this is the desired $`\varphi`.
:::

:::theorem "thm:sigma_le_s_le_tau" (parent := "operator-topologies") (lean := "Ultraweak.Strong.continuous_toUltraweakₗ, Ultraweak.Strong.continuous_fromMackeyₗ") (uses := "def:Mackey_top, def:strong_top, def:sigma_top, thm:polar_decomposition_ultraweak_functional")
The operator topologies satisfy
$`\sigma(M,M_*)\leq s(M,M_*)\leq\tau(M,M_*)`, where the order means that the
topology on the left is weaker.
:::

:::proof "thm:sigma_le_s_le_tau"
Polar decomposition shows that every ultraweak functional is controlled by a
strong seminorm, giving the first comparison.  The GNS representation
identifies the strong continuous dual with the specified predual, and
Mackey--Arens maximality gives the second comparison.
:::

:::lemma_ "lem:bdd_sigma_cts_iff_bdd_s_cts_Sak_1_8_10" (parent := "operator-topologies") (lean := "Ultraweak.Strong.continuous_ultraweak_iff_strong, Ultraweak.Strong.continuousOn_closedUnitBall_tfae") (uses := "thm:sigma_le_s_le_tau")
For a complex-linear functional $`\rho` on $`M`, the following are equivalent:
ultraweak continuity, strong continuity, ultraweak continuity on the
norm-closed unit ball, and strong continuity on that ball.
:::

:::proof "lem:bdd_sigma_cts_iff_bdd_s_cts_Sak_1_8_10"
Krein--Smulian promotes ultraweak continuity on the unit ball to global
continuity.  Equality of the strong and ultraweak continuous duals transports
closure of the convex intersection of the kernel with the ball and gives the
strong version.  This compares continuous functionals; it does not claim that
bounded ultraweak convergence implies strong convergence.
:::
