import Verso
import VersoManual
import VersoBlueprint
import LeanOA

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "C-star and W-star algebras" =>

This chapter introduces the C-star and W-star algebra structures used throughout
Sak-AI and develops the ultraweak, strong, and Mackey topologies.  The mathematical
order follows the first part of Sakai, while the linked Lean declarations expose the
more reusable organization of the formal library.

{index}[C-star algebra]
{index}[W-star algebra]
{index}[ultraweak topology]
{index}[strong topology]
{index}[Mackey topology]

:::group "cstar-foundations"
Basic C-star algebra structure and extreme-point results.
:::

# C-star algebra foundations
%%%
tag := "cstar-foundations"
%%%

:::definition "def:cstar_def" (parent := "cstar-foundations") (lean := "CStarAlgebra, NonUnitalCStarAlgebra") (tags := "mathlib")
A Banach algebra $`A` with an involution is a _C-star algebra_ when
$`\lVert x^*x\rVert=\lVert x\rVert^2` for every $`x\in A`.  The formal
hierarchy includes both unital and nonunital versions.
:::

:::lemma_ "lem:star_pres_norm_Sak_1_1_6" (parent := "cstar-foundations") (lean := "CStarRing.to_normedStarGroup") (uses := "def:cstar_def") (tags := "mathlib")
The involution on a C-star algebra preserves the norm.
:::

:::proof "lem:star_pres_norm_Sak_1_1_6"
The C-star identity and submultiplicativity give
$`\lVert x\rVert^2\leq\lVert x^*\rVert\lVert x\rVert`; applying the same
argument to $`x^*` gives the reverse inequality.
:::

:::theorem "thm:comm_cstar_cts_fcns_Sak_1_2_1" (parent := "cstar-foundations") (lean := "gelfandStarTransform") (uses := "def:cstar_def") (tags := "mathlib")
Every commutative unital C-star algebra $`A` is star-isomorphic to $`C(K)`,
where $`K` is its compact Hausdorff character space.
:::

:::proof "thm:comm_cstar_cts_fcns_Sak_1_2_1"
The Gelfand transform evaluates elements at characters.  The C-star identity
makes it isometric and star preserving.  Its closed unital self-adjoint range
separates points, so Stone--Weierstrass makes the range all of $`C(K)`.
:::

:::corollary "cor:spec_sa_homeo_spec_cstar" (parent := "cstar-foundations") (lean := "cfcₙHom, range_cfcₙHom, IsStarNormal.instNonUnitalIsometricContinuousFunctionalCalculus") (tags := "mathlib")
For a self-adjoint element $`a` in a possibly nonunital C-star algebra, the
nonunital continuous functional calculus isometrically embeds the continuous
complex-valued functions on the pointed quasispectrum $`\sigma_n(a)` that
vanish at $`0`.  Its image is the elemental nonunital C-star subalgebra
generated by $`a`, and it is surjective when $`a` generates the ambient
algebra.
:::

:::proof "cor:spec_sa_homeo_spec_cstar"
Apply the nonunital continuous functional calculus to the normal element
$`a`; its isometry and range theorems give both claims directly.
:::

:::lemma_ "lem:one_is_extreme" (parent := "cstar-foundations") (lean := "CStarAlgebra.one_mem_extremePoints_unitClosedBall") (uses := "thm:comm_cstar_cts_fcns_Sak_1_2_1, lem:star_pres_norm_Sak_1_1_6")
In a unital C-star algebra, the identity is an extreme point of the closed
unit ball.
:::

:::proof "lem:one_is_extreme"
If $`1=(a+b)/2` with $`a` and $`b` contractions, first pass to their
self-adjoint parts.  The commutative C-star algebra they generate is a
function algebra, where the pointwise scalar estimate forces both parts to
equal $`1`.  Applying the same argument to the algebra generated by $`a`
then forces its imaginary part to vanish, so $`a=b=1`.
:::

:::lemma_ "lem:fake_approx_unit" (parent := "cstar-foundations") (lean := "CStarAlgebra.exists_seq_tendsto_mul_left_sq")
For $`a` in a possibly nonunital C-star algebra, there is a sequence of
positive contractions $`y_n` such that $`ay_n\to a` and $`ay_n^2\to a` in
norm.
:::

:::proof "lem:fake_approx_unit"
Choose $`y_n` from the increasing approximate-unit filter with
$`\lVert ay_n-a\rVert<(n+1)^{-1}`.  Since
$`ay_n^2-a=(ay_n-a)y_n+(ay_n-a)` and $`\lVert y_n\rVert\leq1`, the second
error is at most twice the first.
:::

:::lemma_ "lem:extreme_partial_isom" (parent := "cstar-foundations") (lean := "isStarProjection_star_mul_self_of_mem_extremePoints_unitClosedBall")
If $`x` is an extreme point of the closed unit ball of a C-star algebra, then
$`x^*x` is a projection; equivalently, $`x` is a partial isometry in this
sense.
:::

:::proof "lem:extreme_partial_isom"
The linked formal theorem packages the C-star geometric argument: if
$`x^*x` were not idempotent, functional calculus would produce a nonzero
self-adjoint perturbation giving two distinct contractions with midpoint
$`x`, contrary to extremality.
:::

:::theorem "thm:cstar_unital_iff_extreme_Sak_1_6_1" (parent := "cstar-foundations") (lean := "CStarAlgebra.isUnital_iff") (uses := "lem:one_is_extreme, lem:extreme_partial_isom")
A C-star algebra is unital if and only if its closed unit ball has an extreme
point.
:::

:::proof "thm:cstar_unital_iff_extreme_Sak_1_6_1"
In a unital algebra, $`1` is extreme.  Conversely, the projection obtained
from an extreme contraction supplies the identity through the standard
extreme-point argument formalized by the linked characterization.
:::

:::proposition "prop:extr_pos_projs_Sak_1_6_2" (parent := "cstar-foundations") (lean := "isStarProjection_iff_mem_extremePoints_setOf_nonneg_inter_unitClosedBall")
The extreme points of the positive part of the closed unit ball are exactly
the projections.
:::

:::proof "prop:extr_pos_projs_Sak_1_6_2"
Continuous functional calculus reduces extremality of a positive contraction
to the scalar interval $`[0,1]`: only spectrum contained in $`\{0,1\}`
prevents a nontrivial self-adjoint perturbation.  That spectral condition is
equivalent to being a projection.
:::

:::proposition "prop:extr_sa_sa_unitaries_Sak_1_6_3" (parent := "cstar-foundations") (lean := "mem_extremePoints_isSelfAdjoint_and_mem_unitClosedBall_iff_isSelfAdjoint_and_mem_unitary") (uses := "prop:extr_pos_projs_Sak_1_6_2")
The extreme points of the self-adjoint part of the closed unit ball are
exactly the self-adjoint unitaries.
:::

:::proof "prop:extr_sa_sa_unitaries_Sak_1_6_3"
The affine correspondence $`h\mapsto(1+h)/2` identifies self-adjoint
contractions with positive contractions.  The preceding projection
characterization transports to self-adjoint unitaries.
:::

:::group "wstar-foundations"
Preduals, ultraweakly closed subalgebras, and unitality.
:::

# W-star algebras and the ultraweak topology
%%%
tag := "wstar-foundations"
%%%

:::definition "def:wstar_def" (parent := "wstar-foundations") (lean := "WStarAlgebra, Predual") (uses := "def:cstar_def")
A C-star algebra $`M` is a _W-star algebra_ when it is a dual Banach space:
there is a Banach space $`P` whose continuous dual is linearly isometric to
$`M`.  Such a $`P` is a specified predual.  The later uniqueness theorem
justifies the customary notation $`M_*` without building a chosen predual
into reusable statements unnecessarily.
:::

:::lemma_ "lem:sigma_closed_star_subalg_wstar" (parent := "wstar-foundations") (lean := "WStarAlgebra.of_isClosed_submodule, StarSubalgebra.IsUltraweakClosed.wStarAlgebra") (uses := "def:wstar_def, def:sigma_top")
An ultraweakly closed star subalgebra $`N` of a W-star algebra $`M` is again a
W-star algebra.  A predual is obtained from the quotient of $`M_*` by the
preannihilator of $`N`.
:::

:::proof "lem:sigma_closed_star_subalg_wstar"
The preannihilator is norm closed, and the bipolar theorem identifies $`N`
with its annihilator.  The dual of the quotient is isometric to this
annihilator.  An explicit isometry onto the ambient closed submodule supplies
the predual without relying on definitional equality of subtype structures.
:::

:::definition "def:sigma_top" (parent := "wstar-foundations") (lean := "Ultraweak") (uses := "def:wstar_def")
The weak-star topology $`\sigma(M,M_*)` associated to a specified predual is
the _ultraweak_ or _sigma_ topology on $`M`.
:::

:::lemma_ "lem:wstar_unital" (parent := "wstar-foundations") (lean := "CStarAlgebra.isUnital_of_predual") (uses := "thm:cstar_unital_iff_extreme_Sak_1_6_1")
Every C-star algebra with a Banach predual is unital.  Completeness of the
chosen predual is not needed as a separate hypothesis.
:::

:::proof "lem:wstar_unital"
The norm-closed unit ball of $`M=(M_*)^*` is nonempty, compact, and convex in
the ultraweak topology.  Krein--Milman gives an extreme point, and Sakai 1.6.1
then supplies an identity.
:::

:::group "ultraweak-algebra"
Corners, multiplication, and ultraweak closure.
:::

# Ultraweak algebra operations
%%%
tag := "ultraweak-algebra"
%%%

:::lemma_ "lem:cut_down_sigma_closed_cts" (parent := "ultraweak-algebra") (lean := "IsStarProjection.Corner.isClosed_ultraweakRange, IsStarProjection.Corner.continuous_ultraweakCutdownₗ") (uses := "def:sigma_top")
For a projection $`p\in M`, the corner $`pMp` is ultraweakly closed and the
cutdown map $`x\mapsto pxp` is ultraweakly continuous.
:::

:::proof "lem:cut_down_sigma_closed_cts"
The positive unit ball of the corner is the order interval $`[0,p]` and is
ultraweakly compact.  Decomposition into positive contractions and
Krein--Smulian give closedness of the whole corner.  Sakai's off-diagonal
dilation argument makes the range and kernel of cutdown closed; the
idempotent compact-ball criterion then gives continuity.
:::

:::lemma_ "lem:cut_down_of_wstar" (parent := "ultraweak-algebra") (lean := "IsStarProjection.Corner.wStarAlgebra") (uses := "def:sigma_top, lem:cut_down_sigma_closed_cts, lem:sigma_closed_star_subalg_wstar")
If $`p` is a projection in a W-star algebra $`M`, then $`pMp` is a W-star
algebra whose internal identity is $`p`.
:::

:::proof "lem:cut_down_of_wstar"
Use the analytic type synonym `IsStarProjection.Corner`.  Its range map is an
explicit linear isometry onto the ultraweakly closed corner submodule, so the
closed-submodule predual construction applies and its multiplicative identity
is the ambient projection $`p`.
:::

:::lemma_ "lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7" (parent := "ultraweak-algebra") (lean := "IsStarProjection.continuous_ultraweakMulLeftₗ, IsStarProjection.continuous_ultraweakMulRightₗ") (uses := "def:sigma_top, lem:cut_down_sigma_closed_cts")
For every projection $`p\in M`, the maps $`x\mapsto px` and $`x\mapsto xp`
are ultraweakly continuous.
:::

:::proof "lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7"
The compactness argument for the upper off-diagonal Peirce component, together
with compactness of the corner unit ball, closes the range of left
multiplication.  Its kernel is the complementary range, so the idempotent
compact-ball criterion yields continuity.  Right multiplication is obtained
by conjugating with the ultraweakly continuous star operation.
:::

:::lemma_ "lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8" (parent := "ultraweak-algebra") (lean := "Ultraweak.instContinuousStarComplex, Ultraweak.continuous_mulLeftₗ, Ultraweak.continuous_mulRightₗ") (uses := "def:sigma_top, lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7, lem:spec_masa_wstar_stonean_Sak_1_7_5, lem:fin_lin_approx_of_stonean_Sak_1_3_1")
The involution and fixed left and right multiplication maps
$`x\mapsto x^*`, $`x\mapsto ax`, and $`x\mapsto xa` are ultraweakly
continuous.
:::

:::proof "lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8"
The self-adjoint and skew-adjoint parts give complementary real subspaces, so
star is continuous.  Continuous left multipliers form a norm-closed complex
submodule and contain every projection.  A self-adjoint element lies in a
masa; the Stonean Gelfand spectrum approximates it in norm by linear
combinations of projections.  Thus every left multiplier is continuous, and
star conjugation gives the right-multiplier statement.
:::

:::corollary "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9" (parent := "ultraweak-algebra") (lean := "StarSubalgebra.ultraweakClosure, StarSubalgebra.ultraweakClosure_minimal, StarSubalgebra.ultraweakAdjoin, StarSubalgebra.subset_ultraweakAdjoin, StarSubalgebra.isUltraweakClosed_ultraweakAdjoin, StarSubalgebra.ultraweakAdjoin_le, StarSubalgebra.IsUltraweakClosed.wStarAlgebra") (uses := "lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7, lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8, def:sigma_top")
The ultraweak closure of the C-star subalgebra generated by a set $`H` is a
W-star subalgebra.  It is the least ultraweakly closed star subalgebra
containing $`H`, and it remains commutative when the original algebra is
commutative.
:::

:::proof "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9"
`ultraweakAdjoin` takes the ordinary star algebra generated by $`H` and then
its ultraweak closure.  The closure is stable under the algebra operations by
their separate ultraweak continuity; closedness supplies a quotient predual,
and Mathlib's closure theorem for semitopological rings preserves
commutativity.
:::

:::lemma_ "lem:wstar_of_masa" (parent := "ultraweak-algebra") (lean := "StarSubalgebra.IsMasa.isUltraweakClosed, StarSubalgebra.IsUltraweakClosed.wStarAlgebra") (uses := "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9")
A maximal abelian star subalgebra of a W-star algebra is itself a W-star
algebra.
:::

:::proof "lem:wstar_of_masa"
Its ultraweak closure is commutative and contains it.  Maximality identifies
the closure with the original masa, so it is ultraweakly closed and inherits
a predual.
:::

:::group "operator-topologies"
The continuous dual and comparison of ultraweak, strong, and Mackey topologies.
:::

# Other operator topologies
%%%
tag := "operator-topologies"
%%%

:::theorem "thm:vector_functionals_wot" (parent := "operator-topologies") (lean := "ContinuousLinearMapWOT.vectorFunctionalPairing_isWeak, ContinuousLinearMapWOT.vectorFunctionalSpanEquivDual")
Let $`E` be a seminormed space and $`F` a complete Hilbert space over
an $`\mathbb R`- or $`\mathbb C`-like scalar field.  The weak topology on
$`\mathcal L(E,F)` induced by the algebraic span of the vector functionals
$`T\mapsto\langle\eta,T\xi\rangle`, written in Mathlib's second-slot-linear
inner-product convention, is exactly Mathlib's weak operator
topology.  Moreover, this span is the full space of WOT-continuous linear
functionals.
:::

:::proof "thm:vector_functionals_wot"
One continuous identity sends the coefficient-induced `WeakBilin` carrier to
Mathlib WOT because every generating coefficient is a test functional.  The
reverse identity is continuous by induction over the linear span, using
Mathlib's coefficient characterization of WOT for the generators.  The
resulting continuous linear equivalence yields the `LinearMap.IsWeak`
certificate on the WOT carrier, and the general weak representation theorem
identifies its continuous dual with the coefficient span.  This is an
algebraic/topological-dual result; the following theorem performs the
distinct norm-completion step.
:::

:::theorem "thm:vector_functional_closure_predual" (parent := "operator-topologies") (lean := "ContinuousLinearMap.norm_vectorFunctional, ContinuousLinearMap.denseRange_vectorFunctionalSpanToClosure, ContinuousLinearMap.vectorFunctionalClosureEquivDual, ContinuousLinearMap.vectorFunctionalPredualEquivClosure, ContinuousLinearMap.vectorFunctionalPredual_predualEquivDual_apply_apply") (uses := "thm:vector_functionals_wot")
Let $`E` be a seminormed space and $`F` a complete Hilbert space over an
$`\mathbb R`- or $`\mathbb C`-like scalar field.  Let $`P(E,F)` be the norm
closure, inside $`\mathcal L(E,F)^*`, of the finite span of the vector
functionals $`T\mapsto\langle\eta,T\xi\rangle`.  Canonical evaluation is a
linear isometric equivalence
$`\mathcal L(E,F)\cong P(E,F)^*`.  When $`E` is normed, this equivalence
installs a short carrier canonically isometric to $`P(E,F)` as a specified
predual; in particular it gives the concrete vector-functional predual of
$`B(\mathcal H)` without forcing downstream users to unfold the nested
closure subtype.
:::

:::proof "thm:vector_functional_closure_predual"
Hahn--Banach and a rank-one operator give the sharp coefficient formula
$`\lVert\omega_{\xi,\eta}\rVert=\lVert\xi\rVert\lVert\eta\rVert`, so the
finite coefficient span embeds densely into its norm closure and evaluation
is isometric.  For a functional $`g\in P(E,F)^*`, the bounded form
$`(\xi,\eta)\mapsto\overline{g(\omega_{\xi,\eta})}` is conjugate-linear in
$`\xi` and linear in $`\eta`.  Composing it with the conjugate-linear
Fréchet--Riesz equivalence for $`F` recovers an operator $`T_g:E\to F`
satisfying $`\langle\eta,T_g\xi\rangle=g(\omega_{\xi,\eta})`.  Span
induction and continuity extend this equality from the generators to the
whole norm closure, proving surjectivity.
:::

:::theorem "thm:vector_functional_series_predual_bridge" (parent := "operator-topologies") (lean := "ContinuousLinearMap.summable_vectorFunctionalInClosure_of_summable_sq, ContinuousLinearMap.summable_inner_apply_of_summable_sq, ContinuousLinearMap.norm_vectorFunctionalSeries_le, ContinuousLinearMap.vectorFunctionalPredualEvaluation_vectorFunctionalSeriesInPredual, ContinuousLinearMap.vectorFunctionalPredualSpan_sakaiInvariant, ContinuousLinearMap.vectorFunctionalPredualSpan_le_seriesSpan, ContinuousLinearMap.vectorFunctionalSeriesWeakOfUltraweakL, ContinuousLinearMap.vectorFunctionalSeriesTestWeakL_comp_weakOfUltraweakL, Ultraweak.isClosed_ultraweak_of_isClosed_vectorFunctionalSeriesWeak") (uses := "thm:vector_functionals_wot, thm:vector_functional_closure_predual")
Let $`(\xi_n)` and $`(\eta_n)` be separately square-summable vector families.
Then $`\sum_n\omega_{\xi_n,\eta_n}` converges in the norm-closed
vector-functional predual, evaluates on $`T` as
$`\sum_n\langle\eta_n,T\xi_n\rangle`, and satisfies the expected
Cauchy--Schwarz norm bound.  For a complex Hilbert space, let $`V_\Sigma`
be the span of exactly the $`\mathbb N`-indexed series occurring in Sakai's
definition.  The finite coefficient core embeds in $`V_\Sigma`, while the
full concrete-predual topology maps continuously to the weak topology
induced by $`V_\Sigma`.  Consequently every $`V_\Sigma`-weakly closed subset
of $`B(\mathcal H)` is closed for the full specified-predual ultraweak
topology.
:::

:::proof "thm:vector_functional_series_predual_bridge"
The exact coefficient norm reduces norm summability to Hölder's inequality
with conjugate exponents $`2` and $`2`; continuity of evaluation commutes the
resulting `tsum` with operator evaluation.  Single-support vector families
place every ordinary vector functional among the countable series
generators.  Their finite span is norm dense and is separately certified as
stable under the predual involution and fixed left and right multipliers.
At the topology level, restricting the right test space of a `WeakBilin`
pairing gives a continuous identity from the full predual weak topology to
the series-test topology.  This proves only the source-safe direction used
at this stage: the reverse identity, equality of the two topologies, and a
single-series representation of every predual element are not asserted.
:::

:::theorem "thm:bounded_operator_ultrastrong_bridge" (parent := "operator-topologies") (lean := "ContinuousLinearMap.squareSummableSeminorm_apply_eq_sqrt_tsum, SquareSummableConvergenceCLM.toPointwiseConvergenceCLM, SquareSummableConvergenceCLM.isClosed_squareSummable_of_isClosed_pointwise, ContinuousLinearMap.vectorFunctionalDiagonalSeriesUltraweakP, BoundedOperatorUltrastrong.gnsSeminorm_vectorFunctionalDiagonalSeriesUltraweakP, BoundedOperatorUltrastrong.toSquareSummableL, BoundedOperatorUltrastrong.isClosed_strong_of_isClosed_squareSummable") (uses := "thm:vector_functional_series_predual_bridge")
For normed spaces $`E,F`, continuous linear maps carry the topology generated
by
$`
  T\longmapsto
  \left(\sum_n\lVert T\xi_n\rVert^2\right)^{1/2}
`
over square-summable families $`(\xi_n)`.  This topology maps continuously to
pointwise convergence.  On $`B(\mathcal H)`, it is Sakai's strongest, or
ultrastrong, operator topology.  Relative to the concrete vector-functional
predual, the intrinsic strong topology maps continuously to it:
$`
  s(B(\mathcal H),P_{\mathcal H})
    \longrightarrow \operatorname{USOT}(B(\mathcal H))
    \longrightarrow \operatorname{SOT}(B(\mathcal H)).
`
:::

:::proof "thm:bounded_operator_ultrastrong_bridge"
Coordinatewise application sends an $`\ell^2` family to an $`\ell^2` family;
pulling back the $`\ell^2` norm gives the displayed seminorm.  Families
supported at one coordinate prove the continuous identity from ultrastrong
to pointwise convergence.  For $`\xi\in\ell^2(\mathbb N,\mathcal H)`, the
diagonal coefficient series
$`
  T\longmapsto\sum_n\langle\xi_n,T\xi_n\rangle
`
is a positive ultraweakly continuous functional, and its GNS seminorm is
exactly the concrete square-summable seminorm.  Thus every defining
ultrastrong seminorm is already an intrinsic strong seminorm.  No converse
map or equality of topologies is asserted; that requires Sakai's later
representation theorem for positive normal functionals.
:::

:::theorem "thm:wot_relative_kaplansky" (parent := "operator-topologies") (lean := "Ultraweak.testWeakClosure_vectorFunctionalPredualSpan_eq_wotClosure, Ultraweak.ultraweak_closure_unitBall_eq_wotClosure_unitBall, Ultraweak.kaplansky_density_wotClosure") (uses := "thm:vector_functionals_wot, thm:vector_functional_closure_predual, thm:kaplansky_density_Sak_1_9_1")
Let $`H` be a complex Hilbert space, let $`A` be a possibly nonunital
self-adjoint subalgebra of $`B(H)`, and write
$`\overline A^{\mathrm{WOT}}` for its closure in Mathlib's weak operator
topology.  Relative to the concrete vector-functional predual,
write $`S_{B(H)}=\{T\in B(H):\lVert T\rVert\leq 1\}` for the closed unit ball.  Then

$`
  \overline{A\cap S_{B(H)}}^{\,\sigma}
    =\overline A^{\mathrm{WOT}}\cap S_{B(H)},
  \qquad
  \overline{A\cap S_{B(H)}}^{\,\tau}
    =\overline A^{\mathrm{WOT}}\cap S_{B(H)}.
`

Thus the unit ball of $`A` is Mackey dense in the unit ball of its WOT
closure.  This is the ambient-relative Kaplansky bridge needed in Sakai's
proof of Proposition 1.15.1; it is not itself the five-way global
closedness equivalence asserted by that proposition.
:::

:::proof "thm:wot_relative_kaplansky"
The finite vector-functional core inside the concrete predual induces
Mathlib WOT, so its transported test-weak closure of $`A` is exactly
$`\overline A^{\mathrm{WOT}}`.  The relative Kaplansky theorem keeps this
closure as an explicit target star subalgebra.  For a closed source, the
Kaplansky transform puts every extreme point of the target unit ball in the
ultraweak closure of the source unit ball; the extreme-point argument is
performed in the target subtype and then transported through the general
real-submodule interface.  Krein--Milman gives the ultraweak equality.  A
norm-closure reduction removes closedness of $`A`, and compatible convex
closure transfers the equality to the full-predual Mackey topology.
:::

:::proposition "prop:operator_topology_closedness_Sak_1_15_1" (parent := "operator-topologies") (lean := "NonUnitalStarSubalgebra.operatorTopologyClosedness_tfae, NonUnitalStarSubalgebra.isWOTClosed_iff_isSigmaWOTClosed, NonUnitalStarSubalgebra.isWOTClosed_iff_isSOTClosed, NonUnitalStarSubalgebra.isWOTClosed_iff_isUSOTClosed, NonUnitalStarSubalgebra.isWOTClosed_iff_isUltraweakClosed") (uses := "thm:vector_functional_series_predual_bridge, thm:bounded_operator_ultrastrong_bridge, thm:wot_relative_kaplansky, thm:sigma_le_s_le_tau")
Let $`H` be a complex Hilbert space and let $`N` be a possibly nonunital
self-adjoint subalgebra of $`B(H)`.  The following five global closedness
conditions are equivalent:

1. $`N` is weak-operator closed;
2. $`N` is closed for Sakai's coefficient-series $`\sigma`-weak operator
   topology;
3. $`N` is strong-operator closed;
4. $`N` is closed for Sakai's strongest, or ultrastrong, operator topology;
5. $`N` is closed for $`\sigma(B(H),B(H)_*)`, using the concrete
   vector-functional predual.

This is Sakai, Proposition 1.15.1.  It is a statement about global closedness,
not merely bounded subsets, and it does not assert equality of the five
topologies.
:::

:::proof "prop:operator_topology_closedness_Sak_1_15_1"
The easy arrows use continuous identities.  The coefficient-series topology
restricts continuously to the finite coefficient core and hence to Mathlib
WOT; WOT maps from SOT; ultrastrong maps to SOT; and intrinsic strong maps to
ultrastrong.  Real-convex closure transport then sends intrinsic-strong
closedness of the subalgebra to concrete-predual ultraweak closedness.

For the reverse arrow, take the Mathlib-WOT closure of $`N`.  Relative
Kaplansky density identifies its closed unit ball with the ultraweak closure
of the unit ball of $`N`.  Ultraweak closedness therefore puts every
norm-at-most-one element of the WOT closure back in $`N`; normalizing an
arbitrary nonzero element by its norm and rescaling proves that the whole WOT
closure equals $`N`.  This completes the five-way equivalence without using
the converse coefficient-series or ultrastrong representation theorems.
:::

:::theorem "thm:closed_submodule_induced_ultraweak" (parent := "operator-topologies") (lean := "Ultraweak.closedSubmoduleEquivDual_apply_mk, Ultraweak.closedSubmoduleUltraweakEquiv")
Let $`M` have a specified predual $`P`, and let $`E` be an ultraweakly
closed normed submodule of $`M`.  Its canonical quotient predual is
$`P/E^\perp`.  Evaluation on a quotient representative is ambient
evaluation,

$`
  \langle x,[p]\rangle=\langle x,p\rangle,
`

and the resulting intrinsic weak-star topology
$`\sigma(E,P/E^\perp)` is canonically continuously linearly equivalent to
the ambient ultraweak subspace topology on $`E`.  This is proved for an
arbitrary real- or complex-like scalar field and introduces neither a second
predual nor a second subspace topology.
:::

:::proposition "prop:operator_topology_closed_ball_weak_family_Sak_1_15_2" (parent := "operator-topologies") (lean := "NonUnitalStarSubalgebra.IsWOTClosed.inducedUltraweakSigmaWOTClosedBallHomeomorph, NonUnitalStarSubalgebra.IsWOTClosed.inducedUltraweakWOTClosedBallHomeomorph, NonUnitalStarSubalgebra.IsWOTClosed.tendsto_sigmaWOT_iff_inducedUltraweak, NonUnitalStarSubalgebra.IsWOTClosed.tendsto_wot_iff_inducedUltraweak") (uses := "thm:closed_submodule_induced_ultraweak, prop:operator_topology_closedness_Sak_1_15_1, thm:vector_functional_series_predual_bridge, thm:Banach_Alaoglu, lem:homeo_of_cts_bij_cpt_haus")
Let $`H` be a complex Hilbert space and let $`N` be a WOT-closed,
possibly nonunital self-adjoint subalgebra of $`B(H)`.  Give $`N` the
canonical predual

$`
  N_* = B(H)_*/N^\perp.
`

On every zero-centered norm-closed ball of $`N`, the following three
topologies agree:

1. the intrinsic weak-star topology $`\sigma(N,N_*)`;
2. Sakai's coefficient-series $`\sigma`-weak operator topology;
3. the weak operator topology.

The formal statement supplies canonical homeomorphisms of the closed-ball
carriers and arbitrary-filter convergence equivalences, so it is not
restricted to sequences.  This is exactly the weak-family clause of Sakai,
Proposition 1.15.2.  The strong-family clause is not asserted here.
:::

:::proof "prop:operator_topology_closed_ball_weak_family_Sak_1_15_2"
Proposition 1.15.1 turns WOT closedness into concrete-predual ultraweak
closedness.  The quotient-predual theorem then identifies the intrinsic
weak-star ball with the ambient ultraweak subspace ball.  Banach--Alaoglu
makes that ball compact.  The canonical identities from ambient ultraweak
convergence to coefficient-series $`\sigma`-WOT and then to WOT are
continuous, while both target topologies are Hausdorff.  Each continuous
bijection from the compact source to its Hausdorff target is therefore a
homeomorphism.
:::

:::proposition "prop:loc_cvx_result" (parent := "operator-topologies") (lean := "Ultraweak.predualDualEquiv")
The ultraweakly continuous complex-linear functionals on $`M` are precisely
those represented by the specified predual $`M_*`.
:::

:::proof "prop:loc_cvx_result"
`Ultraweak.predualDualEquiv` is the explicit linear equivalence from the
specified predual onto the continuous dual of the transported weak topology;
evaluation is the original dual pairing.
:::

:::definition "def:Mackey_top" (parent := "operator-topologies") (lean := "MackeySpace, continuous_ofMackey")
The _Mackey topology_ $`\tau(M,M_*)` is generated by seminorms
$`p_K(x)=\sup_{\varphi\in K}|\varphi(x)|`, with $`K` ranging over absolutely
convex weakly compact subsets of $`M_*`.  It is the strongest compatible
locally convex topology: its continuous dual is exactly $`M_*`.
:::

:::definition "def:strong_top" (parent := "operator-topologies") (lean := "Ultraweak.Strong, Ultraweak.Strong.seminorm_apply")
The _strong topology_ $`s(M,M_*)` is generated by the seminorms
$`x\mapsto\varphi(x^*x)^{1/2}` as $`\varphi` ranges over positive
ultraweakly continuous functionals.
:::

:::theorem "thm:polar_decomposition_ultraweak_functional" (parent := "operator-topologies") (lean := "Ultraweak.exists_positive_comp_mulLeft_of_isSelfAdjoint") (uses := "def:sigma_top, thm:Banach_Alaoglu, prop:extr_sa_sa_unitaries_Sak_1_6_3, lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8")
If $`f` is a self-adjoint ultraweakly continuous complex-linear functional,
there are a positive ultraweakly continuous functional $`\varphi` and a
self-adjoint unitary $`u\in M` such that $`f(x)=\varphi(ux)` for all $`x`.
:::

:::proof "thm:polar_decomposition_ultraweak_functional"
Maximize the real part of $`f` on the ultraweakly compact self-adjoint unit
ball and pass to an extreme point of the exposed face.  It is a self-adjoint
unitary $`u`.  The phase argument gives $`f(u)=\lVert f\rVert`, so
$`x\mapsto f(ux)` is positive and remains ultraweakly continuous.  Since
$`u^2=1`, this is the desired $`\varphi`.
:::

:::theorem "thm:sigma_le_s_le_tau" (parent := "operator-topologies") (lean := "Ultraweak.Strong.continuous_toUltraweakₗ, Ultraweak.Strong.continuous_fromMackeyₗ") (uses := "def:Mackey_top, def:strong_top, def:sigma_top, thm:polar_decomposition_ultraweak_functional")
The operator topologies satisfy
$`\sigma(M,M_*)\leq s(M,M_*)\leq\tau(M,M_*)`, where the order means that the
topology on the left is weaker.
:::

:::proof "thm:sigma_le_s_le_tau"
Polar decomposition shows that every ultraweak functional is controlled by a
strong seminorm, giving the first comparison.  The GNS representation
identifies the strong continuous dual with the specified predual, and
Mackey--Arens maximality gives the second comparison.
:::

:::lemma_ "lem:bdd_sigma_cts_iff_bdd_s_cts_Sak_1_8_10" (parent := "operator-topologies") (lean := "Ultraweak.Strong.continuous_ultraweak_iff_strong, Ultraweak.Strong.continuousOn_closedUnitBall_tfae") (uses := "thm:sigma_le_s_le_tau")
For a complex-linear functional $`\rho` on $`M`, the following are equivalent:
ultraweak continuity, strong continuity, ultraweak continuity on the
norm-closed unit ball, and strong continuity on that ball.
:::

:::proof "lem:bdd_sigma_cts_iff_bdd_s_cts_Sak_1_8_10"
Krein--Smulian promotes ultraweak continuity on the unit ball to global
continuity.  Equality of the strong and ultraweak continuous duals transports
closure of the convex intersection of the kernel with the ball and gives the
strong version.  This compares continuous functionals; it does not claim that
bounded ultraweak convergence implies strong convergence.
:::
