import Verso
import VersoManual
import VersoBlueprint
import LeanOA.Ultraweak.FunctionalPolarDecomposition
import LeanOA.Ultraweak.FunctionalJordanDecomposition
import LeanOA.Ultraweak.FunctionalSupport

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Functional support and functional decompositions" =>

This chapter formalizes Sakai's Definitions 1.14.1--1.14.2 and Theorems
1.14.3--1.14.4.  For a normal positive functional $`\varphi` on a
$`W^*`-algebra, its GNS null space is a closed left ideal generated by a
projection.  The complement of that generator is the support of $`\varphi`.
Orthogonality of positive functionals is defined by Sakai's norm equality;
self-adjoint normal functionals have unique orthogonal positive/negative
decompositions; and arbitrary normal functionals have unique polar
decompositions with the source's right-multiplication convention.

The public progression is

$`
  \text{normal positive functional}
  \longrightarrow \text{null left ideal}
  \longrightarrow \text{support}
  \longrightarrow \text{greatest zero projection}
  \longrightarrow \text{support cutdown}
  \longrightarrow \text{faithful support corner}
  \longrightarrow \text{norm orthogonality}
  \longrightarrow \text{unique Jordan decomposition}
  \longrightarrow \text{unique general polar decomposition}.
`

The construction reuses the established projection-normality predicate,
closed-left-ideal classifier, projection order, and corner API.  It introduces
neither a second kind of normal functional nor a second notion of corner.

{index}[support projection, of a functional]
{index}[normal positive functional]
{index}[null left ideal]
{index}[faithful functional]
{index}[orthogonal positive functionals]
{index}[Jordan decomposition, of a normal functional]
{index}[polar decomposition, of a normal functional]
{index}[absolute value, of a normal functional]

:::group "functional-support"
The null left ideal and support of a normal positive functional.
:::

# The null left ideal
%%%
tag := "functional-support"
%%%

:::definition "def:functional_null_ideal_Sak_1_14_2" (parent := "functional-support") (lean := "PositiveLinearMap.nullIdeal, PositiveLinearMap.mem_nullIdeal, PositiveLinearMap.apply_star_mul_eq_zero_of_apply_star_mul_self_eq_zero_left, PositiveLinearMap.apply_star_mul_eq_zero_of_apply_star_mul_self_eq_zero_right, PositiveLinearMap.mem_nullIdeal_iff_forall_apply_star_mul_eq_zero") (uses := "def:cstar_def")
For a positive functional $`\varphi` on a $`C^*`-algebra $`A`, define its
_null left ideal_ by

$`
  \mathcal N_\varphi
    = \{x\in A\mid \varphi(x^*x)=0\}.
`

It is a left ideal, and membership is equivalently characterized by
$`\varphi(y^*x)=0` for every $`y\in A`.  This algebraic construction does
not require normality or a predual; the formal definition is therefore made
at the $`C^*`-algebra level rather than only for $`W^*`-algebras.
:::

:::proof "def:functional_null_ideal_Sak_1_14_2"
Positive-functional Cauchy--Schwarz shows that
$`\varphi(x^*x)=0` forces both $`\varphi(x^*y)=0` and
$`\varphi(y^*x)=0` for every $`y`.  Expanding
$`(x+y)^*(x+y)` proves additive closure.  Applying the same coefficient
vanishing to $`a^*ax` proves closure under left multiplication by $`a`.
Taking $`y=x` recovers the quadratic condition from the coefficient
characterization.
:::

:::proposition "prop:functional_null_ideal_closed_Sak_1_14_2" (parent := "functional-support") (lean := "PositiveLinearMap.IsNormalOnProjections.isClosed_nullIdeal_strong, PositiveLinearMap.IsNormalOnProjections.isClosed_nullIdeal_ultraweak") (uses := "def:functional_null_ideal_Sak_1_14_2, def:normal_on_projections, thm:sigma_cts_of_normal_Sak_1_13_2, def:strong_top, def:sigma_top")
Let $`M` be a $`C^*`-algebra with a specified complete Banach predual $`P`,
and let $`\varphi` be a normal positive functional.  Then
$`\mathcal N_\varphi` is closed in the strong topology $`s(M,P)` and hence
in the ultraweak topology $`\sigma(M,P)`.  No separate `WStarAlgebra`
instance is required for these topology-specific theorems.

This follows Sakai's order of proof: strong closedness comes first, and the
passage to ultraweak closedness uses equality of strong and ultraweak closures
for convex sets.
:::

:::proof "prop:functional_null_ideal_closed_Sak_1_14_2"
Normality identifies $`\varphi` with a positive ultraweakly continuous
functional.  Its associated strong seminorm is

$`
  x\longmapsto \sqrt{\lVert\varphi(x^*x)\rVert},
`

so $`\mathcal N_\varphi` is the inverse image of $`\{0\}` under a
continuous strong seminorm.  It is therefore strongly closed.  A left ideal
is real-convex, and the established strong-to-ultraweak closure equivalence
then makes it ultraweakly closed.  The specified predual appears only in
these topology-dependent statements.
:::

# Functional support

:::definition "def:functional_support_Sak_1_14_2" (parent := "functional-support") (lean := "PositiveLinearMap.support, PositiveLinearMap.nullIdeal_eq_span_one_sub_support") (uses := "prop:functional_null_ideal_closed_Sak_1_14_2, prop:left_ideals_in_wstar_proj_Sak_1_10_1")
Let $`\varphi` be a normal positive functional on a $`W^*`-algebra $`M`.
There is a unique projection $`p_0` such that
$`\mathcal N_\varphi=Mp_0`.  The _support_ of $`\varphi` is

$`
  s(\varphi)=1-p_0,
`

so equivalently
$`\mathcal N_\varphi=M(1-s(\varphi))`.

The Lean definition is `PositiveLinearMap.support`.  It takes a proof of the
established `PositiveLinearMap.IsNormalOnProjections` predicate and returns a
star projection.  Its public statement has the ordinary $`W^*`-algebra
context; the canonical predual used to classify the ideal remains internal.
This functional support is distinct from support of an algebra element.
:::

:::proof "def:functional_support_Sak_1_14_2"
Apply the existing classification of ultraweakly closed left ideals to
$`\mathcal N_\varphi`.  It gives a unique star projection $`p_0` with
$`\mathcal N_\varphi=\operatorname{span}\{p_0\}=Mp_0`.  Take the
complementary star projection $`1-p_0`.  Uniqueness of the ideal generator
makes the construction independent of its internal choice.
:::

:::proposition "prop:functional_support_greatest_zero_Sak_1_14_2" (parent := "functional-support") (lean := "PositiveLinearMap.mem_nullIdeal_iff_mul_support_eq_zero, PositiveLinearMap.apply_star_mul_self_eq_zero_iff_mul_support_eq_zero, PositiveLinearMap.apply_eq_zero_iff_le_one_sub_support, PositiveLinearMap.isGreatest_setOf_apply_eq_zero") (uses := "def:functional_support_Sak_1_14_2, lem:projection_mul_eq_zero_iff_le_complement")
The support is characterized intrinsically by

$`
  x\in\mathcal N_\varphi
    \quad\Longleftrightarrow\quad
  x\,s(\varphi)=0.
`

In particular, for every projection $`q`,

$`
  \varphi(q)=0
    \quad\Longleftrightarrow\quad
  q\leq 1-s(\varphi).
`

Thus $`1-s(\varphi)` is the greatest projection on which $`\varphi`
vanishes.  The multiplication in the annihilator formula is on the right:
$`\mathcal N_\varphi` is the left ideal $`M(1-s(\varphi))`.
:::

:::proof "prop:functional_support_greatest_zero_Sak_1_14_2"
Membership in $`M(1-s(\varphi))` is equivalent to right annihilation by
$`s(\varphi)`.  For a projection $`q`, one has $`q^*q=q`, so the defining
quadratic nullity condition reduces to $`\varphi(q)=0`.  Finally,
$`q s(\varphi)=0` is equivalent to
$`q\leq1-s(\varphi)` by the established projection-order lemma.  This gives
both directions and the greatest-element statement.
:::

:::theorem "thm:functional_support_cutdown_Sak_1_14_2" (parent := "functional-support") (lean := "PositiveLinearMap.apply_mul_one_sub_support, PositiveLinearMap.apply_one_sub_support_mul, PositiveLinearMap.apply_mul_support, PositiveLinearMap.apply_support_mul, PositiveLinearMap.apply_support_mul_support") (uses := "prop:functional_support_greatest_zero_Sak_1_14_2")
For every $`x\in M`, Sakai's support cutdown identities are

$`
  \varphi(x)
  =\varphi(s(\varphi)x)
  =\varphi(xs(\varphi))
  =\varphi(s(\varphi)x s(\varphi)).
`

Equivalently, multiplication on either side by the complementary projection
$`1-s(\varphi)` is invisible to $`\varphi`.  No commutation or centrality of
$`s(\varphi)` is asserted.
:::

:::proof "thm:functional_support_cutdown_Sak_1_14_2"
The complementary projection lies in $`\mathcal N_\varphi`.  The coefficient
vanishing form of Cauchy--Schwarz therefore gives
$`\varphi(x(1-s(\varphi)))=0` and
$`\varphi((1-s(\varphi))x)=0`.  Expanding the complementary projection
proves the two one-sided identities, and composing them gives the two-sided
cutdown.
:::

:::proposition "prop:functional_support_faithfulness_Sak_1_14_2" (parent := "functional-support") (lean := "PositiveLinearMap.support_eq_one_iff_apply_star_mul_self_eq_zero_imp, PositiveLinearMap.apply_star_mul_self_eq_zero_iff_on_support_corner, PositiveLinearMap.apply_eq_zero_iff_of_nonneg_on_support_corner") (uses := "prop:functional_support_greatest_zero_Sak_1_14_2, thm:functional_support_cutdown_Sak_1_14_2")
Sakai calls $`\varphi` _faithful_ when $`s(\varphi)=1`.  This is equivalent
to triviality of its quadratic null space:

$`
  s(\varphi)=1
  \quad\Longleftrightarrow\quad
  \bigl(\varphi(x^*x)=0\Longrightarrow x=0\bigr)
  \quad\text{for every }x\in M.
`

*Derived consequence.*  The restriction of $`\varphi` to its support
corner $`s(\varphi)Ms(\varphi)` is faithful: a corner element $`x` satisfies
$`\varphi(x^*x)=0` exactly when $`x=0`; equivalently, a nonnegative corner
element has zero functional value exactly when it is zero.  This corner
statement is a useful consequence of Definition 1.14.2, but is not presented
there as a separate verbatim source assertion.
:::

:::proof "prop:functional_support_faithfulness_Sak_1_14_2"
If $`s(\varphi)=1`, the support-annihilator characterization immediately
makes the quadratic kernel trivial.  Conversely, apply triviality to
$`1-s(\varphi)`, which belongs to the null ideal.

For $`x` in the support corner, the equality $`x s(\varphi)=x` combines with
$`\varphi(x^*x)=0\Longleftrightarrow x s(\varphi)=0` to give $`x=0`.
For a nonnegative corner element, apply the quadratic statement to its
continuous-functional-calculus square root.
:::

# Orthogonality of positive functionals

:::definition "def:positive_functional_orthogonality_Sak_1_14_1" (parent := "functional-support") (lean := "PositiveLinearMap.IsOrthogonal, PositiveLinearMap.isOrthogonal_comm") (uses := "def:cstar_def")
Positive functionals $`\varphi_1` and $`\varphi_2` are _orthogonal_ when

$`
  \lVert\varphi_1-\varphi_2\rVert
  =\lVert\varphi_1\rVert+\lVert\varphi_2\rVert.
`

This is Sakai's Definition 1.14.1 itself, not a replacement by a support
condition.  The Lean relation is defined at nonunital $`C^*`-algebra
generality and is symmetric.
:::

:::theorem "thm:positive_functional_orthogonality_support_Sak_1_14_1" (parent := "functional-support") (lean := "PositiveLinearMap.isOrthogonal_iff_support_mul_eq_zero") (uses := "def:positive_functional_orthogonality_Sak_1_14_1, thm:functional_support_cutdown_Sak_1_14_2, thm:normal_functional_Jordan_decomposition_Sak_1_14_3")
If $`\varphi_1` and $`\varphi_2` are normal positive functionals on a
$`W^*`-algebra, then

$`
  \varphi_1\perp\varphi_2
  \quad\Longleftrightarrow\quad
  s(\varphi_1)s(\varphi_2)=0.
`

Thus support orthogonality is a structural characterization of Sakai's
norm-theoretic relation.  It is not a competing definition.
:::

:::proof "thm:positive_functional_orthogonality_support_Sak_1_14_1"
Orthogonal supports give the norm equality by evaluating
$`\varphi_1-\varphi_2` on the contraction
$`s(\varphi_1)-s(\varphi_2)` and using
$`\lVert\varphi_i\rVert=\varphi_i(1)`.  Conversely, represent the normal
self-adjoint difference on the canonical ultraweak predual.  Its canonical
Jordan pair has orthogonal supports; uniqueness of that pair identifies it
with $`(\varphi_1,\varphi_2)`, forcing the displayed product to vanish.
:::

# Orthogonal Jordan decomposition

:::theorem "thm:normal_functional_Jordan_decomposition_Sak_1_14_3" (parent := "functional-support") (lean := "Ultraweak.existsUnique_orthogonal_decomposition_of_isSelfAdjoint") (uses := "def:positive_functional_orthogonality_Sak_1_14_1, def:normal_on_projections, thm:polar_decomposition_ultraweak_functional, thm:functional_support_cutdown_Sak_1_14_2")
Let $`M` be a $`W^*`-algebra and let $`f\in M_*` be self-adjoint.  There is
a unique pair of normal positive functionals $`f_+` and $`f_-` such that

$`
  f=f_+-f_-,
  \qquad f_+\perp f_-.
`

Equivalently, by Definition 1.14.1,

$`
  \lVert f\rVert
    =\lVert f_+\rVert+\lVert f_-\rVert.
`

The formal statement represents $`f\in M_*` as a continuous linear
functional on a specified ultraweak topology, then states the difference
and norm relation after pulling it back to the ordinary normed algebra.  Its
positive parts are ordinary positive linear maps with explicit intrinsic
normality proofs, so their supports and downstream $`W^*` APIs apply
directly.
:::

:::proof "thm:normal_functional_Jordan_decomposition_Sak_1_14_3"
The existing self-adjoint functional factorization writes
$`f(x)=\phi(ux)` with $`\phi` positive and normal and $`u` a self-adjoint
unitary.  Put $`p=(1+u)/2` and $`q=1-p`; these are complementary
projections.  Cutting $`\phi` down by $`p` and $`q` produces normal positive
functionals $`f_+` and $`f_-`.  The equality $`u=p-q` gives the difference,
while norm preservation in the factorization and the positive-functional
formula $`\lVert\phi\rVert=\phi(1)` give the exact norm sum.

For uniqueness, the carrier equations force the canonical parts into the
complementary support corners.  Any competing normal positive pair with the
same difference and norm sum has the same component norms; evaluation on
$`p` then forces the same support containments.  The established support
cutdown identities identify both components.
:::

# General polar decomposition

:::theorem "thm:normal_functional_polar_decomposition_Sak_1_14_4" (parent := "functional-support") (lean := "Ultraweak.existsUnique_functional_polar_decomposition, Ultraweak.functionalAbs, Ultraweak.functionalAbs_spec, Ultraweak.norm_functionalAbs, Ultraweak.functional_polar_decomposition_final_projection") (uses := "prop:functional_support_greatest_zero_Sak_1_14_2, thm:functional_support_cutdown_Sak_1_14_2, thm:krein_milman, lem:extreme_partial_isom, def:sigma_top")
Let $`M` be a $`W^*`-algebra and let $`g\in M_*` be arbitrary.  There is a
unique pair consisting of an element $`v\in M` and a normal positive
functional $`\varphi` such that

$`
  g(x)=\varphi(xv),
  \qquad \lVert g\rVert=\lVert\varphi\rVert,
  \qquad v^*v=s(\varphi).
`

The last equation makes $`v` a partial isometry with initial projection
$`s(\varphi)`.  Sakai writes $`\varphi=\lvert g\rvert`; with this notation,
the final projection is

$`
  vv^*=s(\lvert g^*\rvert).
`

The multiplication convention is essential: the source's $`R_v\varphi`
means $`(R_v\varphi)(x)=\varphi(xv)`.  In Lean this is
`PositiveLinearMap.cutoff v`, and the uniqueness assertion is uniqueness of
the whole pair $`(v,\varphi)`, not merely of the positive factor.
:::

:::proof "thm:normal_functional_polar_decomposition_Sak_1_14_4"
Expose the real part of $`g` on the ultraweakly compact closed unit ball and
choose an extreme point $`u` of the resulting exposed face.  The established
extreme-point theorem makes the corresponding initial and final products
projections.  Right translation by $`u` is positive and norm preserving.
Trimming the extreme multiplier by the support of the resulting normal
positive functional gives $`v` and the exact factorization
$`g(x)=\varphi(xv)` with $`v^*v=s(\varphi)`.

For uniqueness, compare two normalized factorizations through their support
projections.  The support cutdown identities first identify the supports;
positive-functional nullity applied to
$`(v-w)^*(v-w)` then gives $`v=w`, and the factorization recovers the
positive functional.  Conjugating $`\varphi` by $`v` produces the canonical
positive factor of $`g^*`; its support is $`vv^*`, proving the final-projection
formula.  The chosen positive factor is exposed as
`Ultraweak.functionalAbs`, without introducing another normal-functional or
partial-isometry structure.
:::

# Next checkpoint

Definitions 1.14.1--1.14.2 and Theorems 1.14.3--1.14.4 are complete, so
Section 1.14 is closed.  Proposition 1.15.1 is now also source-formalized for
a possibly nonunital self-adjoint subalgebra of $`B(\mathcal H)`: global
closedness in WOT, coefficient-series $`\sigma`-WOT, SOT, the concrete
ultrastrong topology, and the concrete-predual ultraweak topology are
equivalent.  The difficult reverse implication uses the established relative
Kaplansky unit-ball theorem followed by scalar normalization.  The proof uses
only the one-way comparison maps available at this point in Sakai and does
not claim the later equality of the operator topologies.

The current exact numbered frontier remains Proposition 1.15.2, now at its
exact two-clause packaging step.  Both clauses are source-formalized.  On
each norm-closed ball of a WOT-closed self-adjoint subalgebra, WOT,
coefficient-series $`\sigma`-WOT, and the intrinsic topology
$`\sigma(N,N_*)` agree; on the same ball, SOT, concrete ultrastrong
convergence, and the intrinsic topology $`s(N,N_*)` agree.  Both results are
stated by canonical homeomorphisms and arbitrary-filter convergence, not
only for sequences.  The full proposition is not yet marked
source-formalized until the two printed clauses are packaged together
exactly, and no global equality of these topologies is claimed.

Sakai Proposition 1.15.1: SOURCE-FORMALIZED
Sakai Proposition 1.15.2(1): SOURCE-FORMALIZED
Sakai Proposition 1.15.2(2): SOURCE-FORMALIZED
Sakai Proposition 1.15.2: NOT SOURCE-FORMALIZED
