import Verso
import VersoManual
import VersoBlueprint

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Project overview" =>

Sak-AI has two complementary reading paths.

* The *mathematical path* follows Sakai.  The current formal development
  completes Section 1.10 through the central-support orthogonality theorem
  (Sakai 1.10.7); Section 1.11 on spectral resolution is next.
* The *library path* follows reusable Lean concepts: weak topologies and
  preduals, ultraweak continuity, closed ideals, projection lattices, and
  support constructions.  Names and assumptions are chosen for Mathlib
  portability rather than to mirror book numbering.

This Verso document is the sole mathematical-documentation source.  All
active legacy nodes, proof sketches, declaration links, and dependency edges
moved here before the old LeanBlueprint machinery was retired.  Git history
preserves that migration baseline.

The deployed site is accompanied by the
[Lean API documentation](https://jonbannon.github.io/Sak-AI/docs/) and the
[upstreaming dashboard](https://jonbannon.github.io/Sak-AI/upstreaming.html).

# Current frontier
%%%
tag := "current-frontier"
%%%

The connected Section 1.10 target is complete:

1. algebraic left and right annihilators;
2. left, right, and self-adjoint support projections;
3. the nonunital ultraweak algebra generated by an element;
4. ultraweakly closed two-sided ideals and central projections;
5. central support and its orthogonality theorem.

The next blueprint buildout should select a concrete endpoint in Sakai 1.11,
reconciling it first with current Mathlib's continuous functional calculus and
spectral-projection APIs.

# Migration parity

The generated legacy graph contains 87 active mathematical nodes, all now
formalized and represented in this Verso document.  Its source contains one
additional label inside a fully commented-out proposal about recovering the
norm from states; because that proposal had neither an active graph node nor
a Lean declaration, it is recorded as future work rather than counted as a
completed theorem.

The dependency graph below therefore represents the whole completed Sak-AI
development through Section 1.10, including C-star foundations, operator
topologies, positive separation, Stonean spectra and real rank zero,
normality and predual uniqueness, Kaplansky density, projection lattices, and
support and central-support theory.
