import Verso
import VersoManual
import VersoBlueprint
import LeanOA

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Projection order and closed ideals" =>

This chapter develops the order on self-adjoint projections and then uses
ultraweakly closed one-sided ideals to construct the complete projection
lattice of a W-star algebra.

{index}[projection]
{index}[left ideal]
{index}[projection lattice]

:::group "projection-order"
Algebraic order properties of projections.
:::

# Projection order
%%%
tag := "projection-order"
%%%

:::lemma_ "lem:proj_le_one" (parent := "projection-order") (lean := "IsStarProjection.le_one") (tags := "mathlib")
Every projection in a star-ordered ring is at most $`1`.
:::

:::proof "lem:proj_le_one"
The complement $`1-p` is a projection and therefore nonnegative; this is
precisely $`p\leq1`.
:::

:::lemma_ "lem:proj_sub_pos_iff_comm_eq_self" (parent := "projection-order") (lean := "IsStarProjection.le_tfae") (uses := "lem:star_conj_pos, lem:proj_le_one")
For projections $`p,q` in a C-star algebra,
$`q\leq p` if and only if $`qp=pq=q`.  Equivalently, $`p-q\geq0` exactly
under those multiplication identities.
:::

:::proof "lem:proj_sub_pos_iff_comm_eq_self"
If $`p-q\geq0`, conjugation by $`q` and $`p\leq1` squeeze $`qpq` between
$`q` and itself.  The C-star identity then turns $`q(p-q)q=0` into
$`(p-q)q=0`, giving $`pq=q`; adjoints give $`qp=q`.  Conversely these
identities make $`p-q` a projection, hence nonnegative.
:::

:::corollary "cor:proj_sub_of_subproj" (parent := "projection-order") (lean := "IsStarProjection.le_tfae") (uses := "lem:proj_sub_pos_iff_comm_eq_self")
If $`p` and $`q` are projections with $`q\leq p`, then $`p-q` is a
projection.
:::

:::proof "cor:proj_sub_of_subproj"
The preceding multiplication characterization gives $`pq=qp=q`; expanding
$`(p-q)^2` and taking adjoints proves idempotence and self-adjointness.
:::

:::group "closed-one-sided-ideals"
Ultraweakly closed one-sided ideals and the projection lattice.
:::

# Closed one-sided ideals
%%%
tag := "closed-one-sided-ideals"
%%%

:::proposition "prop:left_ideals_in_wstar_proj_Sak_1_10_1" (parent := "closed-one-sided-ideals") (lean := "Ideal.existsUnique_isStarProjection_eq_span_of_isClosed_ultraweak, CStarAlgebra.isUnital_of_isClosed_submodule") (uses := "lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8, lem:wstar_unital")
Every ultraweakly closed left ideal $`L` of a W-star algebra $`M` is
$`Mp` for a unique projection $`p`.  Formally, $`L` is Mathlib's native
`Ideal M`, and $`Mp` is `Ideal.span {p}`.
:::

:::proof "prop:left_ideals_in_wstar_proj_Sak_1_10_1"
The intersection $`N=L\cap L^*` is an ultraweakly closed nonunital star
subalgebra.  Its closed-submodule predual and W-star unitality give an
internal identity $`p`, which is a projection.  Certainly $`Mp\subseteq L`.
For $`x\in L`, the equality $`(x^*x)p=x^*x` and the C-star identity imply
$`xp=x`, giving the reverse inclusion.  If $`Mp=Mq`, the resulting
multiplication identities and their adjoints force $`p=q`.
:::

:::corollary "cor:right_ideals_in_wstar_proj_Sak_1_10_1" (parent := "closed-one-sided-ideals") (lean := "Ideal.existsUnique_isStarProjection_eq_span_op_of_isClosed_ultraweak") (uses := "prop:left_ideals_in_wstar_proj_Sak_1_10_1")
Every ultraweakly closed right ideal $`R` of $`M` is $`qM` for a unique
projection $`q`.  A right ideal is represented canonically as
`Ideal (MulOpposite M)`, with $`qM` represented by the principal ideal
generated by `MulOpposite.op q`.
:::

:::proof "cor:right_ideals_in_wstar_proj_Sak_1_10_1"
Transport the specified predual to $`M^{\mathrm{op}}` along `unop`.  A right
ideal of $`M` becomes a left ideal of the opposite algebra with the same
ultraweak closedness.  Apply the left-ideal theorem there and transport its
unique projection back.
:::

:::proposition "prop:proj_compl_lat_wstar_Sak_1_10_2" (parent := "closed-one-sided-ideals") (lean := "IsStarProjection.completeLatticeOfPredual, IsStarProjection.instCompleteLatticeSubtypeOfWStarAlgebra, IsStarProjection.isLUB_coe_of_isLUB, IsStarProjection.tendsto_toUltraweak_of_isLUB") (uses := "prop:left_ideals_in_wstar_proj_Sak_1_10_1, lem:proj_sub_pos_iff_comm_eq_self, lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8")
The subtype of projections of a W-star algebra is a complete lattice for the
ambient order.  A least upper bound of a nonempty directed family in this
projection lattice is also its least upper bound in the ambient C-star
algebra, and the canonical net converges to it ultraweakly.
:::

:::proof "prop:proj_compl_lat_wstar_Sak_1_10_2"
The map $`p\mapsto Mp` is an order isomorphism from projections to
ultraweakly closed left ideals.  Arbitrary intersections of such ideals are
again closed, so the projection corresponding to their intersection is the
infimum.  All infima give the complete lattice.  Although the construction
uses a specified predual, uniqueness of order-theoretic infima makes the
resulting operations independent of that choice.

For a directed family, ultraweak compactness produces an ambient least upper
bound which is again a projection.  Uniqueness identifies it with the lattice
supremum, and monotone convergence for the ultraweak order gives convergence
of the canonical net.
:::
