import Verso
import VersoManual
import VersoBlueprint
import LeanOA.Ultraweak.SpectralApproximation

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Lower spectral projections" =>

This chapter begins Sakai's Section 1.11.  It develops the lower spectral
projections of a self-adjoint element through norm convergence of the finite
spectral sums in Theorem 1.11.3: continuity from below, spectral-band and
endpoint estimates, and approximation along nested dyadic divisions.

{index}[spectral projection]
{index}[spectral resolution]
{index}[continuous functional calculus]

For a self-adjoint element $`h` of a W-star algebra, Sakai writes
$`e(\lambda)=s((\lambda 1-h)^+)`.  Pointwise, the scalar function
$`x\mapsto(\lambda-x)^+` is supported on $`(-\infty,\lambda)`, so the public
Lean name records the interval as `spectralProjectionIio`.

This construction does not duplicate the continuous-functional-calculus
projection associated with a *clopen* spectral subset.  A half-line cut need
not be clopen on the spectrum, and its indicator need not be continuous.
Instead, the W-star support operation turns the continuous positive cutoff
into the required projection.  The broader name `spectralProjection` remains
available for a future set-indexed spectral-measure interface.

:::group "lower-spectral-projections"
Positive scalar cutoffs and their support projections.
:::

# Positive cutoffs and lower spectral projections
%%%
tag := "lower-spectral-projections"
%%%

:::definition "def:spectral_positive_part" (parent := "lower-spectral-projections") (lean := "CStarAlgebra.spectralPositivePart, CStarAlgebra.spectralPositivePart_eq_posPart, CStarAlgebra.spectralPositivePart_nonneg, CStarAlgebra.continuous_spectralPositivePart") (uses := "cor:spec_sa_homeo_spec_cstar")
Let $`A` be a unital C-star algebra and let $`h=h^*\in A`.  For
$`\lambda\in\mathbb R`, define
$`b_h(\lambda)=\operatorname{cfc}_h(x\mapsto(\lambda-x)^+)`.  Then
$`b_h(\lambda)=(\lambda 1-h)^+`, it is nonnegative, and the map
$`\lambda\mapsto b_h(\lambda)` is norm-continuous.

This layer needs no predual or W-star structure.  Continuity is asserted only
along scalar translates inside the commutative C-star algebra generated by
$`h`; it is not an operator-Lipschitz claim for positive part on arbitrary
noncommuting elements.
:::

:::proof "def:spectral_positive_part"
Composition in the continuous functional calculus identifies the scalar
function $`x\mapsto(\lambda-x)^+` with the positive part of
$`\lambda 1-h`.  The scalar positive-part map is $`1`-Lipschitz, so changing
$`\lambda` changes these functions uniformly on $`\sigma(h)`.  Mathlib's
fixed-element continuity theorem for the continuous functional calculus then
gives norm continuity.
:::

:::definition "def:lower_spectral_projection_Sak_1_11" (parent := "lower-spectral-projections") (lean := "WStarAlgebra.spectralProjectionIio, WStarAlgebra.spectralProjectionIio_eq_support_posPart, WStarAlgebra.spectralProjectionIio_mul_spectralPositivePart, WStarAlgebra.spectralPositivePart_mul_spectralProjectionIio, WStarAlgebra.spectralProjectionIio_mul_posPart, WStarAlgebra.posPart_mul_spectralProjectionIio, WStarAlgebra.spectralProjectionIio_le_iff") (uses := "def:spectral_positive_part, prop:left_right_support_characterization")
Let $`M` be a W-star algebra and $`h=h^*\in M`.  The lower spectral projection
at $`\lambda` is
$`e_h(\lambda)=s(b_h(\lambda))=s((\lambda 1-h)^+)`.

It is characterized without retaining a choice of predual: for every
projection $`p`,
$`e_h(\lambda)\leq p` if and only if
$`p b_h(\lambda)=b_h(\lambda)`.
Moreover, $`e_h(\lambda)` fixes $`b_h(\lambda)` on both the left and the
right; these identities are exposed as simplification lemmas for subsequent
spectral-resolution calculations.
:::

:::proof "def:lower_spectral_projection_Sak_1_11"
Apply the existing support construction to the bundled self-adjoint positive
element $`b_h(\lambda)`.  Its leastness statement is exactly the established
left-support universal property.
:::

:::proposition "prop:lower_spectral_projection_mono_Sak_1_11" (parent := "lower-spectral-projections") (lean := "WStarAlgebra.spectralProjectionIio_mono") (uses := "def:lower_spectral_projection_Sak_1_11, lem:support_star_compatibility")
If $`\lambda\leq\mu`, then
$`e_h(\lambda)\leq e_h(\mu)`.
:::

:::proof "prop:lower_spectral_projection_mono_Sak_1_11"
The pointwise inequality
$`(\lambda-x)^+\leq(\mu-x)^+` passes through Mathlib's order-preserving
continuous functional calculus.  The resulting positive elements are ordered,
so monotonicity of support projections gives the conclusion.
:::

:::lemma_ "lem:lower_spectral_projection_continuity_Sak_1_11_1" (parent := "lower-spectral-projections") (lean := "WStarAlgebra.isLUB_range_spectralProjectionIio_of_tendsto, WStarAlgebra.tendsto_spectralProjectionIio_of_monotone") (uses := "def:spectral_positive_part, prop:lower_spectral_projection_mono_Sak_1_11, prop:proj_compl_lat_wstar_Sak_1_10_2")
Let $`I` be a nonempty directed preorder and let
$`\lambda_i` be an increasing net of real numbers converging to $`\lambda`.
Then $`e_h(\lambda)` is the least upper bound of the projections
$`e_h(\lambda_i)`, and
$`e_h(\lambda_i)\to e_h(\lambda)` ultraweakly.

Taking $`I=\mathbb N` gives Sakai's Lemma 1.11.1 for every increasing
sequence $`\lambda_n<\lambda` with $`\lambda_n\to\lambda`; the strict
inequality is not needed by the formal theorem.
:::

:::proof "lem:lower_spectral_projection_continuity_Sak_1_11_1"
Norm continuity of $`b_h` shows that any projection fixing every
$`b_h(\lambda_i)` also fixes $`b_h(\lambda)`.  The support universal property
therefore identifies $`e_h(\lambda)` as the least upper bound of the net of
projections.  Reuse the existing theorem that a directed projection supremum
is also an ambient order supremum, then apply monotone convergence in the
specified ultraweak topology.  No spectral measure or Radon--Stieltjes
integration is introduced at this checkpoint.
:::

:::group "spectral-band-increments"
Cut recovery, commutation, and the increment estimate of Sakai 1.11.2.
:::

# Spectral-band increments
%%%
tag := "spectral-band-increments"
%%%

:::proposition "prop:lower_spectral_projection_cut_recovery" (parent := "spectral-band-increments") (lean := "WStarAlgebra.sub_mul_spectralProjectionIio, WStarAlgebra.spectralProjectionIio_mul_sub, WStarAlgebra.commute_sub_spectralProjectionIio, WStarAlgebra.commute_spectralProjectionIio, WStarAlgebra.smul_spectralProjectionIio_sub_spectralPositivePart") (uses := "def:lower_spectral_projection_Sak_1_11, prop:left_right_support_characterization")
For every real $`\lambda`, the defining cutoff is recovered on either side
of its support:
$`
(\lambda 1-h)e_h(\lambda)
=e_h(\lambda)(\lambda 1-h)
=b_h(\lambda).
`
In particular, $`h` commutes with $`e_h(\lambda)` and
$`
\lambda e_h(\lambda)-b_h(\lambda)=h e_h(\lambda).
`
:::

:::proof "prop:lower_spectral_projection_cut_recovery"
Write $`x=\lambda 1-h=x^+-x^-`.  The support-zero-kernel
characterization and Mathlib's identities $`x^-x^+=x^+x^-=0` show that
$`x^-` is killed by $`s(x^+)` on both sides.  The two recovery identities
follow.  Their equality gives commutation with $`x`, hence with $`h` after
subtracting the central scalar $`\lambda 1`.  This proof uses no chosen
predual.
:::

:::lemma_ "lem:lower_spectral_projection_increment_bounds_Sak_1_11_2" (parent := "spectral-band-increments") (lean := "WStarAlgebra.spectralProjectionIio_band_bounds, WStarAlgebra.spectralProjectionIio_increment_bounds") (uses := "prop:lower_spectral_projection_mono_Sak_1_11, prop:lower_spectral_projection_cut_recovery")
If $`\lambda\leq\mu` and
$`p=e_h(\mu)-e_h(\lambda)`, then $`p` is a projection and
$`
\lambda p\leq hp\leq\mu p.
`
Consequently,
$`
\lambda\bigl(e_h(\mu)-e_h(\lambda)\bigr)
\leq
\bigl(\mu e_h(\mu)-b_h(\mu)\bigr)
-\bigl(\lambda e_h(\lambda)-b_h(\lambda)\bigr)
\leq
\mu\bigl(e_h(\mu)-e_h(\lambda)\bigr).
`
This is Sakai's Lemma 1.11.2.  The formal result strengthens the printed
strict hypothesis $`\lambda<\mu` to $`\lambda\leq\mu`.
:::

:::proof "lem:lower_spectral_projection_increment_bounds_Sak_1_11_2"
Monotonicity makes $`p=e_h(\mu)-e_h(\lambda)` a projection.  On this band,
the positive part of $`\lambda 1-h` and the negative part of
$`\mu 1-h` vanish.  The remaining products are nonnegative because the
functional-calculus parts commute with $`p`.  This proves
$`\lambda p\leq hp\leq\mu p`.  Replacing each
$`t e_h(t)-b_h(t)` by $`h e_h(t)` gives the displayed increment estimate.
:::

:::group "spectral-family-endpoints"
The endpoint behavior in Sakai 1.11.3.
:::

# Endpoint behavior
%%%
tag := "spectral-family-endpoints"
%%%

:::proposition "prop:lower_spectral_projection_endpoints_Sak_1_11_3" (parent := "spectral-family-endpoints") (lean := "WStarAlgebra.spectralProjectionIio_eq_zero_of_le_neg_norm, WStarAlgebra.spectralProjectionIio_eq_one_of_norm_lt, WStarAlgebra.tendsto_spectralProjectionIio_atBot, WStarAlgebra.tendsto_spectralProjectionIio_atTop") (uses := "def:lower_spectral_projection_Sak_1_11, lem:support_star_compatibility")
For a self-adjoint $`h` in a W-star algebra,
$`
  e_h(\lambda)=0 \quad\text{if }\lambda\leq-\lVert h\rVert,
  \qquad
  e_h(\lambda)=1 \quad\text{if }\lVert h\rVert<\lambda.
`
Consequently, for any specified predual,
$`e_h(\lambda)` converges ultraweakly to $`0` as $`\lambda\to-\infty`
and to $`1` as $`\lambda\to+\infty`.

The lower bound is stated with a weak inequality, strengthening the strict
version used in Sakai's proof.  The strict upper inequality is essential in
general: at $`\lambda=\lVert h\rVert`, a top spectral value can remain in the
kernel of $`\lambda1-h`.
:::

:::proof "prop:lower_spectral_projection_endpoints_Sak_1_11_3"
Mathlib's order bounds for a self-adjoint element give
$`-\lVert h\rVert1\leq h\leq\lVert h\rVert1`.  Below the lower endpoint,
$`\lambda1-h\leq0`, so its positive part and hence its support vanish.
Above the upper endpoint, $`\lambda1-h` is bounded below by the positive
scalar $`(\lambda-\lVert h\rVert)1`.  The general support-one criterion then
shows that its positive part has full support.  Both nets are eventually
constant, which gives the ultraweak limits without invoking a convergence
theorem specific to projections.
:::

:::group "finite-spectral-sums"
Finite-partition approximation in Sakai 1.11.3.
:::

# Finite spectral sums
%%%
tag := "finite-spectral-sums"
%%%

:::definition "def:finite_spectral_sums_Sak_1_11_3" (parent := "finite-spectral-sums") (lean := "WStarAlgebra.lowerSpectralSum, WStarAlgebra.upperSpectralSum, WStarAlgebra.isSelfAdjoint_lowerSpectralSum, WStarAlgebra.isSelfAdjoint_upperSpectralSum, WStarAlgebra.sum_spectralProjectionIio_sub") (uses := "def:lower_spectral_projection_Sak_1_11")
For real cuts $`\lambda_0,\ldots,\lambda_n`, define the lower and upper
spectral sums
$`
  m(\lambda)=\sum_{i<n}\lambda_i
    \bigl(e_h(\lambda_{i+1})-e_h(\lambda_i)\bigr),
  \qquad
  M(\lambda)=\sum_{i<n}\lambda_{i+1}
    \bigl(e_h(\lambda_{i+1})-e_h(\lambda_i)\bigr).
`
Both sums are self-adjoint, and their unweighted band projections telescope:
$`
  \sum_{i<n}\bigl(e_h(\lambda_{i+1})-e_h(\lambda_i)\bigr)
  =e_h(\lambda_n)-e_h(\lambda_0).
`

The Lean interface takes a function `cut : ℕ → ℝ` and the first `n`
adjacent intervals.  This keeps the construction compatible with Mathlib's
ordinary finite sums and avoids introducing a bespoke partition structure.
:::

:::proof "def:finite_spectral_sums_Sak_1_11_3"
Self-adjointness is preserved by real scalar multiplication, subtraction,
and finite sums.  The band identity is Mathlib's telescoping-sum theorem
applied to the function $`i\mapsto e_h(\lambda_i)`.
:::

:::proposition "prop:finite_spectral_sum_estimate_Sak_1_11_3" (parent := "finite-spectral-sums") (lean := "WStarAlgebra.lowerSpectralSum_le_mul_spectralProjectionIio_sub, WStarAlgebra.mul_spectralProjectionIio_sub_le_upperSpectralSum, WStarAlgebra.upperSpectralSum_sub_lowerSpectralSum, WStarAlgebra.upperSpectralSum_sub_lowerSpectralSum_le, WStarAlgebra.spectralProjectionIio_sub_eq_one_of_endpoint_bounds, WStarAlgebra.lowerSpectralSum_le_self, WStarAlgebra.self_le_upperSpectralSum, WStarAlgebra.lowerSpectralSum_le_self_and_self_le_upperSpectralSum, WStarAlgebra.upperSpectralSum_sub_lowerSpectralSum_le_smul_one, WStarAlgebra.norm_upperSpectralSum_sub_lowerSpectralSum_le, WStarAlgebra.norm_self_sub_lowerSpectralSum_le, WStarAlgebra.norm_upperSpectralSum_sub_self_le") (uses := "def:finite_spectral_sums_Sak_1_11_3, lem:lower_spectral_projection_increment_bounds_Sak_1_11_2, prop:lower_spectral_projection_endpoints_Sak_1_11_3")
Suppose the cuts are increasing, satisfy
$`\lambda_0\leq-\lVert h\rVert` and
$`\lVert h\rVert<\lambda_n`, and every interval has width at most
$`\delta`.  Then
$`
  m(\lambda)\leq h\leq M(\lambda),
  \qquad
  0\leq M(\lambda)-m(\lambda)\leq\delta1.
`
Consequently,
$`
  \lVert M(\lambda)-m(\lambda)\rVert\leq\delta,
  \quad
  \lVert h-m(\lambda)\rVert\leq\delta,
  \quad
  \lVert M(\lambda)-h\rVert\leq\delta.
`
These are the finite-partition estimates used in the existence part of
Sakai's Theorem 1.11.3.  The formal statements allow equal adjacent cuts;
nonnegativity of $`\delta` follows from the other hypotheses and is not
assumed separately.
:::

:::proof "prop:finite_spectral_sum_estimate_Sak_1_11_3"
Apply the spectral-band inequality from Lemma 1.11.2 on every adjacent
interval and sum.  The middle terms telescope to
$`h(e_h(\lambda_n)-e_h(\lambda_0))=h` by the endpoint formulas.  Subtracting
the lower sum from the upper sum weights each nonnegative band projection by
$`\lambda_{i+1}-\lambda_i\leq\delta`; summing and telescoping again gives the
order gap $`\delta1`.  Norm monotonicity on nonnegative elements yields the
three norm estimates.
:::

:::definition "def:dyadic_spectral_divisions_Sak_1_11_3" (parent := "finite-spectral-sums") (lean := "WStarAlgebra.dyadicSpectralMesh, WStarAlgebra.dyadicSpectralCut, WStarAlgebra.dyadicSpectralMesh_pos, WStarAlgebra.dyadicSpectralCut_monotone, WStarAlgebra.dyadicSpectralCut_zero, WStarAlgebra.dyadicSpectralCut_bandCount, WStarAlgebra.dyadicSpectralCut_succ_sub, WStarAlgebra.dyadicSpectralMesh_succ, WStarAlgebra.dyadicSpectralCut_refines, WStarAlgebra.tendsto_dyadicSpectralMesh") (uses := "def:finite_spectral_sums_Sak_1_11_3")
For $`k\in\mathbb N`, divide
$`[-\lVert h\rVert-1,\lVert h\rVert+1]` into $`2^k` equal bands.  Thus
$`
  \delta_k=\frac{2\lVert h\rVert+2}{2^k},
  \qquad
  \lambda_{k,i}=-\lVert h\rVert-1+i\delta_k.
`
These divisions have fixed endpoints, their cuts are increasing, and every
band has width $`\delta_k`.  The division at stage $`k+1` refines the one at
stage $`k`: its even-indexed cuts are exactly the old cuts.  Moreover,
$`\delta_k\to0`.

The grid definitions and their arithmetic properties only assume a
seminormed additive star group.  They are not tied to W-star algebras.
:::

:::proof "def:dyadic_spectral_divisions_Sak_1_11_3"
The endpoint and refinement identities are elementary computations with
$`2^{k+1}=2\cdot2^k`.  Positivity of the mesh gives monotonicity of the cuts,
and the geometric sequence $`(2\lVert h\rVert+2)/2^k` tends to zero.
:::

:::proposition "prop:finite_spectral_sum_convergence_Sak_1_11_3" (parent := "finite-spectral-sums") (lean := "WStarAlgebra.tendsto_lowerSpectralSum, WStarAlgebra.tendsto_upperSpectralSum, WStarAlgebra.tendsto_lowerSpectralSum_dyadic, WStarAlgebra.tendsto_upperSpectralSum_dyadic") (uses := "prop:finite_spectral_sum_estimate_Sak_1_11_3, def:dyadic_spectral_divisions_Sak_1_11_3")
Let a filtered family of finite divisions eventually contain the spectral
interval of $`h`, and suppose its mesh bounds tend to zero.  Then both its
lower and upper spectral sums converge in norm to $`h`.

In particular, for the canonical dyadic divisions above,
$`
  m_k\longrightarrow h,
  \qquad
  M_k\longrightarrow h
`
in norm.  Hence Sakai's finite spectral sums give a concrete norm
approximation of $`h` along a genuinely nested sequence of divisions.

The formal convergence theorem is stated for an arbitrary filter, not only
for sequences.  It retains the unbundled cut, band-count, and mesh interface
of the finite estimates.
:::

:::proof "prop:finite_spectral_sum_convergence_Sak_1_11_3"
The finite-partition estimate gives
$`
  \lVert h-m_k\rVert\leq\delta_k,
  \qquad
  \lVert M_k-h\rVert\leq\delta_k.
`
For a general filtered family, the squeeze theorem therefore reduces both
norm limits to convergence of the mesh bounds.  The dyadic statement follows
by substituting the divisions above, whose endpoints contain
$`[-\lVert h\rVert,\lVert h\rVert]` and whose meshes tend to zero.
:::
