import Verso
import VersoManual
import VersoBlueprint
import LeanOA.Ultraweak.SpectralProjection

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Lower spectral projections" =>

This chapter begins Sakai's Section 1.11.  Its first completed checkpoint is
Lemma 1.11.1: the lower spectral projections of a self-adjoint element are
monotone and continuous from below in the ultraweak topology.

{index}[spectral projection]
{index}[spectral resolution]
{index}[continuous functional calculus]

For a self-adjoint element $`h` of a W-star algebra, Sakai writes
$`e(\lambda)=s((\lambda 1-h)^+)`.  Pointwise, the scalar function
$`x\mapsto(\lambda-x)^+` is supported on $`(-\infty,\lambda)`, so the public
Lean name records the interval as `spectralProjectionIio`.

This construction does not duplicate the continuous-functional-calculus
projection associated with a *clopen* spectral subset.  A half-line cut need
not be clopen on the spectrum, and its indicator need not be continuous.
Instead, the W-star support operation turns the continuous positive cutoff
into the required projection.  The broader name `spectralProjection` remains
available for a future set-indexed spectral-measure interface.

:::group "lower-spectral-projections"
Positive scalar cutoffs and their support projections.
:::

# Positive cutoffs and lower spectral projections
%%%
tag := "lower-spectral-projections"
%%%

:::definition "def:spectral_positive_part" (parent := "lower-spectral-projections") (lean := "CStarAlgebra.spectralPositivePart, CStarAlgebra.spectralPositivePart_eq_posPart, CStarAlgebra.spectralPositivePart_nonneg, CStarAlgebra.continuous_spectralPositivePart") (uses := "cor:spec_sa_homeo_spec_cstar")
Let $`A` be a unital C-star algebra and let $`h=h^*\in A`.  For
$`\lambda\in\mathbb R`, define
$`b_h(\lambda)=\operatorname{cfc}_h(x\mapsto(\lambda-x)^+)`.  Then
$`b_h(\lambda)=(\lambda 1-h)^+`, it is nonnegative, and the map
$`\lambda\mapsto b_h(\lambda)` is norm-continuous.

This layer needs no predual or W-star structure.  Continuity is asserted only
along scalar translates inside the commutative C-star algebra generated by
$`h`; it is not an operator-Lipschitz claim for positive part on arbitrary
noncommuting elements.
:::

:::proof "def:spectral_positive_part"
Composition in the continuous functional calculus identifies the scalar
function $`x\mapsto(\lambda-x)^+` with the positive part of
$`\lambda 1-h`.  The scalar positive-part map is $`1`-Lipschitz, so changing
$`\lambda` changes these functions uniformly on $`\sigma(h)`.  Mathlib's
fixed-element continuity theorem for the continuous functional calculus then
gives norm continuity.
:::

:::definition "def:lower_spectral_projection_Sak_1_11" (parent := "lower-spectral-projections") (lean := "WStarAlgebra.spectralProjectionIio, WStarAlgebra.spectralProjectionIio_le_iff") (uses := "def:spectral_positive_part, prop:left_right_support_characterization")
Let $`M` be a W-star algebra and $`h=h^*\in M`.  The lower spectral projection
at $`\lambda` is
$`e_h(\lambda)=s(b_h(\lambda))=s((\lambda 1-h)^+)`.

It is characterized without retaining a choice of predual: for every
projection $`p`,
$`e_h(\lambda)\leq p` if and only if
$`p b_h(\lambda)=b_h(\lambda)`.
:::

:::proof "def:lower_spectral_projection_Sak_1_11"
Apply the existing support construction to the bundled self-adjoint positive
element $`b_h(\lambda)`.  Its leastness statement is exactly the established
left-support universal property.
:::

:::proposition "prop:lower_spectral_projection_mono_Sak_1_11" (parent := "lower-spectral-projections") (lean := "WStarAlgebra.spectralProjectionIio_mono") (uses := "def:lower_spectral_projection_Sak_1_11, lem:support_star_compatibility")
If $`\lambda\leq\mu`, then
$`e_h(\lambda)\leq e_h(\mu)`.
:::

:::proof "prop:lower_spectral_projection_mono_Sak_1_11"
The pointwise inequality
$`(\lambda-x)^+\leq(\mu-x)^+` passes through Mathlib's order-preserving
continuous functional calculus.  The resulting positive elements are ordered,
so monotonicity of support projections gives the conclusion.
:::

:::lemma_ "lem:lower_spectral_projection_continuity_Sak_1_11_1" (parent := "lower-spectral-projections") (lean := "WStarAlgebra.isLUB_range_spectralProjectionIio_of_tendsto, WStarAlgebra.tendsto_spectralProjectionIio_of_monotone") (uses := "def:spectral_positive_part, prop:lower_spectral_projection_mono_Sak_1_11, prop:proj_compl_lat_wstar_Sak_1_10_2")
Let $`I` be a nonempty directed preorder and let
$`\lambda_i` be an increasing net of real numbers converging to $`\lambda`.
Then $`e_h(\lambda)` is the least upper bound of the projections
$`e_h(\lambda_i)`, and
$`e_h(\lambda_i)\to e_h(\lambda)` ultraweakly.

Taking $`I=\mathbb N` gives Sakai's Lemma 1.11.1 for every increasing
sequence $`\lambda_n<\lambda` with $`\lambda_n\to\lambda`; the strict
inequality is not needed by the formal theorem.
:::

:::proof "lem:lower_spectral_projection_continuity_Sak_1_11_1"
Norm continuity of $`b_h` shows that any projection fixing every
$`b_h(\lambda_i)` also fixes $`b_h(\lambda)`.  The support universal property
therefore identifies $`e_h(\lambda)` as the least upper bound of the net of
projections.  Reuse the existing theorem that a directed projection supremum
is also an ambient order supremum, then apply monotone convergence in the
specified ultraweak topology.  No spectral measure or Radon--Stieltjes
integration is introduced at this checkpoint.
:::
