import Verso
import VersoManual
import VersoBlueprint
import LeanOA

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Stonean spaces and real rank zero" =>

A compact Hausdorff space is _Stonean_ (extremally disconnected) when the
closure of every open set is open.  Projections in $`C(K)` are characteristic
functions of clopen sets, so Stonean spaces provide finite-spectrum
approximants.  This chapter connects that topology to masas in W-star
algebras and packages the reusable consequence as real rank zero.

{index}[Stonean space]
{index}[extremally disconnected]
{index}[real rank zero]
{index}[masa]

:::lemma_ "lem:fin_lin_approx_of_stonean_Sak_1_3_1" (lean := "instIsRealRankZeroContinuousMapOfTotallySeparatedSpaceOfCompactSpace, CStarAlgebra.IsRealRankZero.topologicalClosure_hull_isStarProjection")
If $`K` is a Stonean compact Hausdorff space, every positive element of
$`C(K)` can be uniformly approximated by finite linear combinations of
projections with nonnegative coefficients.
:::

:::proof "lem:fin_lin_approx_of_stonean_Sak_1_3_1"
A Stonean compact Hausdorff space is totally separated, so locally constant
self-adjoint functions are dense.  Thus $`C(K)` has real rank zero.  In a
real-rank-zero C-star algebra, the positive cone is the closure of the convex
cone generated by projections, exactly the stated approximation property.
:::

:::lemma_ "lem:cts_fns_ge_zero_le_one_directed" (lean := "ContinuousMap.directedOn_setOf_support_subset_Icc")
For a topological space $`K` and $`U\subseteq K`, the continuous functions
supported in $`U` and taking values in $`[0,1]` form a directed set under the
pointwise order.
:::

:::proof "lem:cts_fns_ge_zero_le_one_directed"
Given $`f` and $`g`, their pointwise maximum $`f\vee g` is continuous, still
supported in $`U`, still lies in $`[0,1]`, and is an upper bound for both.
:::

:::proposition "prop:stonean_of_cts_fcns_incr_cond_complete_Sak_1_3_2" (lean := "ExtremallyDisconnected.ofConditionallyCompletePartialOrderSupContinuousMap") (uses := "lem:cts_fns_ge_zero_le_one_directed")
Let $`K` be a locally compact $`R_1` space and $`\mathbb K` an `RCLike`
scalar field.  If every nonempty directed subset of $`C(K,\mathbb K)` that is
bounded above has a least upper bound, then $`K` is extremally disconnected.
:::

:::proof "prop:stonean_of_cts_fcns_incr_cond_complete_Sak_1_3_2"
It suffices to work with real-valued functions.  For an open $`U`, let $`S`
be the functions supported in $`U` with values in $`[0,1]`.  It is nonempty,
directed, and bounded above, so let $`f=\sup S`.  Urysohn functions show
$`f=1` on $`\overline U`.  If $`x\notin\overline U`, multiply by a function
that is $`1` on $`\overline U` and vanishes at $`x`; minimality of $`f`
forces $`f(x)=0`.  Hence the complement of $`\overline U` is the zero set of
$`f` and is closed, so $`\overline U` is open.
:::

:::lemma_ "lem:spec_masa_wstar_stonean_Sak_1_7_5" (lean := "StarSubalgebra.IsMasa.extremallyDisconnected_characterSpace") (uses := "prop:stonean_of_cts_fcns_incr_cond_complete_Sak_1_3_2, def:cstar_def, thm:comm_cstar_cts_fcns_Sak_1_2_1, lem:sigma_cont_of_normal_Sak_1_7_4")
The character space of every maximal commutative C-star subalgebra of a
W-star algebra is Stonean.
:::

:::proof "lem:spec_masa_wstar_stonean_Sak_1_7_5"
A nonempty directed family in the masa that is bounded above has an ambient
least upper bound by ultraweak monotone convergence.  Conjugation by each
unitary of the masa fixes the family and therefore its least upper bound.
Thus the bound commutes with the masa and belongs to it by maximality.
Transport this conditional completeness through the Gelfand transform and
apply the preceding Stonean criterion.
:::

:::theorem "thm:real_rank_zero_of_predual" (lean := "CStarAlgebra.isRealRankZero_of_predual") (uses := "lem:fin_lin_approx_of_stonean_Sak_1_3_1, lem:spec_masa_wstar_stonean_Sak_1_7_5")
Every C-star algebra with a specified Banach predual has real rank zero: its
finite-spectrum self-adjoint elements are norm dense in its self-adjoint
part.
:::

:::proof "thm:real_rank_zero_of_predual"
Extend the commutative star subalgebra generated by a self-adjoint $`x` to a
masa $`C`.  Its character space is Stonean.  Transporting finite-spectrum
approximants through the Gelfand transform approximates $`x` in $`C`, and the
inclusion into the ambient algebra preserves both norm convergence and finite
spectrum.
:::

:::corollary "cor:positive_functional_le_of_projection_le" (lean := "PositiveLinearMap.le_on_nonneg_of_le_on_isStarProjection") (uses := "def:cstar_def, lem:fin_lin_approx_of_stonean_Sak_1_3_1")
Let $`A` be a real-rank-zero C-star algebra and let $`\varphi,\psi` be
positive linear maps.  If $`\varphi(p)\leq\psi(p)` for every projection
$`p`, then the same inequality holds on every nonnegative element.  The
formal theorem does not require unitality and permits an ordered C-star
algebra as codomain.
:::

:::proof "cor:positive_functional_le_of_projection_le"
The inequality locus is a closed convex cone containing every projection and
hence their generated cone.  Real rank zero says the closure of that cone is
the whole positive cone.
:::
