module

public import LeanOA.Mathlib.Analysis.LocallyConvex.SquareSummableConvergenceCLM
public import LeanOA.Ultraweak.BoundedOperatorCoefficientSeries
public import LeanOA.Ultraweak.Strong
public import Mathlib.Analysis.InnerProductSpace.StarOrder
public import Mathlib.Analysis.InnerProductSpace.l2Space

/-!
# Ultrastrong convergence on bounded operators

For a complex Hilbert space `H`, this file compares Sakai's concrete ultrastrong topology on
`B(H)` with the intrinsic strong topology induced by the canonical concrete predual.

Every square-summable family `ξ` defines the positive normal functional

`T ↦ ∑' n, ⟪ξ n, T (ξ n)⟫`.

Its intrinsic GNS seminorm is exactly `T ↦ √(∑' n, ‖T (ξ n)‖ ^ 2)`. Consequently the identity
from the intrinsic strong carrier to the concrete ultrastrong carrier is continuous. It also
characterizes concrete ultrastrong convergence by coefficient-series sigma-weak convergence of
positive-square errors. The resulting bounded-set topology comparison is proved separately in
`LeanOA.Ultraweak.BoundedOperatorStrongTopology`.
-/

@[expose] public section

open scoped ComplexOrder ENNReal InnerProduct InnerProductSpace lp Ultraweak

noncomputable section

namespace ContinuousLinearMap

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

local notation "BH" => H →L[ℂ] H
local notation "BHPredual" => VectorFunctionalPredual ℂ H H
local notation "SeriesCore" => vectorFunctionalSeriesSpan (H := H)
local notation "SeriesWeak" =>
  WeakBilin (Ultraweak.testPairing (M := BH) SeriesCore)

/-- A bounded operator regarded as a point of Sakai's weak topology generated by
square-summable coefficient series. -/
def vectorFunctionalSeriesWeakOfCLM (T : BH) : SeriesWeak :=
  vectorFunctionalSeriesWeakOfUltraweakL
    (toUltraweak ℂ BHPredual T)

@[simp]
theorem vectorFunctionalSeriesWeakOfCLM_apply (T : BH) :
    vectorFunctionalSeriesWeakOfCLM T = T :=
  rfl

/-- The positive ultraweak functional obtained from a diagonal square-summable coefficient
series. -/
def vectorFunctionalDiagonalSeriesUltraweakP
    (ξ : ℓ²(ℕ, H)) : σ(BH, BHPredual) →P[ℂ] ℂ :=
  PositiveContinuousLinearMap.mk₀
    (vectorFunctionalSeriesUltraweakL (fun n ↦ ξ n) (fun n ↦ ξ n)) fun T hT ↦ by
      rw [vectorFunctionalSeriesUltraweakL_apply
        (fun n ↦ ξ n) (fun n ↦ ξ n) (lp.summable_norm_sq ξ) (lp.summable_norm_sq ξ)]
      apply tsum_nonneg
      intro n
      have hpos : ContinuousLinearMap.IsPositive (ofUltraweak T) :=
        (ContinuousLinearMap.nonneg_iff_isPositive _).mp
          (Ultraweak.ofUltraweak_nonneg.mpr hT)
      exact hpos.inner_nonneg_right (ξ n)

@[simp]
theorem vectorFunctionalDiagonalSeriesUltraweakP_apply
    (ξ : ℓ²(ℕ, H)) (T : σ(BH, BHPredual)) :
    vectorFunctionalDiagonalSeriesUltraweakP ξ T =
      ∑' n, ⟪ξ n, (ofUltraweak T) (ξ n)⟫_ℂ := by
  exact vectorFunctionalSeriesUltraweakL_apply
    (fun n ↦ ξ n) (fun n ↦ ξ n) (lp.summable_norm_sq ξ) (lp.summable_norm_sq ξ) T

end ContinuousLinearMap

private theorem boundedOperator_inner_star_mul_self_eq_norm_sq
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    (T : H →L[ℂ] H) (x : H) :
    ⟪x, (star T * T) x⟫_ℂ = (‖T x‖ ^ 2 : ℂ) := by
  simp [ContinuousLinearMap.star_eq_adjoint,
    ContinuousLinearMap.adjoint_inner_right, inner_self_eq_norm_sq_to_K]

namespace BoundedOperatorUltrastrong

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

local notation "BH" => H →L[ℂ] H
local notation "BHPredual" => ContinuousLinearMap.VectorFunctionalPredual ℂ H H
local notation "SeriesCore" => ContinuousLinearMap.vectorFunctionalSeriesSpan (H := H)
local notation "SeriesWeak" =>
  WeakBilin (Ultraweak.testPairing (M := BH) SeriesCore)

omit [InnerProductSpace ℂ H] [CompleteSpace H] in
private def l2OfSummableNormSq (ξ : ℕ → H)
    (hξ : Summable (fun n ↦ ‖ξ n‖ ^ 2)) : ℓ²(ℕ, H) :=
  ⟨ξ, (memℓp_gen_iff (p := (2 : ℝ≥0∞)) (by norm_num)).2 <| by
    simpa only [ENNReal.toReal_ofNat, Real.rpow_two] using hξ⟩

omit [InnerProductSpace ℂ H] [CompleteSpace H] in
@[simp]
private theorem l2OfSummableNormSq_apply (ξ : ℕ → H)
    (hξ : Summable (fun n ↦ ‖ξ n‖ ^ 2)) (n : ℕ) :
    l2OfSummableNormSq ξ hξ n = ξ n :=
  rfl

private theorem vectorFunctionalSeriesTestWeakL_positiveSquare_applyLp
    (ξ η : ℓ²(ℕ, H)) (T : BH) :
    ContinuousLinearMap.vectorFunctionalSeriesTestWeakL
        (fun n ↦ ξ n) (fun n ↦ η n) (lp.summable_norm_sq ξ) (lp.summable_norm_sq η)
        (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM (star T * T)) =
      ⟪ContinuousLinearMap.applyLpₗ η T,
        ContinuousLinearMap.applyLpₗ ξ T⟫_ℂ := by
  rw [ContinuousLinearMap.vectorFunctionalSeriesTestWeakL_apply]
  rw [lp.inner_eq_tsum]
  congr 1
  funext n
  simp only [ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM_apply,
    WeakBilin.linearEquiv_apply,
    ContinuousLinearMap.applyLpₗ_apply]
  simp [ContinuousLinearMap.star_eq_adjoint,
    ContinuousLinearMap.adjoint_inner_right]

private theorem testPairing_positiveSquare_series_eq_inner_applyLp
    (ξ η : ℓ²(ℕ, H)) (T : BH) :
    Ultraweak.testPairing (M := BH) SeriesCore (star T * T)
        ⟨ContinuousLinearMap.vectorFunctionalSeriesInPredual
            (fun n ↦ ξ n) (fun n ↦ η n),
          Submodule.subset_span
            (ContinuousLinearMap.vectorFunctionalSeriesInPredual_mem_seriesSet
              (fun n ↦ ξ n) (fun n ↦ η n)
              (lp.summable_norm_sq ξ) (lp.summable_norm_sq η))⟩ =
      ⟪ContinuousLinearMap.applyLpₗ η T,
        ContinuousLinearMap.applyLpₗ ξ T⟫_ℂ := by
  change ContinuousLinearMap.vectorFunctionalSeriesTestWeakL
        (fun n ↦ ξ n) (fun n ↦ η n) (lp.summable_norm_sq ξ) (lp.summable_norm_sq η)
        (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM (star T * T)) = _
  exact vectorFunctionalSeriesTestWeakL_positiveSquare_applyLp ξ η T

private theorem sqrt_norm_diagonalSeries_positiveSquare_eq
    (ξ : ℓ²(ℕ, H)) (T : BH) :
    √‖ContinuousLinearMap.vectorFunctionalSeriesTestWeakL
        (fun n ↦ ξ n) (fun n ↦ ξ n) (lp.summable_norm_sq ξ) (lp.summable_norm_sq ξ)
        (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM (star T * T))‖ =
      ContinuousLinearMap.squareSummableSeminorm ξ T := by
  rw [vectorFunctionalSeriesTestWeakL_positiveSquare_applyLp]
  rw [inner_self_eq_norm_sq_to_K]
  simp only [norm_pow, Real.sqrt_sq_eq_abs, abs_norm]
  rw [RCLike.norm_ofReal]
  rw [abs_of_nonneg (norm_nonneg _)]
  rfl

private theorem tendsto_seriesWeak_iff_forall_pairing
    {I : Type*} {l : Filter I} {f : I → SeriesWeak} {x : SeriesWeak} :
    Filter.Tendsto f l (nhds x) ↔
      ∀ p : SeriesCore,
        Filter.Tendsto (fun i ↦ WeakBilin.pairing
            (Ultraweak.testPairing (M := BH) SeriesCore) (f i) p) l
          (nhds (WeakBilin.pairing
            (Ultraweak.testPairing (M := BH) SeriesCore) x p)) := by
  rw [(WeakBilin.isInducing
    (Ultraweak.testPairing (M := BH) SeriesCore)).tendsto_nhds_iff]
  exact tendsto_pi_nhds

omit [CompleteSpace H] in
private theorem tendsto_applyLp_sub_of_tendsto
    {I : Type*} {l : Filter I} {u : I → (H →USOT[ℂ] H)}
    {T : H →USOT[ℂ] H} (hu : Filter.Tendsto u l (nhds T))
    (ξ : ℓ²(ℕ, H)) :
    Filter.Tendsto (fun i ↦ ContinuousLinearMap.applyLpₗ ξ
        (SquareSummableConvergenceCLM.toCLM (u i - T))) l (nhds 0) := by
  have hd : Filter.Tendsto (fun i ↦ u i - T) l (nhds 0) := by
    simpa using hu.sub_const T
  have hs :=
    ((SquareSummableConvergenceCLM.withSeminorms
      (𝕜 := ℂ) (E := H) (F := H)).continuous_seminorm ξ).tendsto 0 |>.comp hd
  apply tendsto_zero_iff_norm_tendsto_zero.mpr
  have hs' : Filter.Tendsto (fun i ↦
      SquareSummableConvergenceCLM.seminorm ξ (u i - T)) l (nhds 0) := by
    simpa only [Function.comp_def, SquareSummableConvergenceCLM.seminormFamily,
      map_zero] using hs
  simpa only [SquareSummableConvergenceCLM.seminorm_apply] using hs'

/-! ## Positive-square characterization of concrete ultrastrong convergence -/

/-- Concrete ultrastrong convergence makes the positive squares of the differences converge to
zero in Sakai's coefficient-series sigma-weak operator topology. No norm bound is needed. -/
theorem tendsto_vectorFunctionalSeriesWeak_positiveSquare_of_tendsto
    {I : Type*} {l : Filter I} {u : I → (H →USOT[ℂ] H)}
    {T : H →USOT[ℂ] H} (hu : Filter.Tendsto u l (nhds T)) :
    Filter.Tendsto (fun i ↦
      ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM
        (star (SquareSummableConvergenceCLM.toCLM (u i - T)) *
          SquareSummableConvergenceCLM.toCLM (u i - T))) l
      (nhds (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM (0 : BH))) := by
  apply tendsto_seriesWeak_iff_forall_pairing.mpr
  intro p
  let P : ContinuousLinearMap.VectorFunctionalPredual ℂ H H → Prop := fun q ↦
    Filter.Tendsto (fun i ↦ Predual.equivDual (𝕜 := ℂ) (M := BH)
      (P := ContinuousLinearMap.VectorFunctionalPredual ℂ H H)
      (star (SquareSummableConvergenceCLM.toCLM (u i - T)) *
        SquareSummableConvergenceCLM.toCLM (u i - T)) q) l (nhds 0)
  simp only [WeakBilin.pairing_apply,
    ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM_apply,
    WeakBilin.linearEquiv_apply, Ultraweak.testPairing_apply, map_zero]
  change P p.1
  refine Submodule.span_induction (p := fun q _ ↦ P q) ?_ ?_ ?_ ?_ p.2
  · intro q hq
    rcases hq with ⟨ξ, η, hξ, hη, rfl⟩
    let ξ₂ := l2OfSummableNormSq ξ hξ
    let η₂ := l2OfSummableNormSq η hη
    have hξlim := tendsto_applyLp_sub_of_tendsto hu ξ₂
    have hηlim := tendsto_applyLp_sub_of_tendsto hu η₂
    have hinner := Filter.Tendsto.inner (𝕜 := ℂ) hηlim hξlim
    convert hinner using 1
    · funext i
      exact testPairing_positiveSquare_series_eq_inner_applyLp ξ₂ η₂
        (SquareSummableConvergenceCLM.toCLM (u i - T))
    · simp
  · change P 0
    dsimp only [P]
    have heq : (fun i ↦ Predual.equivDual (𝕜 := ℂ) (M := BH)
        (P := ContinuousLinearMap.VectorFunctionalPredual ℂ H H)
        (star (SquareSummableConvergenceCLM.toCLM (u i - T)) *
          SquareSummableConvergenceCLM.toCLM (u i - T)) 0) =
        (fun _ : I ↦ (0 : ℂ)) := by
      funext i
      exact map_zero _
    rw [heq]
    exact tendsto_const_nhds
  · intro q r _ _ hq hr
    simpa only [P, map_add, Pi.add_apply, zero_add] using hq.add hr
  · intro c q _ hq
    simpa only [P, map_smul, smul_eq_mul, Pi.smul_apply, mul_zero] using hq.const_mul c

/-- If the positive squares of the differences converge coefficient-series sigma-weakly to zero,
then the original net converges concrete-ultrastrongly. No norm bound is needed. -/
theorem tendsto_of_tendsto_vectorFunctionalSeriesWeak_positiveSquare
    {I : Type*} {l : Filter I} {u : I → (H →USOT[ℂ] H)}
    {T : H →USOT[ℂ] H}
    (hsq : Filter.Tendsto (fun i ↦
      ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM
        (star (SquareSummableConvergenceCLM.toCLM (u i - T)) *
          SquareSummableConvergenceCLM.toCLM (u i - T))) l
      (nhds (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM (0 : BH)))) :
    Filter.Tendsto u l (nhds T) := by
  apply (SquareSummableConvergenceCLM.withSeminorms
    (𝕜 := ℂ) (E := H) (F := H)).tendsto_nhds u T |>.mpr
  intro ξ ε hε
  let φ := ContinuousLinearMap.vectorFunctionalSeriesTestWeakL
    (fun n ↦ ξ n) (fun n ↦ ξ n) (lp.summable_norm_sq ξ) (lp.summable_norm_sq ξ)
  have hφ : Filter.Tendsto (fun i ↦ φ
      (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM
        (star (SquareSummableConvergenceCLM.toCLM (u i - T)) *
          SquareSummableConvergenceCLM.toCLM (u i - T)))) l (nhds 0) := by
    have h := (φ.continuous.tendsto
      (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM (0 : BH))).comp hsq
    have hzero : φ
        (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM (0 : BH)) = 0 := by
      change φ 0 = 0
      exact map_zero φ
    simpa only [Function.comp_def, hzero] using h
  have hsqrt : Filter.Tendsto (fun i ↦ √‖φ
      (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM
        (star (SquareSummableConvergenceCLM.toCLM (u i - T)) *
          SquareSummableConvergenceCLM.toCLM (u i - T)))‖) l (nhds 0) := by
    simpa only [Function.comp_def, norm_zero, Real.sqrt_zero] using
      (((Real.continuous_sqrt.comp continuous_norm).tendsto (0 : ℂ)).comp hφ)
  have hevent := hsqrt.eventually (Metric.ball_mem_nhds 0 hε)
  filter_upwards [hevent] with i hi
  rw [Real.dist_0_eq_abs, abs_of_nonneg (Real.sqrt_nonneg _)] at hi
  change SquareSummableConvergenceCLM.seminorm ξ (u i - T) < ε
  simpa only [φ, sqrt_norm_diagonalSeries_positiveSquare_eq,
    SquareSummableConvergenceCLM.seminorm_apply,
    ContinuousLinearMap.squareSummableSeminorm_apply] using hi

/-- Concrete ultrastrong convergence is equivalent to coefficient-series sigma-weak convergence
of the positive squares `(u i - T)⋆ * (u i - T)` to zero. This global form requires no norm-bound
hypothesis; boundedness enters only when sigma-WOT is replaced by WOT. -/
theorem tendsto_iff_vectorFunctionalSeriesWeak_positiveSquare
    {I : Type*} {l : Filter I} {u : I → (H →USOT[ℂ] H)}
    {T : H →USOT[ℂ] H} :
    Filter.Tendsto u l (nhds T) ↔
      Filter.Tendsto (fun i ↦
        ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM
          (star (SquareSummableConvergenceCLM.toCLM (u i - T)) *
            SquareSummableConvergenceCLM.toCLM (u i - T))) l
        (nhds (ContinuousLinearMap.vectorFunctionalSeriesWeakOfCLM (0 : BH))) :=
  ⟨tendsto_vectorFunctionalSeriesWeak_positiveSquare_of_tendsto,
    tendsto_of_tendsto_vectorFunctionalSeriesWeak_positiveSquare⟩

/-- The GNS seminorm of a diagonal coefficient-series functional is exactly the corresponding
concrete square-summable application seminorm. -/
theorem gnsSeminorm_vectorFunctionalDiagonalSeriesUltraweakP
    (ξ : ℓ²(ℕ, H)) (T : BH) :
    ((ContinuousLinearMap.vectorFunctionalDiagonalSeriesUltraweakP ξ).comp
      (Ultraweak.toUltraweakPosCLM BHPredual)).toPositiveLinearMap.gnsSeminorm T =
      ContinuousLinearMap.squareSummableSeminorm ξ T := by
  rw [PositiveLinearMap.gnsSeminorm_apply,
    ContinuousLinearMap.squareSummableSeminorm_apply_eq_sqrt_tsum]
  change √‖ContinuousLinearMap.vectorFunctionalDiagonalSeriesUltraweakP ξ
    (toUltraweak ℂ BHPredual (star T * T))‖ = √(∑' n, ‖T (ξ n)‖ ^ 2)
  rw [ContinuousLinearMap.vectorFunctionalDiagonalSeriesUltraweakP_apply]
  simp only [ofUltraweak_toUltraweak]
  have hseries :
      (∑' n, ⟪ξ n, (star T * T) (ξ n)⟫_ℂ) =
        ((∑' n, ‖T (ξ n)‖ ^ 2 : ℝ) : ℂ) := by
    rw [Complex.ofReal_tsum]
    congr 1
    funext n
    simpa using boundedOperator_inner_star_mul_self_eq_norm_sq T (ξ n)
  rw [hseries, Complex.norm_real, Real.norm_eq_abs,
    abs_of_nonneg (tsum_nonneg fun _ ↦ sq_nonneg _)]

/-- The algebraic identity from the intrinsic strong carrier to the concrete ultrastrong
carrier. -/
def toSquareSummableₗ :
    Ultraweak.Strong BH BHPredual →ₗ[ℂ] (H →USOT[ℂ] H) where
  toFun T := SquareSummableConvergenceCLM.ofCLM (Ultraweak.ofStrong T)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

@[simp]
theorem toSquareSummableₗ_apply (T : Ultraweak.Strong BH BHPredual) :
    SquareSummableConvergenceCLM.toCLM (toSquareSummableₗ T) = Ultraweak.ofStrong T :=
  rfl

/-- The intrinsic strong topology on `B(H)` is finer than the concrete ultrastrong topology. -/
theorem continuous_toSquareSummableₗ :
    Continuous (toSquareSummableₗ (H := H)) := by
  apply SquareSummableConvergenceCLM.withSeminorms.continuous_of_continuous_comp
    toSquareSummableₗ
  intro ξ
  have hs := (Ultraweak.Strong.withSeminorms (M := BH) (P := BHPredual)).continuous_seminorm
    (ContinuousLinearMap.vectorFunctionalDiagonalSeriesUltraweakP ξ)
  refine hs.congr fun T ↦ ?_
  change
    ((ContinuousLinearMap.vectorFunctionalDiagonalSeriesUltraweakP ξ).comp
      (Ultraweak.toUltraweakPosCLM BHPredual)).toPositiveLinearMap.gnsSeminorm
        (Ultraweak.ofStrong T) =
      ContinuousLinearMap.squareSummableSeminorm ξ (Ultraweak.ofStrong T)
  exact gnsSeminorm_vectorFunctionalDiagonalSeriesUltraweakP ξ (Ultraweak.ofStrong T)

/-- The source-safe continuous identity from intrinsic strong convergence on `B(H)` to concrete
ultrastrong convergence. -/
def toSquareSummableL :
    Ultraweak.Strong BH BHPredual →L[ℂ] (H →USOT[ℂ] H) :=
  ⟨toSquareSummableₗ, continuous_toSquareSummableₗ⟩

@[simp]
theorem toSquareSummableL_apply (T : Ultraweak.Strong BH BHPredual) :
    SquareSummableConvergenceCLM.toCLM (toSquareSummableL T) = Ultraweak.ofStrong T :=
  rfl

/-- A concrete-ultrastrong-closed operator set is closed for the intrinsic strong topology. -/
theorem isClosed_strong_of_isClosed_squareSummable (S : Set BH)
    (hS : IsClosed {T : H →USOT[ℂ] H |
      SquareSummableConvergenceCLM.toCLM T ∈ S}) :
    IsClosed {T : Ultraweak.Strong BH BHPredual | Ultraweak.ofStrong T ∈ S} := by
  change IsClosed (toSquareSummableL ⁻¹'
    {T : H →USOT[ℂ] H | SquareSummableConvergenceCLM.toCLM T ∈ S})
  exact hS.preimage toSquareSummableL.continuous

end BoundedOperatorUltrastrong
