module

public import LeanOA.Mathlib.Analysis.InnerProductSpace.OperatorPredualSeries
public import LeanOA.Ultraweak.BoundedOperator
public import LeanOA.Ultraweak.TestWeak
public import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap

/-!
# Square-summable coefficient series for the concrete predual of `B(H)`

This file transports the generic coefficient-series API to the short concrete predual carrier of
bounded operators.  For a complex Hilbert space it then forms the span of precisely Sakai's
countable, separately square-summable coefficient-series functionals.  The resulting existing
`WeakBilin` carrier is used directly; no second `SigmaWOT` topology synonym is introduced.

The continuous identity constructed below goes only from the full specified-predual topology to
the weaker series-test topology.  Its converse would require the later representation of every
predual functional by a single pair of square-summable sequences and is deliberately not claimed.
-/

@[expose] public section

open scoped InnerProduct InnerProductSpace Ultraweak

noncomputable section

namespace ContinuousLinearMap

variable {ι 𝕜 E F : Type*} [RCLike 𝕜]
  [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  [NormedAddCommGroup F] [InnerProductSpace 𝕜 F]

set_option maxSynthPendingDepth 4

/-- A coefficient series, transported from the norm-closed coefficient space to the short
specified-predual carrier. -/
def vectorFunctionalSeriesInPredual (xi : ι → E) (eta : ι → F) :
    VectorFunctionalPredual 𝕜 E F :=
  (vectorFunctionalPredualEquivClosure (𝕜 := 𝕜) (E := E) (F := F)).symm
    (vectorFunctionalSeries (𝕜 := 𝕜) xi eta)

@[simp]
lemma vectorFunctionalPredualEquivClosure_vectorFunctionalSeriesInPredual
    (xi : ι → E) (eta : ι → F) :
    vectorFunctionalPredualEquivClosure
        (vectorFunctionalSeriesInPredual (𝕜 := 𝕜) xi eta) =
      vectorFunctionalSeries xi eta :=
  rfl

/-- Cauchy--Schwarz controls the norm of the coefficient series in the short predual carrier. -/
theorem norm_vectorFunctionalSeriesInPredual_le (xi : ι → E) (eta : ι → F)
    (hxi : Summable (fun i ↦ ‖xi i‖ ^ 2))
    (heta : Summable (fun i ↦ ‖eta i‖ ^ 2)) :
    ‖vectorFunctionalSeriesInPredual (𝕜 := 𝕜) xi eta‖ ≤
      √(∑' i, ‖xi i‖ ^ 2) * √(∑' i, ‖eta i‖ ^ 2) := by
  change ‖(vectorFunctionalPredualEquivClosure
    (𝕜 := 𝕜) (E := E) (F := F)).symm (vectorFunctionalSeries xi eta)‖ ≤ _
  rw [(vectorFunctionalPredualEquivClosure
    (𝕜 := 𝕜) (E := E) (F := F)).symm.norm_map]
  exact norm_vectorFunctionalSeries_le xi eta hxi heta

section Complete

variable [CompleteSpace F]

/-- Evaluation of a coefficient-series element of the short predual is its scalar coefficient
series. -/
theorem vectorFunctionalPredualEvaluation_vectorFunctionalSeriesInPredual (T : E →L[𝕜] F)
    (xi : ι → E) (eta : ι → F)
    (hxi : Summable (fun i ↦ ‖xi i‖ ^ 2))
    (heta : Summable (fun i ↦ ‖eta i‖ ^ 2)) :
    Predual.equivDual (𝕜 := 𝕜) (M := E →L[𝕜] F)
        (P := VectorFunctionalPredual 𝕜 E F) T
        (vectorFunctionalSeriesInPredual xi eta) =
      ∑' i, ⟪eta i, T (xi i)⟫_𝕜 := by
  rw [vectorFunctionalPredual_predualEquivDual_apply_apply,
    vectorFunctionalPredualEquivClosure_vectorFunctionalSeriesInPredual]
  exact vectorFunctionalClosureEvaluation_vectorFunctionalSeries T xi eta hxi heta

end Complete

/-! ## Sakai's countable coefficient-series test space -/

section Complex

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]

/-- The set of coefficient-series predual elements built from two separately square-summable
`ℕ`-indexed vector families.  The index type is intentionally `ℕ`, matching Sakai's definition. -/
def vectorFunctionalSeriesSet : Set (VectorFunctionalPredual ℂ H H) :=
  {p | ∃ xi eta : ℕ → H,
    Summable (fun n ↦ ‖xi n‖ ^ 2) ∧
    Summable (fun n ↦ ‖eta n‖ ^ 2) ∧
    vectorFunctionalSeriesInPredual xi eta = p}

/-- The linear test space generated by Sakai's square-summable coefficient-series
functionals. -/
def vectorFunctionalSeriesSpan : Submodule ℂ (VectorFunctionalPredual ℂ H H) :=
  Submodule.span ℂ (vectorFunctionalSeriesSet (H := H))

/-- Every separately square-summable coefficient series is one of the raw generators of the
series test space. -/
theorem vectorFunctionalSeriesInPredual_mem_seriesSet (xi eta : ℕ → H)
    (hxi : Summable (fun n ↦ ‖xi n‖ ^ 2))
    (heta : Summable (fun n ↦ ‖eta n‖ ^ 2)) :
    vectorFunctionalSeriesInPredual xi eta ∈ vectorFunctionalSeriesSet (H := H) :=
  ⟨xi, eta, hxi, heta, rfl⟩

/-- A single vector functional is a square-summable coefficient-series generator, represented by
families supported at index zero. -/
theorem vectorFunctionalInPredual_mem_seriesSet (xi eta : H) :
    vectorFunctionalInPredual (𝕜 := ℂ) xi eta ∈
      vectorFunctionalSeriesSet (H := H) := by
  let xis : ℕ → H := fun n ↦ if n = 0 then xi else 0
  let etas : ℕ → H := fun n ↦ if n = 0 then eta else 0
  have hxis : Summable (fun n ↦ ‖xis n‖ ^ 2) := by
    apply (hasSum_ite_eq 0 (‖xi‖ ^ 2)).summable.congr
    intro n
    by_cases hn : n = 0 <;> simp [xis, hn]
  have hetas : Summable (fun n ↦ ‖etas n‖ ^ 2) := by
    apply (hasSum_ite_eq 0 (‖eta‖ ^ 2)).summable.congr
    intro n
    by_cases hn : n = 0 <;> simp [etas, hn]
  refine ⟨xis, etas, hxis, hetas, ?_⟩
  apply (vectorFunctionalPredualEquivClosure
    (𝕜 := ℂ) (E := H) (F := H)).injective
  rw [vectorFunctionalPredualEquivClosure_vectorFunctionalSeriesInPredual,
    vectorFunctionalPredualEquivClosure_vectorFunctionalInPredual]
  have hseries : vectorFunctionalSeries (𝕜 := ℂ) xis etas =
      vectorFunctionalInClosure (𝕜 := ℂ) xi eta := by
    unfold vectorFunctionalSeries
    rw [show (fun n ↦ vectorFunctionalInClosure (𝕜 := ℂ) (xis n) (etas n)) =
        fun n ↦ if n = 0 then vectorFunctionalInClosure (𝕜 := ℂ) xi eta else 0 by
      funext n
      by_cases hn : n = 0
      · simp [xis, etas, hn]
      · simp only [xis, etas, if_neg hn]
        apply Subtype.ext
        ext T
        simp [vectorFunctionalInClosure, vectorFunctional_apply]]
    exact tsum_ite_eq 0 _
  rw [hseries]

/-- The image of every finite vector-functional combination lies in the series test space. -/
theorem vectorFunctionalSpanToPredual_mem_seriesSpan
    (f : vectorFunctionalSpan (𝕜 := ℂ) (E := H) (F := H)) :
    vectorFunctionalSpanToPredual f ∈ vectorFunctionalSeriesSpan (H := H) := by
  refine Submodule.span_induction
    (p := fun g hg ↦ vectorFunctionalSpanToPredual
      (⟨g, hg⟩ : vectorFunctionalSpan (𝕜 := ℂ) (E := H) (F := H)) ∈
        vectorFunctionalSeriesSpan (H := H)) ?_ ?_ ?_ ?_ f.2
  · intro g hg
    rw [mem_vectorFunctionals_iff] at hg
    obtain ⟨xi, eta, rfl⟩ := hg
    rw [vectorFunctionalSpanToPredual_vectorFunctional]
    change vectorFunctionalInPredual (𝕜 := ℂ) xi eta ∈
      Submodule.span ℂ (vectorFunctionalSeriesSet (H := H))
    exact Submodule.subset_span (vectorFunctionalInPredual_mem_seriesSet xi eta)
  · change vectorFunctionalSpanToPredual
      (0 : vectorFunctionalSpan (𝕜 := ℂ) (E := H) (F := H)) ∈
        vectorFunctionalSeriesSpan (H := H)
    rw [map_zero]
    exact (vectorFunctionalSeriesSpan (H := H)).zero_mem
  · intro g h hg hh ihg ihh
    change vectorFunctionalSpanToPredual
      ((⟨g, hg⟩ : vectorFunctionalSpan (𝕜 := ℂ) (E := H) (F := H)) +
        ⟨h, hh⟩) ∈ vectorFunctionalSeriesSpan (H := H)
    rw [map_add]
    exact (vectorFunctionalSeriesSpan (H := H)).add_mem ihg ihh
  · intro c g hg ih
    change vectorFunctionalSpanToPredual
      (c • (⟨g, hg⟩ : vectorFunctionalSpan (𝕜 := ℂ) (E := H) (F := H))) ∈
        vectorFunctionalSeriesSpan (H := H)
    rw [map_smul]
    exact (vectorFunctionalSeriesSpan (H := H)).smul_mem c ih

/-- The finite coefficient core is contained in Sakai's coefficient-series test space. -/
theorem vectorFunctionalPredualSpan_le_seriesSpan :
    vectorFunctionalPredualSpan (𝕜 := ℂ) (E := H) (F := H) ≤
      vectorFunctionalSeriesSpan (H := H) := by
  intro p hp
  obtain ⟨f, rfl⟩ := hp
  exact vectorFunctionalSpanToPredual_mem_seriesSpan f

/-- Sakai's coefficient-series test space is norm dense in the concrete predual. -/
theorem dense_vectorFunctionalSeriesSpan :
    Dense (vectorFunctionalSeriesSpan (H := H) :
      Set (VectorFunctionalPredual ℂ H H)) :=
  (dense_vectorFunctionalPredualSpan (𝕜 := ℂ) (E := H) (F := H)).mono
    vectorFunctionalPredualSpan_le_seriesSpan

/-! ## Continuous realizations of the source series -/

section CompleteHilbert

variable [CompleteSpace H]

/-- A square-summable coefficient series as an ultraweakly continuous linear functional on
`B(H)`. -/
def vectorFunctionalSeriesUltraweakL (xi eta : ℕ → H) :
    σ(H →L[ℂ] H, VectorFunctionalPredual ℂ H H) →L[ℂ] ℂ :=
  Ultraweak.predualDualEquiv ℂ (H →L[ℂ] H) (VectorFunctionalPredual ℂ H H)
    (vectorFunctionalSeriesInPredual xi eta)

@[simp]
theorem vectorFunctionalSeriesUltraweakL_apply (xi eta : ℕ → H)
    (hxi : Summable (fun n ↦ ‖xi n‖ ^ 2))
    (heta : Summable (fun n ↦ ‖eta n‖ ^ 2))
    (T : σ(H →L[ℂ] H, VectorFunctionalPredual ℂ H H)) :
    vectorFunctionalSeriesUltraweakL xi eta T =
      ∑' n, ⟪eta n, (ofUltraweak T) (xi n)⟫_ℂ := by
  unfold vectorFunctionalSeriesUltraweakL
  rw [Ultraweak.predualDualEquiv_apply_apply]
  exact vectorFunctionalPredualEvaluation_vectorFunctionalSeriesInPredual
    (ofUltraweak T) xi eta hxi heta

/-- A raw square-summable coefficient series as a continuous linear functional on the weak
topology generated by all such series. -/
def vectorFunctionalSeriesTestWeakL (xi eta : ℕ → H)
    (hxi : Summable (fun n ↦ ‖xi n‖ ^ 2))
    (heta : Summable (fun n ↦ ‖eta n‖ ^ 2)) :
    WeakBilin (Ultraweak.testPairing (M := H →L[ℂ] H)
      (vectorFunctionalSeriesSpan (H := H))) →L[ℂ] ℂ where
  toLinearMap := (WeakBilin.pairing (Ultraweak.testPairing (M := H →L[ℂ] H)
    (vectorFunctionalSeriesSpan (H := H)))).flip
      ⟨vectorFunctionalSeriesInPredual xi eta,
        Submodule.subset_span (vectorFunctionalSeriesInPredual_mem_seriesSet xi eta hxi heta)⟩
  cont := WeakBilin.eval_continuous _ _

@[simp]
theorem vectorFunctionalSeriesTestWeakL_apply (xi eta : ℕ → H)
    (hxi : Summable (fun n ↦ ‖xi n‖ ^ 2))
    (heta : Summable (fun n ↦ ‖eta n‖ ^ 2))
    (T : WeakBilin (Ultraweak.testPairing (M := H →L[ℂ] H)
      (vectorFunctionalSeriesSpan (H := H)))) :
    vectorFunctionalSeriesTestWeakL xi eta hxi heta T =
      ∑' n, ⟪eta n,
        (WeakBilin.linearEquiv ℂ (Ultraweak.testPairing (M := H →L[ℂ] H)
          (vectorFunctionalSeriesSpan (H := H))) T) (xi n)⟫_ℂ := by
  change Predual.equivDual (𝕜 := ℂ) (M := H →L[ℂ] H)
      (P := VectorFunctionalPredual ℂ H H)
      (WeakBilin.linearEquiv ℂ (Ultraweak.testPairing (M := H →L[ℂ] H)
        (vectorFunctionalSeriesSpan (H := H))) T)
      (vectorFunctionalSeriesInPredual xi eta) = _
  exact vectorFunctionalPredualEvaluation_vectorFunctionalSeriesInPredual _ xi eta hxi heta

/-- The source-specific continuous identity from the full concrete-predual topology to the weak
topology generated by square-summable coefficient series. -/
def vectorFunctionalSeriesWeakOfUltraweakL :
    σ(H →L[ℂ] H, VectorFunctionalPredual ℂ H H) →L[ℂ]
      WeakBilin (Ultraweak.testPairing (M := H →L[ℂ] H)
        (vectorFunctionalSeriesSpan (H := H))) :=
  Ultraweak.toTestWeakL (vectorFunctionalSeriesSpan (H := H))

lemma vectorFunctionalSeriesWeakOfUltraweakL_apply
    (T : σ(H →L[ℂ] H, VectorFunctionalPredual ℂ H H)) :
    WeakBilin.linearEquiv ℂ (Ultraweak.testPairing (M := H →L[ℂ] H)
      (vectorFunctionalSeriesSpan (H := H)))
      (vectorFunctionalSeriesWeakOfUltraweakL (H := H) T) = ofUltraweak T :=
  rfl

/-- Restricting an ultraweak coefficient-series functional along the source-specific identity does
not change its value. -/
theorem vectorFunctionalSeriesTestWeakL_comp_weakOfUltraweakL
    (xi eta : ℕ → H)
    (hxi : Summable (fun n ↦ ‖xi n‖ ^ 2))
    (heta : Summable (fun n ↦ ‖eta n‖ ^ 2)) :
    (vectorFunctionalSeriesTestWeakL xi eta hxi heta).comp
        (vectorFunctionalSeriesWeakOfUltraweakL (H := H)) =
      vectorFunctionalSeriesUltraweakL xi eta := by
  ext T
  change vectorFunctionalSeriesTestWeakL xi eta hxi heta
      (vectorFunctionalSeriesWeakOfUltraweakL (H := H) T) =
    vectorFunctionalSeriesUltraweakL xi eta T
  rw [vectorFunctionalSeriesTestWeakL_apply xi eta hxi heta,
    vectorFunctionalSeriesUltraweakL_apply xi eta hxi heta]
  rfl

/-- Pointwise form of
`ContinuousLinearMap.vectorFunctionalSeriesTestWeakL_comp_weakOfUltraweakL`. -/
theorem vectorFunctionalSeriesTestWeakL_weakOfUltraweakL_apply
    (xi eta : ℕ → H)
    (hxi : Summable (fun n ↦ ‖xi n‖ ^ 2))
    (heta : Summable (fun n ↦ ‖eta n‖ ^ 2))
    (T : σ(H →L[ℂ] H, VectorFunctionalPredual ℂ H H)) :
    vectorFunctionalSeriesTestWeakL xi eta hxi heta
        (vectorFunctionalSeriesWeakOfUltraweakL (H := H) T) =
      vectorFunctionalSeriesUltraweakL xi eta T := by
  change ((vectorFunctionalSeriesTestWeakL xi eta hxi heta).comp
    (vectorFunctionalSeriesWeakOfUltraweakL (H := H))) T = _
  rw [vectorFunctionalSeriesTestWeakL_comp_weakOfUltraweakL]

end CompleteHilbert

end Complex

end ContinuousLinearMap

namespace Ultraweak

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- Stage A of the source topology comparison: a subset of `B(H)` closed for the weak topology
generated by square-summable coefficient series is closed for the full concrete-predual
ultraweak topology.  No converse or topology equality is asserted. -/
theorem isClosed_ultraweak_of_isClosed_vectorFunctionalSeriesWeak
    (S : Set (H →L[ℂ] H))
    (hS : IsClosed
      ((WeakBilin.linearEquiv ℂ
        (testPairing (M := H →L[ℂ] H)
          (ContinuousLinearMap.vectorFunctionalSeriesSpan (H := H)))) ⁻¹' S)) :
    IsClosed (ofUltraweak ⁻¹' S :
      Set σ(H →L[ℂ] H, ContinuousLinearMap.VectorFunctionalPredual ℂ H H)) :=
  isClosed_ultraweak_of_isClosed_testWeak
    (ContinuousLinearMap.vectorFunctionalSeriesSpan (H := H)) S hS

end Ultraweak
