module

public import LeanOA.Ultraweak.BoundedOperatorRelativeKaplansky
public import LeanOA.Ultraweak.BoundedOperatorUltrastrong
public import LeanOA.Ultraweak.NonUnitalStarSubalgebra
public import LeanOA.Mathlib.Analysis.LocallyConvex.WeakOperatorTopology

/-!
# Closed self-adjoint operator algebras in the standard operator topologies

This file proves Sakai, Proposition 1.15.1: a possibly nonunital self-adjoint subalgebra of
`B(H)` is closed in the weak operator, coefficient-series sigma-weak operator, strong operator,
concrete ultrastrong, and concrete-predual ultraweak topologies simultaneously.

Only source-required one-way comparison maps are used. In particular, this result does not assume
or prove equality between the concrete coefficient-series and full-predual topologies, or between
the concrete ultrastrong and intrinsic strong topologies. Those identifications belong to later
results in Sakai.
-/

@[expose] public section

open Metric Set
open scoped InnerProductSpace Ultraweak

noncomputable section

namespace ContinuousLinearMapWOT

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

local notation "BH" => H →L[ℂ] H
local notation "FiniteCore" =>
  ContinuousLinearMap.vectorFunctionalPredualSpan (𝕜 := ℂ) (E := H) (F := H)
local notation "SeriesCore" => ContinuousLinearMap.vectorFunctionalSeriesSpan (H := H)

/-- Restriction from Sakai's coefficient-series weak topology to the finite vector-functional
weak topology. -/
def vectorFunctionalSeriesWeakToFiniteCoreL :
    WeakBilin (Ultraweak.testPairing (M := BH) SeriesCore) →L[ℂ]
      WeakBilin (Ultraweak.testPairing (M := BH) FiniteCore) :=
  Ultraweak.testWeakRestrictionL
    (ContinuousLinearMap.vectorFunctionalPredualSpan_le_seriesSpan (H := H))

lemma vectorFunctionalSeriesWeakToFiniteCoreL_apply
    (T : WeakBilin (Ultraweak.testPairing (M := BH) SeriesCore)) :
    WeakBilin.linearEquiv ℂ (Ultraweak.testPairing (M := BH) FiniteCore)
        (vectorFunctionalSeriesWeakToFiniteCoreL T) =
      WeakBilin.linearEquiv ℂ (Ultraweak.testPairing (M := BH) SeriesCore) T :=
  rfl

/-- The concrete coefficient-series sigma-weak operator topology is finer than Mathlib's weak
operator topology. -/
def vectorFunctionalSeriesWeakToWOTL :
    WeakBilin (Ultraweak.testPairing (M := BH) SeriesCore) →L[ℂ]
      (H →WOT[ℂ] H) :=
  vectorFunctionalPredualSpanWeakEquiv.toContinuousLinearMap.comp
    vectorFunctionalSeriesWeakToFiniteCoreL

@[simp]
lemma vectorFunctionalSeriesWeakToWOTL_apply
    (T : WeakBilin (Ultraweak.testPairing (M := BH) SeriesCore)) :
    vectorFunctionalSeriesWeakToWOTL T =
      ContinuousLinearMapWOT.ofCLM
        (WeakBilin.linearEquiv ℂ (Ultraweak.testPairing (M := BH) SeriesCore) T) :=
  rfl

/-- WOT-closed subsets of `B(H)` are closed for Sakai's coefficient-series sigma-weak operator
topology. -/
theorem isClosed_vectorFunctionalSeriesWeak_of_isClosed_wot
    (S : Set BH) (hS : IsClosed {T : H →WOT[ℂ] H | T.toCLM ∈ S}) :
    IsClosed
      ((WeakBilin.linearEquiv ℂ
        (Ultraweak.testPairing (M := BH) SeriesCore)) ⁻¹' S) := by
  change IsClosed (vectorFunctionalSeriesWeakToWOTL ⁻¹'
    {T : H →WOT[ℂ] H | T.toCLM ∈ S})
  exact hS.preimage vectorFunctionalSeriesWeakToWOTL.continuous

end ContinuousLinearMapWOT

namespace NonUnitalStarSubalgebra

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

local notation "BH" => H →L[ℂ] H
local notation "BHPredual" => ContinuousLinearMap.VectorFunctionalPredual ℂ H H
local notation "SeriesCore" => ContinuousLinearMap.vectorFunctionalSeriesSpan (H := H)

/-- Closedness of a bounded-operator star subalgebra in Mathlib's weak operator topology. -/
def IsWOTClosed (N : NonUnitalStarSubalgebra ℂ BH) : Prop :=
  IsClosed {T : H →WOT[ℂ] H | T.toCLM ∈ N}

/-- Closedness in Sakai's concrete sigma-weak operator topology generated by separately
square-summable coefficient series. -/
def IsSigmaWOTClosed (N : NonUnitalStarSubalgebra ℂ BH) : Prop :=
  IsClosed
    ((WeakBilin.linearEquiv ℂ
      (Ultraweak.testPairing (M := BH) SeriesCore)) ⁻¹' (N : Set BH))

/-- Closedness of a bounded-operator star subalgebra in the strong operator topology. -/
def IsSOTClosed (N : NonUnitalStarSubalgebra ℂ BH) : Prop :=
  IsClosed {T : H →Lₚₜ[ℂ] H | (T : BH) ∈ N}

/-- Closedness in Sakai's strongest operator topology, now usually called the ultrastrong
operator topology. -/
def IsUSOTClosed (N : NonUnitalStarSubalgebra ℂ BH) : Prop :=
  IsClosed {T : H →USOT[ℂ] H | SquareSummableConvergenceCLM.toCLM T ∈ N}

/-- WOT-closed subsets of `B(H)` are closed for Sakai's coefficient-series sigma-weak operator
topology. -/
theorem IsWOTClosed.isSigmaWOTClosed
    {N : NonUnitalStarSubalgebra ℂ BH} (hN : N.IsWOTClosed) :
    N.IsSigmaWOTClosed :=
  ContinuousLinearMapWOT.isClosed_vectorFunctionalSeriesWeak_of_isClosed_wot
    (N : Set BH) hN

/-- WOT closedness implies strong-operator closedness for any operator set. -/
theorem IsWOTClosed.isSOTClosed
    {N : NonUnitalStarSubalgebra ℂ BH} (hN : N.IsWOTClosed) :
    N.IsSOTClosed :=
  PointwiseConvergenceCLM.isClosed_pointwise_of_isClosed_wot (N : Set BH) hN

/-- Strong-operator closedness implies concrete ultrastrong closedness. -/
theorem IsSOTClosed.isUSOTClosed
    {N : NonUnitalStarSubalgebra ℂ BH} (hN : N.IsSOTClosed) :
    N.IsUSOTClosed :=
  SquareSummableConvergenceCLM.isClosed_squareSummable_of_isClosed_pointwise
    (N : Set BH) hN

/-- Concrete ultrastrong closedness implies closedness for the intrinsic strong topology. -/
theorem IsUSOTClosed.isClosed_strong
    {N : NonUnitalStarSubalgebra ℂ BH} (hN : N.IsUSOTClosed) :
    IsClosed (Ultraweak.ofStrong ⁻¹' (N : Set BH) :
      Set (Ultraweak.Strong BH BHPredual)) :=
  BoundedOperatorUltrastrong.isClosed_strong_of_isClosed_squareSummable (N : Set BH) hN

/-- Concrete ultrastrong closedness implies closedness in the concrete-predual ultraweak
topology. -/
theorem IsUSOTClosed.isUltraweakClosed
    {N : NonUnitalStarSubalgebra ℂ BH} (hN : N.IsUSOTClosed) :
    N.IsUltraweakClosed (P := BHPredual) := by
  have hconvex : Convex ℝ (N : Set BH) :=
    (N.toNonUnitalSubalgebra.toSubmodule.restrictScalars ℝ).convex
  have hu : IsClosed (ofUltraweak ⁻¹' (N : Set BH) : Set σ(BH, BHPredual)) :=
    (Ultraweak.Strong.isClosed_ofStrong_preimage_iff_ofUltraweak_preimage
      (N : Set BH) hconvex).mp hN.isClosed_strong
  exact ⟨by
    convert hu using 1
    ext T
    simp⟩

/-- Closedness for Sakai's coefficient-series sigma-weak operator topology implies closedness for
the full concrete-predual ultraweak topology. -/
theorem IsSigmaWOTClosed.isUltraweakClosed
    {N : NonUnitalStarSubalgebra ℂ BH} (hN : N.IsSigmaWOTClosed) :
    N.IsUltraweakClosed (P := BHPredual) := by
  have hu := Ultraweak.isClosed_ultraweak_of_isClosed_vectorFunctionalSeriesWeak
    (N : Set BH) hN
  exact ⟨by
    convert hu using 1
    ext T
    simp⟩

/-- The unit-ball consequence of relative Kaplansky density used in the reverse implication of
Sakai's closedness theorem. -/
theorem mem_of_mem_wotClosure_of_norm_le_one
    (N : NonUnitalStarSubalgebra ℂ BH)
    (hN : N.IsUltraweakClosed (P := BHPredual))
    {x : BH} (hx : x ∈ N.wotClosure) (hxnorm : ‖x‖ ≤ 1) :
    x ∈ N := by
  have hNclosed : IsClosed
      (ofUltraweak ⁻¹' (N : Set BH) : Set σ(BH, BHPredual)) := by
    convert hN.isClosed using 1
    ext T
    simp
  have hBallClosed : IsClosed
      (ofUltraweak ⁻¹' ((N : Set BH) ∩ Metric.closedBall 0 1) :
        Set σ(BH, BHPredual)) := by
    rw [preimage_inter]
    exact hNclosed.inter (Ultraweak.isClosed_closedBall ℂ BHPredual 0 1)
  have hxClosure : toUltraweak ℂ BHPredual x ∈
      closure (ofUltraweak ⁻¹' ((N : Set BH) ∩ Metric.closedBall 0 1) :
        Set σ(BH, BHPredual)) := by
    rw [Ultraweak.ultraweak_closure_unitBall_eq_wotClosure_unitBall N]
    exact ⟨hx, by simpa [Metric.mem_closedBall, dist_zero_right]⟩
  exact (closure_minimal subset_rfl hBallClosed hxClosure).1

/-- An ultraweakly closed bounded-operator star subalgebra equals its Mathlib-WOT closure. -/
theorem IsUltraweakClosed.wotClosure_eq
    {N : NonUnitalStarSubalgebra ℂ BH}
    (hN : N.IsUltraweakClosed (P := BHPredual)) :
    N.wotClosure = N := by
  apply le_antisymm ?_ N.le_wotClosure
  intro x hx
  by_cases hx0 : x = 0
  · subst x
    exact N.zero_mem
  · have hxscaledWOT : ‖x‖⁻¹ • x ∈ N.wotClosure :=
      (N.wotClosure.toSubmodule.restrictScalars ℝ).smul_mem ‖x‖⁻¹ hx
    have hxscaledN : ‖x‖⁻¹ • x ∈ N :=
      mem_of_mem_wotClosure_of_norm_le_one N hN hxscaledWOT
        (by
          simpa [Metric.mem_closedBall, dist_zero_right] using
            (inv_norm_smul_mem_unitClosedBall x))
    have hxrescaled : ‖x‖ • (‖x‖⁻¹ • x) ∈ N :=
      (N.toSubmodule.restrictScalars ℝ).smul_mem ‖x‖ hxscaledN
    simpa [smul_smul, norm_ne_zero_iff.mpr hx0] using hxrescaled

/-- Ultraweak closedness of a bounded-operator star subalgebra implies weak-operator
closedness. -/
theorem IsUltraweakClosed.isWOTClosed
    {N : NonUnitalStarSubalgebra ℂ BH}
    (hN : N.IsUltraweakClosed (P := BHPredual)) :
    N.IsWOTClosed := by
  rw [← hN.wotClosure_eq]
  exact N.isClosed_wotClosure

/-- Sakai, Proposition 1.15.1: the five global closedness conditions for a possibly nonunital
self-adjoint subalgebra of `B(H)` are equivalent. -/
theorem operatorTopologyClosedness_tfae (N : NonUnitalStarSubalgebra ℂ BH) :
    List.TFAE
      [N.IsWOTClosed, N.IsSigmaWOTClosed, N.IsSOTClosed, N.IsUSOTClosed,
        N.IsUltraweakClosed (P := BHPredual)] := by
  tfae_have 1 → 2 := IsWOTClosed.isSigmaWOTClosed
  tfae_have 1 → 3 := IsWOTClosed.isSOTClosed
  tfae_have 2 → 5 := IsSigmaWOTClosed.isUltraweakClosed
  tfae_have 3 → 4 := IsSOTClosed.isUSOTClosed
  tfae_have 4 → 5 := IsUSOTClosed.isUltraweakClosed
  tfae_have 5 → 1 := IsUltraweakClosed.isWOTClosed
  tfae_finish

/-- A bounded-operator star subalgebra is WOT closed exactly when it is closed for Sakai's
coefficient-series sigma-weak operator topology. -/
theorem isWOTClosed_iff_isSigmaWOTClosed (N : NonUnitalStarSubalgebra ℂ BH) :
    N.IsWOTClosed ↔ N.IsSigmaWOTClosed :=
  ⟨IsWOTClosed.isSigmaWOTClosed, fun hN ↦ hN.isUltraweakClosed.isWOTClosed⟩

/-- A bounded-operator star subalgebra is WOT closed exactly when it is SOT closed. -/
theorem isWOTClosed_iff_isSOTClosed (N : NonUnitalStarSubalgebra ℂ BH) :
    N.IsWOTClosed ↔ N.IsSOTClosed :=
  ⟨IsWOTClosed.isSOTClosed, fun hN ↦ hN.isUSOTClosed.isUltraweakClosed.isWOTClosed⟩

/-- A bounded-operator star subalgebra is WOT closed exactly when it is concrete-ultrastrong
closed. -/
theorem isWOTClosed_iff_isUSOTClosed (N : NonUnitalStarSubalgebra ℂ BH) :
    N.IsWOTClosed ↔ N.IsUSOTClosed :=
  ⟨fun hN ↦ hN.isSOTClosed.isUSOTClosed, fun hN ↦ hN.isUltraweakClosed.isWOTClosed⟩

/-- A bounded-operator star subalgebra is WOT closed exactly when it is closed for the concrete
predual's ultraweak topology. -/
theorem isWOTClosed_iff_isUltraweakClosed (N : NonUnitalStarSubalgebra ℂ BH) :
    N.IsWOTClosed ↔ N.IsUltraweakClosed (P := BHPredual) :=
  ⟨fun hN ↦ hN.isSOTClosed.isUSOTClosed.isUltraweakClosed,
    IsUltraweakClosed.isWOTClosed⟩

end NonUnitalStarSubalgebra
