module

public import LeanOA.CStarAlgebra.PositiveLinearFunctional
public import LeanOA.Ultraweak.Corner
public import LeanOA.Ultraweak.Ideal
public import LeanOA.Ultraweak.NormalCharacterization

@[expose] public section

/-!
# Support projections of normal positive functionals

This file constructs the support of a normal positive functional on a $W^*$-algebra from its
GNS null left ideal. The public definition is intrinsic: the selected predual of the
$W^*$-algebra is used only inside the proof that the null ideal is ultraweakly closed.
-/

open Set
open scoped ComplexOrder Ultraweak

namespace PositiveLinearMap

section SpecifiedPredual

variable {M P : Type*} [CStarAlgebra M] [PartialOrder M] [StarOrderedRing M]
  [NormedAddCommGroup P] [NormedSpace ℂ P] [CompleteSpace P] [Predual ℂ M P]

/-- The GNS null left ideal of a normal positive functional is closed in Sakai's strong
topology. It is the zero set of one of the seminorms defining that topology. -/
theorem IsNormalOnProjections.isClosed_nullIdeal_strong
    {φ : M →ₚ[ℂ] ℂ} (hφ : φ.IsNormalOnProjections) :
    IsClosed (Ultraweak.ofStrong ⁻¹' (φ.nullIdeal : Set M) : Set s(M, P)) := by
  have hφmem : φ.toContinuousLinearMap ∈ Ultraweak.continuousDual ℂ M P :=
    (φ.isNormalOnProjections_iff_mem_continuousDual (P := P)).1 hφ
  have hφcont : Continuous (fun x : σ(M, P) ↦ φ (ofUltraweak x)) :=
    (Ultraweak.mem_continuousDual_iff_continuous_ultraweak
      (P := P) φ.toContinuousLinearMap).1 hφmem
  let φu : σ(M, P) →P[ℂ] ℂ := {
    toFun x := φ (ofUltraweak x)
    map_add' x y := by simp
    map_smul' c x := by
      change φ (c • ofUltraweak x) = c * φ (ofUltraweak x)
      rw [map_smul]
      rfl
    monotone' x y hxy := φ.monotone (Ultraweak.monotone_ofUltraweak hxy)
    cont := hφcont
  }
  rw [show (Ultraweak.ofStrong ⁻¹' (φ.nullIdeal : Set M) : Set s(M, P)) =
      Ultraweak.Strong.seminorm φu ⁻¹' {0} by
    ext x
    change φ (star (Ultraweak.ofStrong x) * Ultraweak.ofStrong x) = 0 ↔
      Ultraweak.Strong.seminorm φu x = 0
    rw [Ultraweak.Strong.seminorm_apply, Real.sqrt_eq_zero (norm_nonneg _), norm_eq_zero]
    rw [show φu (toUltraweak ℂ P
        (star (Ultraweak.ofStrong x) * Ultraweak.ofStrong x)) =
      φ (ofUltraweak (toUltraweak ℂ P
        (star (Ultraweak.ofStrong x) * Ultraweak.ofStrong x))) by rfl]
    rw [ofUltraweak_toUltraweak]]
  exact isClosed_singleton.preimage
    (Ultraweak.Strong.withSeminorms.continuous_seminorm φu)

/-- The GNS null left ideal of a normal positive functional is closed in the specified ultraweak
topology. Following Sakai, this is deduced from strong closedness using the coincidence of strong
and ultraweak closures on convex sets. -/
theorem IsNormalOnProjections.isClosed_nullIdeal_ultraweak
    {φ : M →ₚ[ℂ] ℂ} (hφ : φ.IsNormalOnProjections) :
    IsClosed (Ultraweak.ofSubmodule (P := P)
      (φ.nullIdeal.restrictScalars ℂ) : Set σ(M, P)) := by
  let S : Set s(M, P) := Ultraweak.ofStrong ⁻¹' (φ.nullIdeal : Set M)
  have hSclosed : IsClosed S := hφ.isClosed_nullIdeal_strong (P := P)
  have hSconvex : Convex ℝ S := by
    letI : Module ℝ s(M, P) := RestrictScalars.module ℝ ℂ s(M, P)
    letI : IsScalarTower ℝ ℂ s(M, P) := RestrictScalars.isScalarTower ℝ ℂ s(M, P)
    let N : Submodule ℂ s(M, P) :=
      (φ.nullIdeal.restrictScalars ℂ).comap
        (Ultraweak.Strong.linearEquiv M P).toLinearMap
    change Convex ℝ (N : Set s(M, P))
    exact (N.restrictScalars ℝ).convex
  have himage : Ultraweak.Strong.toUltraweakEquiv '' S =
      (Ultraweak.ofSubmodule (P := P)
        (φ.nullIdeal.restrictScalars ℂ) : Set σ(M, P)) := by
    rw [LinearEquiv.image_eq_preimage_symm]
    ext x
    change Ultraweak.ofStrong
      ((Ultraweak.Strong.toUltraweakEquiv (M := M) (P := P)).symm x) ∈ φ.nullIdeal ↔
        ofUltraweak x ∈ φ.nullIdeal
    rw [Ultraweak.Strong.ofStrong_toUltraweakEquiv_symm]
  rw [← himage, ← closure_eq_iff_isClosed,
    ← Ultraweak.Strong.image_closure_toUltraweakEquiv hSconvex,
    hSclosed.closure_eq]

end SpecifiedPredual

section WStarAlgebra

variable {M : Type*} [CStarAlgebra M] [PartialOrder M] [StarOrderedRing M] [WStarAlgebra M]

/-- The support projection of a normal positive functional, in Sakai's convention: the
complement of the projection generating its GNS null left ideal. -/
noncomputable def support (φ : M →ₚ[ℂ] ℂ) (hφ : φ.IsNormalOnProjections) :
    {p : M // IsStarProjection p} := by
  let P := WStarAlgebra.predual M
  let h := Ideal.existsUnique_isStarProjection_eq_span_of_isClosed_ultraweak
    φ.nullIdeal (hφ.isClosed_nullIdeal_ultraweak (P := P))
  exact ⟨1 - h.choose, h.choose_spec.1.1.one_sub⟩

/-- The null left ideal of a normal positive functional is generated by the complement of its
support projection. -/
theorem nullIdeal_eq_span_one_sub_support (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) :
    φ.nullIdeal = Ideal.span {1 - (φ.support hφ).1} := by
  let P := WStarAlgebra.predual M
  let h := Ideal.existsUnique_isStarProjection_eq_span_of_isClosed_ultraweak
    φ.nullIdeal (hφ.isClosed_nullIdeal_ultraweak (P := P))
  change φ.nullIdeal = Ideal.span {1 - (1 - h.choose)}
  simpa only [sub_sub_cancel] using h.choose_spec.1.2

/-- An element belongs to the GNS null left ideal exactly when it is annihilated on the right by
the support projection. -/
theorem mem_nullIdeal_iff_mul_support_eq_zero (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (x : M) :
    x ∈ φ.nullIdeal ↔ x * (φ.support hφ).1 = 0 := by
  rw [φ.nullIdeal_eq_span_one_sub_support hφ]
  exact Ideal.mem_span_singleton_one_sub_iff_mul_eq_zero (φ.support hφ).2.isIdempotentElem

/-- The defining quadratic form of a normal positive functional vanishes exactly on the right
annihilator of its support. -/
theorem apply_star_mul_self_eq_zero_iff_mul_support_eq_zero (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (x : M) :
    φ (star x * x) = 0 ↔ x * (φ.support hφ).1 = 0 := by
  rw [← φ.mem_nullIdeal, φ.mem_nullIdeal_iff_mul_support_eq_zero hφ]

/-- A projection has zero value under a normal positive functional exactly when it lies below
the complement of the functional's support. -/
theorem apply_eq_zero_iff_le_one_sub_support (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (q : {q : M // IsStarProjection q}) :
    φ q.1 = 0 ↔ q.1 ≤ 1 - (φ.support hφ).1 := by
  calc
    φ q.1 = 0 ↔ φ (star q.1 * q.1) = 0 := by
      rw [q.2.isSelfAdjoint.star_eq, q.2.isIdempotentElem.eq]
    _ ↔ q.1 * (φ.support hφ).1 = 0 :=
      φ.apply_star_mul_self_eq_zero_iff_mul_support_eq_zero hφ q.1
    _ ↔ q.1 ≤ 1 - (φ.support hφ).1 :=
      q.2.mul_eq_zero_iff_le_one_sub (φ.support hφ).2

/-- The complement of the support is the greatest projection on which a normal positive
functional vanishes. This is Sakai's principal order characterization of functional support. -/
theorem isGreatest_setOf_apply_eq_zero (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) :
    IsGreatest {q : {q : M // IsStarProjection q} | φ q.1 = 0}
      ⟨1 - (φ.support hφ).1, (φ.support hφ).2.one_sub⟩ := by
  constructor
  · exact (φ.apply_eq_zero_iff_le_one_sub_support hφ
      ⟨1 - (φ.support hφ).1, (φ.support hφ).2.one_sub⟩).2 le_rfl
  · intro q hq
    exact (φ.apply_eq_zero_iff_le_one_sub_support hφ q).1 hq

/-- The support of a normal positive functional lies below a projection exactly when the
functional takes the same value on that projection as on the identity. -/
theorem support_le_iff_apply_eq_apply_one (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (p : {p : M // IsStarProjection p}) :
    φ.support hφ ≤ p ↔ φ p.1 = φ 1 := by
  change (φ.support hφ).1 ≤ p.1 ↔ φ p.1 = φ 1
  calc
    (φ.support hφ).1 ≤ p.1 ↔
        (1 - p.1 : M) ≤ 1 - (φ.support hφ).1 := by
      rw [sub_le_sub_iff_left]
    _ ↔ φ (1 - p.1) = 0 :=
      (φ.apply_eq_zero_iff_le_one_sub_support hφ ⟨1 - p.1, p.2.one_sub⟩).symm
    _ ↔ φ p.1 = φ 1 := by rw [map_sub, sub_eq_zero, eq_comm]

/-- Normal positive functionals with orthogonal support projections are orthogonal in Sakai's
norm-theoretic sense. -/
theorem isOrthogonal_of_support_mul_eq_zero (φ ψ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (hψ : ψ.IsNormalOnProjections)
    (horth : (φ.support hφ).1 * (ψ.support hψ).1 = 0) :
    φ.IsOrthogonal ψ := by
  let p := (φ.support hφ).1
  let q := (ψ.support hψ).1
  have hp : IsStarProjection p := (φ.support hφ).2
  have hq : IsStarProjection q := (ψ.support hψ).2
  change p * q = 0 at horth
  have hqp : q * p = 0 := by
    simpa only [p, q, star_mul, hp.isSelfAdjoint.star_eq, hq.isSelfAdjoint.star_eq,
      star_zero] using congrArg star horth
  have hφq : φ q = 0 := by
    rw [φ.apply_eq_zero_iff_le_one_sub_support hφ]
    exact (hq.mul_eq_zero_iff_le_one_sub hp).mp hqp
  have hψp : ψ p = 0 := by
    rw [ψ.apply_eq_zero_iff_le_one_sub_support hψ]
    exact (hp.mul_eq_zero_iff_le_one_sub hq).mp horth
  have hφp : φ p = (‖φ.toContinuousLinearMap‖ : ℂ) := by
    calc
      φ p = φ 1 := by
        simpa only [p] using
          (φ.support_le_iff_apply_eq_apply_one hφ (φ.support hφ)).mp le_rfl
      _ = (‖φ.toContinuousLinearMap‖ : ℂ) :=
        (PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one
          φ.toPositiveContinuousLinearMap).symm
  have hψq : ψ q = (‖ψ.toContinuousLinearMap‖ : ℂ) := by
    calc
      ψ q = ψ 1 := by
        simpa only [q] using
          (ψ.support_le_iff_apply_eq_apply_one hψ (ψ.support hψ)).mp le_rfl
      _ = (‖ψ.toContinuousLinearMap‖ : ℂ) :=
        (PositiveContinuousLinearMap.ofReal_opNorm_eq_map_one
          ψ.toPositiveContinuousLinearMap).symm
  have hpq_norm : ‖p - q‖ ≤ 1 := by
    rw [sub_eq_add_neg,
      CStarRing.norm_add_eq_max_of_mul_star_eq_zero_of_star_mul_eq_zero]
    · exact max_le (IsStarProjection.norm_le p hp)
        (by simpa using IsStarProjection.norm_le q hq)
    · simp only [star_neg, hq.isSelfAdjoint.star_eq, mul_neg, horth, neg_zero]
    · simp only [hp.isSelfAdjoint.star_eq, mul_neg, horth, neg_zero]
  let f := φ.toContinuousLinearMap - ψ.toContinuousLinearMap
  have hf_apply : f (p - q) =
      ((‖φ.toContinuousLinearMap‖ + ‖ψ.toContinuousLinearMap‖ : ℝ) : ℂ) := by
    change φ (p - q) - ψ (p - q) = _
    rw [map_sub, map_sub, hφp, hφq, hψp, hψq]
    simp
  have hf_apply_norm : ‖f (p - q)‖ =
      ‖φ.toContinuousLinearMap‖ + ‖ψ.toContinuousLinearMap‖ := by
    rw [hf_apply, Complex.norm_real, Real.norm_eq_abs,
      abs_of_nonneg (add_nonneg (norm_nonneg _) (norm_nonneg _))]
  rw [IsOrthogonal]
  apply le_antisymm (norm_sub_le _ _) ?_
  rw [← hf_apply_norm]
  calc
    ‖f (p - q)‖ ≤ ‖f‖ * ‖p - q‖ := f.le_opNorm (p - q)
    _ ≤ ‖f‖ * 1 := mul_le_mul_of_nonneg_left hpq_norm (norm_nonneg f)
    _ = ‖φ.toContinuousLinearMap - ψ.toContinuousLinearMap‖ := by simp [f]

/-- Right multiplication by the complement of the support is invisible to the functional. -/
theorem apply_mul_one_sub_support (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (x : M) :
    φ (x * (1 - (φ.support hφ).1)) = 0 := by
  have hn : 1 - (φ.support hφ).1 ∈ φ.nullIdeal :=
    (φ.mem_nullIdeal_iff_mul_support_eq_zero hφ _).2
      (φ.support hφ).2.one_sub_mul_self
  simpa only [star_star] using
    (φ.mem_nullIdeal_iff_forall_apply_star_mul_eq_zero
      (1 - (φ.support hφ).1)).1 hn (star x)

/-- Left multiplication by the complement of the support is invisible to the functional. -/
theorem apply_one_sub_support_mul (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (x : M) :
    φ ((1 - (φ.support hφ).1) * x) = 0 := by
  have hn : φ (star (1 - (φ.support hφ).1) *
      (1 - (φ.support hφ).1)) = 0 :=
    (φ.apply_star_mul_self_eq_zero_iff_mul_support_eq_zero hφ _).2
      (φ.support hφ).2.one_sub_mul_self
  simpa only [(φ.support hφ).2.one_sub.isSelfAdjoint.star_eq] using
    φ.apply_star_mul_eq_zero_of_apply_star_mul_self_eq_zero_left hn x

/-- Cutting down on the right by the support does not change a normal positive functional. -/
@[simp]
theorem apply_mul_support (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (x : M) :
    φ (x * (φ.support hφ).1) = φ x := by
  have h := φ.apply_mul_one_sub_support hφ x
  rw [mul_sub, mul_one, map_sub] at h
  exact (sub_eq_zero.mp h).symm

/-- Cutting down on the left by the support does not change a normal positive functional. -/
@[simp]
theorem apply_support_mul (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (x : M) :
    φ ((φ.support hφ).1 * x) = φ x := by
  have h := φ.apply_one_sub_support_mul hφ x
  rw [sub_mul, one_mul, map_sub] at h
  exact (sub_eq_zero.mp h).symm

/-- Cutting down on both sides by the support does not change a normal positive functional. -/
theorem apply_support_mul_support (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (x : M) :
    φ ((φ.support hφ).1 * x * (φ.support hφ).1) = φ x := by
  rw [φ.apply_mul_support hφ, φ.apply_support_mul hφ]

/-- Cutting down by any projection above the support does not change a normal positive
functional. -/
theorem apply_cutdown_of_support_le (φ : M →ₚ[ℂ] ℂ)
    (hφ : φ.IsNormalOnProjections) (p : {p : M // IsStarProjection p})
    (hsp : φ.support hφ ≤ p) (x : M) :
    φ (p.1 * x * p.1) = φ x := by
  have hsp_right : (φ.support hφ).1 * p.1 = (φ.support hφ).1 :=
    ((φ.support hφ).2.le_iff_mul_eq_left p.2).mp hsp
  have hsp_left : p.1 * (φ.support hφ).1 = (φ.support hφ).1 :=
    ((φ.support hφ).2.le_iff_mul_eq_right p.2).mp hsp
  calc
    φ (p.1 * x * p.1) =
        φ ((φ.support hφ).1 * (p.1 * x * p.1) * (φ.support hφ).1) :=
      (φ.apply_support_mul_support hφ (p.1 * x * p.1)).symm
    _ = φ (((φ.support hφ).1 * p.1) * x *
        (p.1 * (φ.support hφ).1)) := by
      congr 1
      noncomm_ring
    _ = φ ((φ.support hφ).1 * x * (φ.support hφ).1) := by
      rw [hsp_right, hsp_left]
    _ = φ x := φ.apply_support_mul_support hφ x

/-- Sakai's full-support definition of faithfulness is equivalent to the direct statement that
the functional's GNS null space is trivial. -/
theorem support_eq_one_iff_apply_star_mul_self_eq_zero_imp
    (φ : M →ₚ[ℂ] ℂ) (hφ : φ.IsNormalOnProjections) :
    (φ.support hφ).1 = 1 ↔ ∀ x : M, φ (star x * x) = 0 → x = 0 := by
  constructor
  · intro hs x hx
    have hxp := (φ.apply_star_mul_self_eq_zero_iff_mul_support_eq_zero hφ x).mp hx
    simpa only [hs, mul_one] using hxp
  · intro hfaith
    have hzero :
        φ (star (1 - (φ.support hφ).1) * (1 - (φ.support hφ).1)) = 0 :=
      (φ.apply_star_mul_self_eq_zero_iff_mul_support_eq_zero hφ
        (1 - (φ.support hφ).1)).mpr (φ.support hφ).2.one_sub_mul_self
    have hcomp : 1 - (φ.support hφ).1 = 0 := hfaith _ hzero
    exact (sub_eq_zero.mp hcomp).symm

/-- The restriction of a normal positive functional to its support corner has trivial
star-square kernel. This is the derived support-corner faithfulness property used later in
Sakai's polar-decomposition arguments. -/
theorem apply_star_mul_self_eq_zero_iff_on_support_corner
    (φ : M →ₚ[ℂ] ℂ) (hφ : φ.IsNormalOnProjections)
    (x : (φ.support hφ).2.Corner) :
    φ (star (x : M) * (x : M)) = 0 ↔ x = 0 := by
  constructor
  · intro hx
    have hxs :=
      (φ.apply_star_mul_self_eq_zero_iff_mul_support_eq_zero hφ (x : M)).mp hx
    apply IsStarProjection.Corner.ext (φ.support hφ).2
    simpa only [IsStarProjection.Corner.mul_projection,
      IsStarProjection.Corner.coe_zero] using hxs
  · rintro rfl
    simp

/-- A nonnegative element of the support corner has zero functional value exactly when it is
zero. -/
theorem apply_eq_zero_iff_of_nonneg_on_support_corner
    (φ : M →ₚ[ℂ] ℂ) (hφ : φ.IsNormalOnProjections)
    (x : (φ.support hφ).2.Corner) (hx : 0 ≤ x) :
    φ (x : M) = 0 ↔ x = 0 := by
  constructor
  · intro hφx
    let y : (φ.support hφ).2.Corner := CFC.sqrt x
    have hy_square : star y * y = x := by
      rw [(CFC.sqrt_nonneg x).star_eq, CFC.sqrt_mul_sqrt_self x hx]
    have hy_zero : φ (star (y : M) * (y : M)) = 0 := by
      simpa only [← IsStarProjection.Corner.coe_star,
        ← IsStarProjection.Corner.coe_mul, hy_square] using hφx
    have hy : y = 0 :=
      (φ.apply_star_mul_self_eq_zero_iff_on_support_corner hφ y).mp hy_zero
    rw [← hy_square, hy]
    simp
  · rintro rfl
    simp

end WStarAlgebra

end PositiveLinearMap
