module

public import LeanOA.Mathlib.Analysis.CStarAlgebra.Projection
public import LeanOA.Mathlib.Analysis.CStarAlgebra.Basic
public import LeanOA.Ultraweak.ContinuousStar
public import LeanOA.Ultraweak.IsUnital

@[expose] public section

/-!
# Ultraweakly closed left ideals

This file proves that an ultraweakly closed left ideal of a dual C-star algebra is generated by a
unique star projection.
-/

open Set
open scoped Ultraweak

namespace Ideal

variable {M P : Type*} [CStarAlgebra M]

/-- The largest star-stable nonunital star subalgebra contained in a left ideal. -/
private def starCore (I : Ideal M) : NonUnitalStarSubalgebra ℂ M where
  carrier := {x | x ∈ I ∧ star x ∈ I}
  zero_mem' := by simp
  add_mem' hx hy := ⟨I.add_mem hx.1 hy.1, by simpa only [star_add] using I.add_mem hx.2 hy.2⟩
  mul_mem' hx hy := ⟨I.mul_mem_left _ hy.1, by
    simpa only [star_mul] using I.mul_mem_left (star _) hx.2⟩
  smul_mem' c x hx := ⟨by
    change c • x ∈ I
    exact (I.restrictScalars ℂ).smul_mem c hx.1, by
    rw [star_smul]
    change star c • star x ∈ I
    exact (I.restrictScalars ℂ).smul_mem (star c) hx.2⟩
  star_mem' hx := ⟨hx.2, by simpa only [star_star] using hx.1⟩

/-- The ambient submodule underlying the star-stable core of a left ideal. -/
private noncomputable def starCoreSubmodule (I : Ideal M) : Submodule ℂ M :=
  (starCore I).toNonUnitalSubalgebra.toSubmodule

/-- The explicit linear isometry from the star-stable core to its ambient submodule. -/
private def starCoreEquiv (I : Ideal M) : starCore I ≃ₗᵢ[ℂ] starCoreSubmodule I where
  toFun x := ⟨x, x.property⟩
  invFun x := ⟨x, x.property⟩
  left_inv _ := rfl
  right_inv _ := rfl
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  norm_map' _ := rfl

variable [NormedAddCommGroup P] [NormedSpace ℂ P] [CompleteSpace P] [Predual ℂ M P]

/-- The star-stable core of an ultraweakly closed left ideal is ultraweakly closed. -/
private lemma isClosed_starCoreSubmodule (I : Ideal M)
    (hI : IsClosed
      (Ultraweak.ofSubmodule (P := P) (I.restrictScalars ℂ) : Set σ(M, P))) :
    IsClosed (Ultraweak.ofSubmodule (P := P) (starCoreSubmodule I) : Set σ(M, P)) := by
  rw [show (Ultraweak.ofSubmodule (P := P) (starCoreSubmodule I) : Set σ(M, P)) =
      (Ultraweak.ofSubmodule (P := P) (I.restrictScalars ℂ) : Set σ(M, P)) ∩
        star ⁻¹' Ultraweak.ofSubmodule (P := P) (I.restrictScalars ℂ) by
    ext x
    simp [starCoreSubmodule, starCore, Ultraweak.mem_ofSubmodule]]
  exact hI.inter (hI.preimage continuous_star)

omit [CompleteSpace P] in
/-- Ultraweak closedness of the star-stable core implies the norm closedness needed for its
inherited nonunital C-star algebra structure. -/
private lemma isClosed_starCore (I : Ideal M)
    (hI : IsClosed
      (Ultraweak.ofSubmodule (P := P) (starCoreSubmodule I) : Set σ(M, P))) :
    IsClosed (starCore I : Set M) := by
  have hpre := hI.preimage (continuous_toUltraweak (𝕜 := ℂ) (M := M) (P := P))
  rw [show toUltraweak ℂ P ⁻¹'
      (Ultraweak.ofSubmodule (P := P) (starCoreSubmodule I) : Set σ(M, P)) =
      (starCore I : Set M) by
    ext x
    change ofUltraweak (toUltraweak ℂ P x) ∈ starCoreSubmodule I ↔ x ∈ starCore I
    rw [ofUltraweak_toUltraweak]
    rfl] at hpre
  exact hpre

/-- The ambient value of the unit of a star-stable subalgebra is a star projection. -/
private lemma isStarProjection_coe_unit (N : NonUnitalStarSubalgebra ℂ M) [IsUnital N] :
    IsStarProjection ((IsUnital.isUnital.choose : N) : M) := by
  let e : N := IsUnital.isUnital.choose
  have he (x : N) := IsUnital.isUnital.choose_spec x
  refine ⟨congr_arg Subtype.val (he e).1, ?_⟩
  have hstar : star e = e := (he (star e)).2.symm.trans <| by
    simpa only [star_mul, star_star] using congr_arg star (he (star e)).2
  exact congr_arg Subtype.val hstar

/-- The unit of the star-stable core acts on the right as the identity on the whole left ideal. -/
private lemma mul_coe_unit_eq_of_mem (I : Ideal M) [IsUnital (starCore I)]
    {x : M} (hx : x ∈ I) : x * ((IsUnital.isUnital.choose : starCore I) : M) = x := by
  let p : M := (IsUnital.isUnital.choose : starCore I)
  have hp := isStarProjection_coe_unit (starCore I)
  let y : starCore I := ⟨star x * x, I.mul_mem_left _ hx, by
    simpa only [star_mul, star_star] using I.mul_mem_left (star x) hx⟩
  have hy := congr_arg Subtype.val (IsUnital.isUnital.choose_spec y).2
  change (star x * x) * p = star x * x at hy
  exact hp.isSelfAdjoint.mul_eq_self_of_star_mul_self_mul_eq hy

/-- An ultraweakly closed left ideal of a dual C-star algebra is generated by a unique star
projection. -/
theorem existsUnique_isStarProjection_eq_span_of_isClosed_ultraweak (I : Ideal M)
    (hI : IsClosed
      (Ultraweak.ofSubmodule (P := P) (I.restrictScalars ℂ) : Set σ(M, P))) :
    ∃! p : M, IsStarProjection p ∧ I = Ideal.span {p} := by
  let N := starCoreSubmodule I
  have hN : IsClosed (Ultraweak.ofSubmodule (P := P) N : Set σ(M, P)) :=
    isClosed_starCoreSubmodule I hI
  letI : IsClosed (starCore I : Set M) := isClosed_starCore I hN
  letI : NonUnitalCStarAlgebra (starCore I) :=
    NonUnitalStarSubalgebra.nonUnitalCStarAlgebra (starCore I)
  letI : IsUnital (starCore I) := CStarAlgebra.isUnital_of_isClosed_submodule
    N (starCoreEquiv I) hN
  let p : M := (IsUnital.isUnital.choose : starCore I)
  have hp : IsStarProjection p := isStarProjection_coe_unit (starCore I)
  have hIp : I = Ideal.span {p} := le_antisymm
    (fun _ hx ↦ Ideal.mem_span_singleton'.2
      ⟨_, mul_coe_unit_eq_of_mem I hx⟩)
    ((Ideal.span_singleton_le_iff_mem I).2
      ((IsUnital.isUnital.choose : starCore I).property.1))
  exact ⟨p, ⟨hp, hIp⟩, fun q hq ↦
    (hp.eq_of_span_singleton_eq hq.1 (hIp.symm.trans hq.2)).symm⟩

/-- An ultraweakly closed right ideal of a dual C-star algebra is generated by a unique star
projection. Right ideals of `M` are represented canonically as left ideals of `Mᵐᵒᵖ`; under this
representation, the right ideal `pM` is `Ideal.span {MulOpposite.op p}`. -/
theorem existsUnique_isStarProjection_eq_span_op_of_isClosed_ultraweak (I : Ideal Mᵐᵒᵖ)
    (hI : IsClosed
      (Ultraweak.ofSubmodule (P := P) (I.restrictScalars ℂ) : Set σ(Mᵐᵒᵖ, P))) :
    ∃! p : M, IsStarProjection p ∧ I = Ideal.span {MulOpposite.op p} := by
  obtain ⟨q, ⟨hq, hIq⟩, huniq⟩ :=
    existsUnique_isStarProjection_eq_span_of_isClosed_ultraweak I hI
  refine ⟨q.unop, ⟨isStarProjection_unop_iff.mpr hq, by simpa using hIq⟩, ?_⟩
  intro p hp
  have hop : MulOpposite.op p = q := huniq (MulOpposite.op p)
    ⟨isStarProjection_op_iff.mpr hp.1, hp.2⟩
  simpa using congr_arg MulOpposite.unop hop

end Ideal
