module

public import LeanOA.Ultraweak.Ideal
public import LeanOA.Ultraweak.Multiplication
public import LeanOA.Ultraweak.WStarAlgebra

@[expose] public section

/-!
# The complete lattice of projections in a W-star algebra

For a C-star algebra with a specified Banach predual, star projections are order isomorphic to
ultraweakly closed left ideals by sending a projection `p` to `Ideal.span {p}`. This gives an
explicit complete lattice structure on star projections without making its chosen predual an
implicit typeclass output.
-/

open Filter Set
open scoped Topology Ultraweak

variable {M P : Type*} [CStarAlgebra M] [PartialOrder M] [StarOrderedRing M]
  [NormedAddCommGroup P] [NormedSpace ℂ P] [CompleteSpace P] [Predual ℂ M P]

namespace IsIdempotentElem

/-- The principal left ideal generated by an idempotent is ultraweakly closed. -/
theorem isClosed_span_singleton_ultraweak {p : M} (hp : IsIdempotentElem p) :
    IsClosed (Ultraweak.ofSubmodule (P := P)
      ((Ideal.span {p}).restrictScalars ℂ) : Set σ(M, P)) := by
  rw [show (Ideal.span {p}).restrictScalars ℂ =
      LinearMap.range (LinearMap.mulRight ℂ p) by
    ext x
    change x ∈ Ideal.span {p} ↔ _
    rw [← Ideal.range_mulRight, LinearMap.mem_range, LinearMap.mem_range]
    exact exists_congr fun y ↦ by rw [LinearMap.mulRight_apply, LinearMap.mulRight_apply]]
  rw [← Ultraweak.range_mulRightL]
  exact ContinuousLinearMap.IsIdempotentElem.isClosed_range (hp.mulRightL (P := P))

end IsIdempotentElem

namespace Ultraweak

/-- A nonempty directed set of star projections has a star-projection least upper bound, and its
canonical net converges ultraweakly to that least upper bound. -/
lemma DirectedOn.exists_isLUB_isStarProjection (s : Set σ(M, P))
    (hs : DirectedOn (· ≤ ·) s) (hnon : s.Nonempty)
    (hproj : ∀ p ∈ s, IsStarProjection p) :
    ∃ p : σ(M, P), IsStarProjection p ∧ IsLUB s p ∧
      Tendsto (Subtype.val : s → σ(M, P)) atTop (𝓝 p) := by
  letI : Nonempty s := hnon.to_subtype
  letI : IsDirectedOrder s := ⟨hs.directed_val⟩
  obtain ⟨p, hp, hp_tendsto⟩ := DirectedOn.exists_isLUB s hs hnon
    ⟨1, fun q hq ↦ (hproj q hq).le_one⟩
  have hp_star : star p = p := by
    apply tendsto_nhds_unique hp_tendsto.star
    exact hp_tendsto.congr' <| Eventually.of_forall fun q ↦
      (hproj q q.2).isSelfAdjoint.star_eq.symm
  have hqp (q : s) : q.1 * p = q.1 := by
    apply tendsto_nhds_unique (hp_tendsto.const_mul q.1)
    apply tendsto_const_nhds.congr'
    filter_upwards [Ici_mem_atTop q] with r hr
    symm
    rw [← ofUltraweak_inj, ofUltraweak_mul]
    exact ((hproj q q.2).map (ofUltraweak_starRingEquiv' M P)).le_iff_mul_eq_left
      ((hproj r r.2).map (ofUltraweak_starRingEquiv' M P)) |>.mp <| monotone_ofUltraweak hr
  have hp_mul : p * p = p := by
    apply tendsto_nhds_unique (hp_tendsto.mul_const p)
    exact hp_tendsto.congr' (Eventually.of_forall fun q ↦ (hqp q).symm)
  exact ⟨p, ⟨hp_mul, hp_star⟩, hp, hp_tendsto⟩

end Ultraweak

namespace IsStarProjection

/-- The principal left ideal generated by a projection is ultraweakly closed. -/
theorem isClosed_span_singleton_ultraweak {p : M} (hp : IsStarProjection p) :
    IsClosed (Ultraweak.ofSubmodule (P := P)
      ((Ideal.span {p}).restrictScalars ℂ) : Set σ(M, P)) :=
  hp.isIdempotentElem.isClosed_span_singleton_ultraweak (P := P)

/-- Star projections are order isomorphic to ultraweakly closed left ideals via their principal
left ideals. -/
noncomputable def orderIsoUltraweakClosedIdeal :
    {p : M // IsStarProjection p} ≃o
      {I : Ideal M // IsClosed (Ultraweak.ofSubmodule (P := P)
        (I.restrictScalars ℂ) : Set σ(M, P))} where
  toFun p := ⟨Ideal.span {p.1}, p.2.isClosed_span_singleton_ultraweak (P := P)⟩
  invFun I := ⟨(Ideal.existsUnique_isStarProjection_eq_span_of_isClosed_ultraweak I.1 I.2).choose,
    (Ideal.existsUnique_isStarProjection_eq_span_of_isClosed_ultraweak I.1 I.2).choose_spec.1.1⟩
  left_inv p := by
    let h := Ideal.existsUnique_isStarProjection_eq_span_of_isClosed_ultraweak
      (Ideal.span {p.1}) (p.2.isClosed_span_singleton_ultraweak (P := P))
    exact Subtype.ext <| h.unique h.choose_spec.1 ⟨p.2, rfl⟩
  right_inv I := Subtype.ext <|
    (Ideal.existsUnique_isStarProjection_eq_span_of_isClosed_ultraweak I.1 I.2).choose_spec.1.2.symm
  map_rel_iff' {p q} := p.2.span_singleton_le_span_singleton_iff q.2

/-- The complete lattice structure on star projections determined by a specified Banach predual.

This named layer keeps `P` explicit: the predual does not occur in the projection subtype, so an
instance parameterized directly by `P` would leave an unconstrained typeclass metavariable. -/
@[implicit_reducible]
noncomputable def completeLatticeOfPredual : CompleteLattice {p : M // IsStarProjection p} := by
  let e := orderIsoUltraweakClosedIdeal (M := M) (P := P)
  let I : Set {p : M // IsStarProjection p} →
      {I : Ideal M // IsClosed (Ultraweak.ofSubmodule (P := P)
        (I.restrictScalars ℂ) : Set σ(M, P))} := fun s ↦
    ⟨⨅ p : s, Ideal.span {p.1.1}, by
      rw [Submodule.restrictScalars_iInf]
      exact Ultraweak.isClosed_iInf_ofSubmodule _ fun p ↦
        p.1.2.isClosed_span_singleton_ultraweak (P := P)⟩
  letI : InfSet {p : M // IsStarProjection p} := ⟨fun s ↦ e.symm (I s)⟩
  refine completeLatticeOfInf _ ?_
  intro s
  constructor
  · intro p hp
    change e.symm (I s) ≤ p
    rw [← e.le_iff_le, e.apply_symm_apply]
    change (⨅ q : s, Ideal.span {q.1.1}) ≤ Ideal.span {p.1}
    exact iInf_le_of_le (⟨p, hp⟩ : s) le_rfl
  · intro p hp
    change p ≤ e.symm (I s)
    rw [← e.le_iff_le, e.apply_symm_apply]
    change Ideal.span {p.1} ≤ ⨅ q : s, Ideal.span {q.1.1}
    exact le_iInf fun q : s ↦
      (p.2.span_singleton_le_span_singleton_iff q.1.2).2 <| hp q.2

/-- A projection which is the least upper bound of a nonempty directed family among projections
is already its least upper bound in the ambient C-star algebra.

The specified predual is an explicit proof parameter: it supplies the ultraweak compactness used
to construct an ambient least upper bound, but is not recoverable from the statement. -/
theorem isLUB_coe_of_isLUB (P : Type*) [NormedAddCommGroup P] [NormedSpace ℂ P]
    [CompleteSpace P] [Predual ℂ M P] (s : Set {p : M // IsStarProjection p})
    (hs : DirectedOn (· ≤ ·) s) (hnon : s.Nonempty) {p : {p : M // IsStarProjection p}}
    (hp : IsLUB s p) :
    IsLUB ((fun q : {p : M // IsStarProjection p} ↦ q.1) '' s) p.1 := by
  let f : {p : M // IsStarProjection p} → σ(M, P) := fun q ↦
    toUltraweak ℂ P q.1
  have hf : Monotone f := Ultraweak.monotone_toUltraweak.comp fun _ _ ↦ id
  have hproj : ∀ q ∈ f '' s, IsStarProjection q := by
    rintro _ ⟨q, hq, rfl⟩
    exact q.2.map (Ultraweak.ofUltraweak_starRingEquiv' M P).symm
  obtain ⟨q, hq, hq_lub, -⟩ :=
    Ultraweak.DirectedOn.exists_isLUB_isStarProjection (f '' s)
      (hs.mono_comp hf) (hnon.image f) hproj
  have hq_lubM :
      IsLUB ((fun q : {p : M // IsStarProjection p} ↦ q.1) '' s) (ofUltraweak q) := by
    refine ⟨fun a ha ↦ ?_, fun a ha ↦ ?_⟩
    · obtain ⟨r, hr, rfl⟩ := ha
      exact Ultraweak.monotone_ofUltraweak (hq_lub.1 ⟨r, hr, rfl⟩)
    · exact Ultraweak.monotone_ofUltraweak <| hq_lub.2 fun x hx ↦ by
        obtain ⟨r, hr, rfl⟩ := hx
        exact Ultraweak.monotone_toUltraweak (ha ⟨r, hr, rfl⟩)
  let r : {p : M // IsStarProjection p} :=
    ⟨ofUltraweak q, hq.map (Ultraweak.ofUltraweak_starRingEquiv' M P)⟩
  have hr : IsLUB s r := by
    refine ⟨fun a ha ↦ hq_lubM.1 ⟨a, ha, rfl⟩, fun a ha ↦ hq_lubM.2 ?_⟩
    rintro _ ⟨b, hb, rfl⟩
    exact ha hb
  have hrp : r = p := hr.unique hp
  change IsLUB _ r.1 at hq_lubM
  simpa only [hrp] using hq_lubM

/-- The canonical net of a nonempty directed family of projections converges ultraweakly to any
specified least upper bound in the projection order. -/
theorem tendsto_toUltraweak_of_isLUB (s : Set {p : M // IsStarProjection p})
    (hs : DirectedOn (· ≤ ·) s) (hnon : s.Nonempty) {p : {p : M // IsStarProjection p}}
    (hp : IsLUB s p) :
    Tendsto (fun q : s ↦ toUltraweak ℂ P q.1.1) atTop
      (𝓝 (toUltraweak ℂ P p.1)) := by
  letI : Nonempty s := hnon.to_subtype
  letI : IsDirectedOrder s := ⟨hs.directed_val⟩
  let f : {p : M // IsStarProjection p} → σ(M, P) := fun q ↦ toUltraweak ℂ P q.1
  have hf : Monotone f := Ultraweak.monotone_toUltraweak.comp fun _ _ ↦ id
  have hUw : IsLUB (f '' s) (toUltraweak ℂ P p.1) := by
    refine ⟨fun a ha ↦ ?_, fun a ha ↦ ?_⟩
    · obtain ⟨r, hr, rfl⟩ := ha
      exact Ultraweak.monotone_toUltraweak
        ((isLUB_coe_of_isLUB P s hs hnon hp).1 ⟨r, hr, rfl⟩)
    · rw [← toUltraweak_ofUltraweak (𝕜 := ℂ) (m := a)]
      exact Ultraweak.monotone_toUltraweak <|
        (isLUB_coe_of_isLUB P s hs hnon hp).2 fun x hx ↦ by
          obtain ⟨r, hr, rfl⟩ := hx
          exact Ultraweak.monotone_ofUltraweak (ha ⟨r, hr, rfl⟩)
  change Tendsto (f ∘ (Subtype.val : s → {p : M // IsStarProjection p})) atTop _
  apply tendsto_atTop_isLUB (hf.comp <| Subtype.mono_coe (· ∈ s))
  simpa only [Set.range_comp, Subtype.range_coe] using hUw

section WStarAlgebra

variable {M : Type*} [CStarAlgebra M] [PartialOrder M] [StarOrderedRing M] [WStarAlgebra M]

/-- The canonical complete lattice of star projections in a W-star algebra.

The selected predual is used only to prove completeness. The resulting infima and suprema are
determined uniquely by the ambient projection order, so the structure is independent of that
selection. -/
noncomputable instance instCompleteLatticeSubtypeOfWStarAlgebra :
    CompleteLattice {p : M // IsStarProjection p} :=
  completeLatticeOfPredual (P := WStarAlgebra.predual M)

/-- The supremum of a nonempty directed set of projections is its least upper bound in the
ambient C-star algebra, not merely in the projection subtype. -/
theorem isLUB_coe_sSup (s : Set {p : M // IsStarProjection p})
    (hs : DirectedOn (· ≤ ·) s) (hnon : s.Nonempty) :
    IsLUB ((fun p : {p : M // IsStarProjection p} ↦ p.1) '' s) (sSup s).1 :=
  isLUB_coe_of_isLUB (WStarAlgebra.predual M) s hs hnon (isLUB_sSup s)

variable {P : Type*} [NormedAddCommGroup P] [NormedSpace ℂ P] [CompleteSpace P]
  [Predual ℂ M P]

/-- The canonical net of a nonempty directed set of projections converges ultraweakly to its
lattice supremum. -/
theorem tendsto_toUltraweak_sSup (s : Set {p : M // IsStarProjection p})
    (hs : DirectedOn (· ≤ ·) s) (hnon : s.Nonempty) :
    Tendsto (fun p : s ↦ toUltraweak ℂ P p.1.1) atTop
      (𝓝 (toUltraweak ℂ P (sSup s).1)) :=
  tendsto_toUltraweak_of_isLUB s hs hnon (isLUB_sSup s)

end WStarAlgebra

end IsStarProjection
