module

public import LeanOA.CStarAlgebra.PositiveLinearFunctional
public import LeanOA.MackeySpace
public import LeanOA.Mathlib.Analysis.LocallyConvex.WithSeminorms
public import LeanOA.Ultraweak.PolarDecomposition
public import LeanOA.Ultraweak.Uniformity

@[expose] public section

/-!
# The strong topology of a dual C-star-algebra

This file defines `Ultraweak.Strong M P`, the type synonym of a C-star-algebra `M` equipped with
the strong topology determined by a specified predual `P`. Its topology is generated by the GNS
seminorms associated to positive ultraweakly continuous functionals.

The synonym deliberately carries only its additive and complex-linear structures. Algebraic
expressions are transported through `ofStrong`, keeping the topology-bearing type separate from
the C-star-algebra structure on `M`.
-/

open Metric Set Topology
open scoped ComplexOrder ComplexStarModule NNReal Ultraweak

namespace Ultraweak

noncomputable section

variable {M P : Type*} [CStarAlgebra M] [PartialOrder M] [StarOrderedRing M]
  [NormedAddCommGroup P] [NormedSpace ℂ P] [Predual ℂ M P]

/-- A C-star-algebra `M` equipped with the strong topology determined by its specified predual
`P`. -/
@[nolint unusedArguments]
def Strong (M P : Type*) [CStarAlgebra M] [PartialOrder M] [StarOrderedRing M]
    [NormedAddCommGroup P] [NormedSpace ℂ P] [Predual ℂ M P] := M
deriving AddCommGroup, Module ℂ

@[inherit_doc]
scoped[Ultraweak] notation "s(" M ", " P ")" => Strong M P

variable (P) in
/-- The canonical map from `M` to `s(M, P)`. -/
def toStrong (x : M) : s(M, P) := x

/-- The canonical map from `s(M, P)` to `M`. -/
def ofStrong (x : s(M, P)) : M := x

@[simp]
lemma toStrong_ofStrong (x : s(M, P)) : toStrong P (ofStrong x) = x := rfl

@[simp]
lemma ofStrong_toStrong (x : M) : ofStrong (toStrong P x) = x := rfl

@[simp]
lemma ofStrong_add (x y : s(M, P)) : ofStrong (x + y) = ofStrong x + ofStrong y := rfl

@[simp]
lemma toStrong_add (x y : M) : toStrong P (x + y) = toStrong P x + toStrong P y := rfl

@[simp]
lemma ofStrong_smul (c : ℂ) (x : s(M, P)) : ofStrong (c • x) = c • ofStrong x := rfl

@[simp]
lemma toStrong_smul (c : ℂ) (x : M) : toStrong P (c • x) = c • toStrong P x := rfl

@[simp]
lemma ofStrong_zero : ofStrong (0 : s(M, P)) = (0 : M) := rfl

@[simp]
lemma toStrong_zero : toStrong P (0 : M) = (0 : s(M, P)) := rfl

@[simp]
lemma ofStrong_neg (x : s(M, P)) : ofStrong (-x) = -ofStrong x := rfl

@[simp]
lemma toStrong_neg (x : M) : toStrong P (-x) = -toStrong P x := rfl

@[simp]
lemma ofStrong_sub (x y : s(M, P)) : ofStrong (x - y) = ofStrong x - ofStrong y := rfl

@[simp]
lemma toStrong_sub (x y : M) : toStrong P (x - y) = toStrong P x - toStrong P y := rfl

@[simp]
lemma ofStrong_inj {x y : s(M, P)} : ofStrong x = ofStrong y ↔ x = y := Iff.rfl

@[simp]
lemma toStrong_inj {x y : M} : toStrong P x = toStrong P y ↔ x = y := Iff.rfl

variable (M P) in
/-- The canonical linear equivalence from `s(M, P)` to `M`. -/
@[simps]
def Strong.linearEquiv : s(M, P) ≃ₗ[ℂ] M where
  toFun := ofStrong
  invFun := toStrong P
  map_add' _ _ := ofStrong_add _ _
  map_smul' _ _ := ofStrong_smul _ _
  left_inv := toStrong_ofStrong
  right_inv := ofStrong_toStrong

namespace Strong

/-- The strong seminorm associated to a positive ultraweakly continuous functional. -/
def seminorm (phi : σ(M, P) →P[ℂ] ℂ) : Seminorm ℂ s(M, P) :=
  (phi.comp (toUltraweakPosCLM P)).toPositiveLinearMap.gnsSeminorm.comp
    (linearEquiv M P).toLinearMap

@[simp]
lemma seminorm_apply (phi : σ(M, P) →P[ℂ] ℂ) (x : s(M, P)) :
    seminorm phi x = √‖phi (toUltraweak ℂ P (star (ofStrong x) * ofStrong x))‖ := by
  simp [seminorm]

/-- The family of strong seminorms indexed by positive ultraweakly continuous functionals. -/
def seminormFamily : SeminormFamily ℂ s(M, P) (σ(M, P) →P[ℂ] ℂ) :=
  seminorm

noncomputable instance : TopologicalSpace s(M, P) :=
  seminormFamily.moduleFilterBasis.topology

/-- The topology of `s(M, P)` is induced by its defining family of strong seminorms. -/
lemma withSeminorms : WithSeminorms (seminormFamily (M := M) (P := P)) := ⟨rfl⟩

instance : IsTopologicalAddGroup s(M, P) :=
  withSeminorms.topologicalAddGroup

instance : ContinuousSMul ℂ s(M, P) :=
  withSeminorms.continuousSMul

instance : LocallyConvexSpace ℂ s(M, P) :=
  let _ : Module ℝ s(M, P) := RestrictScalars.module ℝ ℂ s(M, P)
  let _ : IsScalarTower ℝ ℂ s(M, P) := RestrictScalars.isScalarTower ℝ ℂ s(M, P)
  .to_rclike ℂ s(M, P) withSeminorms.toLocallyConvexSpace

lemma continuous_seminorm (phi : σ(M, P) →P[ℂ] ℂ) : Continuous (seminorm phi) :=
  withSeminorms.continuous_seminorm phi

/-! ## Explicit comparison maps -/

/-- The canonical algebraic equivalence from the strong type synonym to the ultraweak one. -/
def toUltraweakEquiv : s(M, P) ≃ₗ[ℂ] σ(M, P) :=
  linearEquiv M P ≪≫ₗ (Ultraweak.linearEquiv ℂ M P).symm

@[simp]
lemma toUltraweakEquiv_apply (x : s(M, P)) :
    toUltraweakEquiv x = toUltraweak ℂ P (ofStrong x) := rfl

@[simp]
lemma ofUltraweak_toUltraweakEquiv (x : s(M, P)) :
    ofUltraweak (toUltraweakEquiv x) = ofStrong x := by
  simp [toUltraweakEquiv_apply]

@[simp]
lemma ofStrong_toUltraweakEquiv_symm (x : σ(M, P)) :
    ofStrong ((toUltraweakEquiv (M := M) (P := P)).symm x) = ofUltraweak x := by
  have h := congrArg ofUltraweak
    ((toUltraweakEquiv (M := M) (P := P)).apply_symm_apply x)
  rw [toUltraweakEquiv_apply] at h
  simpa only [ofUltraweak_toUltraweak] using h

/-- The identity map from the strong topology to the ultraweak topology, as a linear map. -/
def toUltraweakₗ : s(M, P) →ₗ[ℂ] σ(M, P) :=
  toUltraweakEquiv.toLinearMap

@[simp]
lemma toUltraweakₗ_apply (x : s(M, P)) :
    toUltraweakₗ x = toUltraweak ℂ P (ofStrong x) := rfl

lemma toUltraweakₗ_toUltraweakEquiv_symm (x : σ(M, P)) :
    toUltraweakₗ ((toUltraweakEquiv (M := M) (P := P)).symm x) = x :=
  (toUltraweakEquiv (M := M) (P := P)).apply_symm_apply x

private theorem continuous_comp_toUltraweakₗ_of_isSelfAdjoint [CompleteSpace P]
    (f : σ(M, P) →L[ℂ] ℂ) (hf : IsSelfAdjoint (WithConv.toConv f)) :
    Continuous fun x : s(M, P) ↦ f (toUltraweakₗ x) := by
  obtain ⟨u, phi, hu, huU, hpolar⟩ :=
    exists_positive_comp_mulLeft_of_isSelfAdjoint f hf
  let c : ℝ≥0 := ⟨√‖phi (toUltraweak ℂ P (1 : M))‖, by positivity⟩
  apply withSeminorms.continuous_normedSpace_rng ℂ
    (f.toLinearMap.comp toUltraweakₗ)
  refine ⟨{phi}, c, fun x ↦ ?_⟩
  simp only [Seminorm.comp_apply, Finset.sup_singleton, seminormFamily,
    Seminorm.smul_apply, NNReal.smul_def]
  change ‖f (toUltraweakₗ x)‖ ≤ (c : ℝ) * seminorm phi x
  rw [hpolar]
  change ‖phi (toUltraweak ℂ P (u * ofStrong x))‖ ≤ c * seminorm phi x
  calc
    _ ≤ √‖(phi.comp (toUltraweakPosCLM P)).toPositiveLinearMap (star u * u)‖ *
        √‖(phi.comp (toUltraweakPosCLM P)).toPositiveLinearMap
          (star (ofStrong x) * ofStrong x)‖ := by
      simpa [hu.star_eq] using
        (phi.comp (toUltraweakPosCLM P)).toPositiveLinearMap.cauchy_schwarz_star_mul
          u (ofStrong x)
    _ = c * seminorm phi x := by
      rw [(Unitary.mem_iff.mp huU).1]
      simp only [PositiveContinuousLinearMap.coe_toPositiveLinearMap,
        PositiveContinuousLinearMap.comp_apply, toUltraweakPosCLM_apply, toUltraweak_one,
        toUltraweak_mul, toUltraweak_star, seminorm_apply, mul_eq_mul_right_iff, norm_nonneg,
        Real.sqrt_eq_zero, norm_eq_zero, c]
      exact Or.inl rfl

/-- Every ultraweakly continuous functional remains continuous after precomposition with the
canonical map from the strong topology. -/
theorem continuous_comp_toUltraweakₗ [CompleteSpace P] (f : σ(M, P) →L[ℂ] ℂ) :
    Continuous fun x : s(M, P) ↦ f (toUltraweakₗ x) := by
  let fr : σ(M, P) →L[ℂ] ℂ := (ℜ (WithConv.toConv f)).1.ofConv
  let fi : σ(M, P) →L[ℂ] ℂ := (ℑ (WithConv.toConv f)).1.ofConv
  have hfr : IsSelfAdjoint (WithConv.toConv fr) := by
    change IsSelfAdjoint (ℜ (WithConv.toConv f)).1
    exact (ℜ (WithConv.toConv f)).2
  have hfi : IsSelfAdjoint (WithConv.toConv fi) := by
    change IsSelfAdjoint (ℑ (WithConv.toConv f)).1
    exact (ℑ (WithConv.toConv f)).2
  have hf : fr + Complex.I • fi = f := by
    simpa [fr, fi] using
      congrArg WithConv.ofConv (realPart_add_I_smul_imaginaryPart (WithConv.toConv f))
  rw [← hf]
  convert
    (continuous_comp_toUltraweakₗ_of_isSelfAdjoint fr hfr).add <|
      (continuous_comp_toUltraweakₗ_of_isSelfAdjoint fi hfi).const_mul Complex.I using 1
  funext x
  simp

/-- The canonical linear map from the strong topology to the ultraweak topology is continuous. -/
theorem continuous_toUltraweakₗ [CompleteSpace P] :
    Continuous (toUltraweakₗ : s(M, P) → σ(M, P)) := by
  refine Ultraweak.continuous_of_continuous_eval fun p ↦ ?_
  let f := predualDualEquiv ℂ M P p
  simpa [f] using continuous_comp_toUltraweakₗ f

/-- The strong topology is Hausdorff. -/
instance [CompleteSpace P] : T2Space s(M, P) :=
  T2Space.of_injective_continuous toUltraweakEquiv.injective continuous_toUltraweakₗ

/-- The canonical continuous linear map from the strong topology to the ultraweak topology. -/
noncomputable def toUltraweakL [CompleteSpace P] : s(M, P) →L[ℂ] σ(M, P) :=
  ⟨toUltraweakₗ, continuous_toUltraweakₗ⟩

@[simp]
lemma toUltraweakL_apply [CompleteSpace P] (x : s(M, P)) :
    toUltraweakL x = toUltraweak ℂ P (ofStrong x) := rfl

/-- Norm-closed balls in the underlying C-star-algebra are closed in the strong topology. -/
theorem isClosed_closedBall [CompleteSpace P] (x : M) (r : ℝ) :
    IsClosed (ofStrong ⁻¹' closedBall x r : Set s(M, P)) := by
  have h := (Ultraweak.isClosed_closedBall ℂ P x r).preimage continuous_toUltraweakₗ
  convert h using 1
  ext y
  simp

/-! ## The continuous dual -/

/-- The dual pairing on the strong type synonym obtained from the ultraweak continuous dual. -/
noncomputable def pairing : s(M, P) →ₗ[ℂ] WeakDual ℂ σ(M, P) →ₗ[ℂ] ℂ :=
  (weakDualPairing ℂ σ(M, P)).flip.comp toUltraweakₗ

@[simp]
lemma pairing_apply_apply (x : s(M, P)) (f : WeakDual ℂ σ(M, P)) :
    pairing x f = f (toUltraweakₗ x) := rfl

instance pairing_flip_isWeak :
    (pairing (M := M) (P := P)).flip.IsWeak :=
  LinearMap.IsWeak.congr (weakDualPairing ℂ σ(M, P)) pairing.flip
    (ContinuousLinearEquiv.refl ℂ _) (toUltraweakEquiv (M := M) (P := P)).symm <| by
      ext f x
      rfl

private lemma finset_sup_seminorm_le_sum [CompleteSpace P]
    (s : Finset (σ(M, P) →P[ℂ] ℂ)) :
    s.sup (seminormFamily (M := M) (P := P)) ≤ seminorm (∑ phi ∈ s, phi) := by
  classical
  apply Finset.sup_le
  intro phi hphi x
  change (phi.comp (toUltraweakPosCLM P)).toPositiveLinearMap.gnsSeminorm (ofStrong x) ≤
    (((∑ psi ∈ s, psi).comp (toUltraweakPosCLM P)).toPositiveLinearMap.gnsSeminorm
      (ofStrong x))
  apply PositiveLinearMap.gnsSeminorm_mono
  intro a ha
  change phi (toUltraweak ℂ P a) ≤ (∑ psi ∈ s, psi) (toUltraweak ℂ P a)
  rw [PositiveContinuousLinearMap.sum_apply]
  exact Finset.single_le_sum (fun psi _ ↦ psi.map_nonneg ha) hphi

private theorem exists_bound_by_gnsSeminorm [CompleteSpace P]
    (f : StrongDual ℂ s(M, P)) :
    ∃ (phi : σ(M, P) →P[ℂ] ℂ) (C : ℝ≥0), ∀ x,
      ‖f x‖ ≤ C * (phi.comp (toUltraweakPosCLM P)).toPositiveLinearMap.gnsSeminorm
        (ofStrong x) := by
  obtain ⟨s, C, -, hf⟩ := Seminorm.bound_of_continuous withSeminorms
    ((normSeminorm ℂ ℂ).comp f.toLinearMap) (continuous_norm.comp f.continuous)
  refine ⟨∑ phi ∈ s, phi, C, fun x ↦ (hf x).trans ?_⟩
  change C * s.sup (seminormFamily (M := M) (P := P)) x ≤ _
  gcongr
  exact finset_sup_seminorm_le_sum s x

/-- GNS coefficients of positive ultraweakly continuous functionals come from the specified
predual under its canonical isometric embedding into the norm dual. -/
theorem gnsCoefficient_mem_range_toDualₗᵢ [CompleteSpace P]
    (phi : σ(M, P) →P[ℂ] ℂ) (y : M) :
    (phi.comp (toUltraweakPosCLM P)).toPositiveLinearMap.gnsCoefficient y ∈
      range (Predual.toDualₗᵢ (𝕜 := ℂ) (M := M) (P := P)) := by
  let g : σ(M, P) →L[ℂ] ℂ :=
    phi.toContinuousLinearMap.comp (mulLeftL (P := P) (star y))
  refine ⟨(predualDualEquiv ℂ M P).symm g, ?_⟩
  ext x
  rw [Predual.toDualₗᵢ_apply]
  calc
    _ = predualDualEquiv ℂ M P ((predualDualEquiv ℂ M P).symm g)
        (toUltraweak ℂ P x) := by
      simpa using (predualDualEquiv_apply_apply
        ((predualDualEquiv ℂ M P).symm g) (toUltraweak ℂ P x)).symm
    _ = g (toUltraweak ℂ P x) := by rw [LinearEquiv.apply_symm_apply]
    _ = (phi.comp (toUltraweakPosCLM P)).toPositiveLinearMap.gnsCoefficient y x := by
      simp [g]

private theorem exists_predual [CompleteSpace P] (f : StrongDual ℂ s(M, P)) :
    ∃ p : P, ∀ x : M, f (toStrong P x) =
      Predual.equivDual (𝕜 := ℂ) (M := M) (P := P) x p := by
  obtain ⟨phi, C, hf⟩ := exists_bound_by_gnsSeminorm f
  let psi := (phi.comp (toUltraweakPosCLM P)).toPositiveLinearMap
  let fMₗ : M →ₗ[ℂ] ℂ := f.toLinearMap.comp (linearEquiv M P).symm.toLinearMap
  let fM : M →L[ℂ] ℂ := fMₗ.mkContinuousOfExistsBound ⟨C * ‖psi.toGNS'‖, fun x ↦ by
    change ‖f (toStrong P x)‖ ≤ (C : ℝ) * ‖psi.toGNS'‖ * ‖x‖
    grw [hf (toStrong P x)]
    calc
      (C : ℝ) * psi.gnsSeminorm x = (C : ℝ) * ‖psi.toGNS' x‖ := by
        congr 1
        change ‖psi.toPreGNS' x‖ = ‖(psi.toPreGNS' x :
          UniformSpace.Completion psi.PreGNS')‖
        rw [UniformSpace.Completion.norm_coe]
      _ ≤ (C : ℝ) * (‖psi.toGNS'‖ * ‖x‖) :=
        mul_le_mul_of_nonneg_left (psi.toGNS'.le_opNorm x) C.coe_nonneg
      _ = (C : ℝ) * ‖psi.toGNS'‖ * ‖x‖ := by rw [mul_assoc]⟩
  have hfM : fM ∈ closure (range psi.gnsCoefficient) :=
    psi.mem_closure_range_gnsCoefficient_of_bound fM C fun x ↦ by
      simpa [fM, fMₗ, psi] using hf (toStrong P x)
  have hcoeff : range psi.gnsCoefficient ⊆
      range (Predual.toDualₗᵢ (𝕜 := ℂ) (M := M) (P := P)) := by
    rintro - ⟨y, rfl⟩
    exact gnsCoefficient_mem_range_toDualₗᵢ phi y
  obtain ⟨p, hp⟩ := closure_minimal hcoeff Predual.isClosed_range_toDualₗᵢ hfM
  refine ⟨p, fun x ↦ ?_⟩
  simpa [fM, fMₗ] using congr($(hp.symm) x)

/-- Restriction of an ultraweakly continuous functional to the strong topology. -/
noncomputable def dualMap [CompleteSpace P] :
    WeakDual ℂ σ(M, P) →ₗ[ℂ] StrongDual ℂ s(M, P) where
  toFun f := ⟨pairing.flip f, by
    change Continuous fun x : s(M, P) ↦ f (toUltraweakₗ x)
    simpa only [WeakDual.toStrongDual_apply] using
      continuous_comp_toUltraweakₗ (WeakDual.toStrongDual f)⟩
  map_add' _ _ := by ext; simp
  map_smul' _ _ := by ext; simp

@[simp]
lemma dualMap_apply_apply [CompleteSpace P] (f : WeakDual ℂ σ(M, P)) (x : s(M, P)) :
    dualMap f x = f (toUltraweakₗ x) := rfl

/-- Restriction from the ultraweak continuous dual to the strong continuous dual is injective. -/
theorem dualMap_injective [CompleteSpace P] :
    Function.Injective (dualMap (M := M) (P := P)) := by
  intro f g h
  apply WeakDual.toStrongDual.injective
  ext x
  have h' := congr($(h) ((toUltraweakEquiv (M := M) (P := P)).symm x))
  change f (toUltraweakₗ ((toUltraweakEquiv (M := M) (P := P)).symm x)) =
    g (toUltraweakₗ ((toUltraweakEquiv (M := M) (P := P)).symm x)) at h'
  rw [toUltraweakₗ_toUltraweakEquiv_symm] at h'
  exact h'

/-- Every strongly continuous functional is ultraweakly continuous. -/
theorem dualMap_surjective [CompleteSpace P] :
    Function.Surjective (dualMap (M := M) (P := P)) := by
  intro f
  obtain ⟨p, hp⟩ := exists_predual f
  refine ⟨(predualDualEquiv ℂ M P p).toWeakDual, ?_⟩
  ext x
  simpa using (hp (ofStrong x)).symm

/-- The continuous dual of the strong topology is the ultraweak continuous dual. -/
noncomputable def dualEquiv [CompleteSpace P] :
    WeakDual ℂ σ(M, P) ≃ₗ[ℂ] StrongDual ℂ s(M, P) :=
  LinearEquiv.ofBijective dualMap ⟨dualMap_injective, dualMap_surjective⟩

@[simp]
lemma dualEquiv_apply_apply [CompleteSpace P]
    (f : WeakDual ℂ σ(M, P)) (x : s(M, P)) :
    dualEquiv f x = f (toUltraweakₗ x) := rfl

instance pairing_isCompatibleDual [CompleteSpace P] :
    (pairing (M := M) (P := P)).IsCompatibleDual :=
  LinearEquiv.IsCompatibleDual pairing dualEquiv <| by
    ext f x
    rfl

/-- The canonical equivalence from the strong synonym to the ultraweak synonym commutes with
closure on real-convex sets. -/
theorem image_closure_toUltraweakEquiv [CompleteSpace P]
    {S : Set s(M, P)} (hS : Convex ℝ S) :
    toUltraweakEquiv '' closure S = closure (toUltraweakEquiv '' S) := by
  letI : Module ℝ s(M, P) := RestrictScalars.module ℝ ℂ s(M, P)
  letI : IsScalarTower ℝ ℂ s(M, P) := RestrictScalars.isScalarTower ℝ ℂ s(M, P)
  letI : LocallyConvexSpace ℝ s(M, P) :=
    LocallyConvexSpace.to_real ℂ s(M, P) inferInstance
  letI : Module ℝ σ(M, P) := RestrictScalars.module ℝ ℂ σ(M, P)
  letI : IsScalarTower ℝ ℂ σ(M, P) := RestrictScalars.isScalarTower ℝ ℂ σ(M, P)
  letI : LocallyConvexSpace ℂ σ(M, P) := Ultraweak.locallyConvexSpace ℂ M P
  letI : LocallyConvexSpace ℝ σ(M, P) :=
    LocallyConvexSpace.to_real ℂ σ(M, P) inferInstance
  let eDual : StrongDual ℂ σ(M, P) ≃ₗ[ℂ] StrongDual ℂ s(M, P) :=
    StrongDual.toWeakDual ≪≫ₗ dualEquiv
  apply LinearEquiv.image_closure_of_convex' hS toUltraweakEquiv eDual
  intro f
  ext x
  rfl

/-- For `f : M →ₗ[ℂ] ℂ`, continuity of `x ↦ f (ofUltraweak x)` on `σ(M, P)` is
equivalent to continuity of `x ↦ f (ofStrong x)` on `s(M, P)`. -/
theorem continuous_ultraweak_iff_strong [CompleteSpace P] (f : M →ₗ[ℂ] ℂ) :
    Continuous (fun x : σ(M, P) ↦ f (ofUltraweak x)) ↔
      Continuous (fun x : s(M, P) ↦ f (ofStrong x)) := by
  constructor
  · intro hf
    let fU : StrongDual ℂ σ(M, P) :=
      ⟨f.comp (Ultraweak.linearEquiv ℂ M P).toLinearMap, hf⟩
    simpa [fU] using continuous_comp_toUltraweakₗ fU
  · intro hf
    let fS : StrongDual ℂ s(M, P) :=
      ⟨f.comp (linearEquiv M P).toLinearMap, hf⟩
    let g := (dualEquiv (M := M) (P := P)).symm fS
    have hg := (WeakDual.toStrongDual g).continuous
    convert hg using 1
    funext x
    have h := congr($(dualEquiv_apply_apply g
      ((toUltraweakEquiv (M := M) (P := P)).symm x)))
    rw [(dualEquiv (M := M) (P := P)).apply_symm_apply] at h
    change f (ofStrong ((toUltraweakEquiv (M := M) (P := P)).symm x)) =
      g (toUltraweakₗ ((toUltraweakEquiv (M := M) (P := P)).symm x)) at h
    rw [ofStrong_toUltraweakEquiv_symm, toUltraweakₗ_toUltraweakEquiv_symm] at h
    exact h

private theorem continuous_ultraweak_of_continuousOn_strong_closedUnitBall
    [CompleteSpace P] (f : M →ₗ[ℂ] ℂ)
    (hf : ContinuousOn (fun x : s(M, P) ↦ f (ofStrong x))
      (ofStrong ⁻¹' closedBall 0 1)) :
    Continuous fun x : σ(M, P) ↦ f (ofUltraweak x) := by
  let fS : s(M, P) →ₗ[ℂ] ℂ := f.comp (linearEquiv M P).toLinearMap
  let fU : σ(M, P) →ₗ[ℂ] ℂ := f.comp (Ultraweak.linearEquiv ℂ M P).toLinearMap
  let S : Set s(M, P) := fS.ker ∩ (ofStrong ⁻¹' closedBall 0 1)
  have hSclosed : IsClosed S := by
    rw [show S = (fS.ker : Set s(M, P)) ∩ (ofStrong ⁻¹' closedBall 0 1) by rfl,
      inter_comm]
    exact hf.preimage_isClosed_of_isClosed (isClosed_closedBall 0 1) isClosed_singleton
  have hSconvex : Convex ℝ S := by
    letI : Module ℝ s(M, P) := RestrictScalars.module ℝ ℂ s(M, P)
    letI : IsScalarTower ℝ ℂ s(M, P) := RestrictScalars.isScalarTower ℝ ℂ s(M, P)
    rw [show S = (fS.ker : Set s(M, P)) ∩ (ofStrong ⁻¹' closedBall 0 1) by rfl]
    refine (show Convex ℝ (fS.ker.restrictScalars ℝ : Set s(M, P)) from
      (fS.ker.restrictScalars ℝ).convex).inter ?_
    exact (convex_closedBall (0 : M) 1).linear_preimage
      ((linearEquiv M P).restrictScalars ℝ).toLinearMap
  have himageClosed : IsClosed (toUltraweakEquiv '' S) := by
    rw [← closure_eq_iff_isClosed, ← image_closure_toUltraweakEquiv hSconvex,
      hSclosed.closure_eq]
  apply Ultraweak.continuous_linearMap_of_isClosed_ker_inter_closedBall fU
  convert himageClosed using 1
  rw [LinearEquiv.image_eq_preimage_symm]
  ext x
  simp [S, fS, fU, ofStrong_toUltraweakEquiv_symm]

/-- For `f : M →ₗ[ℂ] ℂ`, the following are equivalent: continuity of
`x ↦ f (ofUltraweak x)` on `σ(M, P)`; continuity of `x ↦ f (ofStrong x)` on `s(M, P)`;
continuity of the former on the pullback of the norm-closed unit ball; and continuity of the
latter on the corresponding pullback. -/
theorem continuousOn_closedUnitBall_tfae [CompleteSpace P] (f : M →ₗ[ℂ] ℂ) :
    List.TFAE [
      Continuous (fun x : σ(M, P) ↦ f (ofUltraweak x)),
      Continuous (fun x : s(M, P) ↦ f (ofStrong x)),
      ContinuousOn (fun x : σ(M, P) ↦ f (ofUltraweak x))
        (ofUltraweak ⁻¹' closedBall 0 1),
      ContinuousOn (fun x : s(M, P) ↦ f (ofStrong x))
        (ofStrong ⁻¹' closedBall 0 1)] := by
  tfae_have 1 ↔ 2 := continuous_ultraweak_iff_strong f
  tfae_have 1 → 3 := Continuous.continuousOn
  tfae_have 3 → 1 := by
    intro h
    exact Ultraweak.continuous_linearMap_of_continuousOn
      (f.comp (Ultraweak.linearEquiv ℂ M P).toLinearMap) h
  tfae_have 2 → 4 := Continuous.continuousOn
  tfae_have 4 → 1 := continuous_ultraweak_of_continuousOn_strong_closedUnitBall f
  tfae_finish

/-- The canonical algebraic equivalence from the Mackey topology associated to the ultraweak
continuous dual to the strong type synonym. -/
def fromMackeyEquiv : MackeySpace ℂ σ(M, P) ≃ₗ[ℂ] s(M, P) :=
  ofMackeySpace ℂ σ(M, P) ≪≫ₗ Ultraweak.linearEquiv ℂ M P ≪≫ₗ (linearEquiv M P).symm

@[simp]
lemma ofStrong_fromMackeyEquiv (x : MackeySpace ℂ σ(M, P)) :
    ofStrong (fromMackeyEquiv x) = ofUltraweak (ofMackeySpace ℂ σ(M, P) x) :=
  rfl

@[simp]
lemma toUltraweakₗ_fromMackeyEquiv (x : MackeySpace ℂ σ(M, P)) :
    toUltraweakₗ (fromMackeyEquiv x) = ofMackeySpace ℂ σ(M, P) x :=
  rfl

@[simp]
lemma ofMackeySpace_fromMackeyEquiv_symm (x : s(M, P)) :
    ofMackeySpace ℂ σ(M, P) ((fromMackeyEquiv (M := M) (P := P)).symm x) =
      toUltraweakₗ x :=
  rfl

/-- The identity map from the Mackey topology associated to the ultraweak continuous dual to the
strong topology, as a linear map. -/
def fromMackeyₗ : MackeySpace ℂ σ(M, P) →ₗ[ℂ] s(M, P) :=
  fromMackeyEquiv.toLinearMap

@[simp]
lemma ofStrong_fromMackeyₗ (x : MackeySpace ℂ σ(M, P)) :
    ofStrong (fromMackeyₗ x) = ofUltraweak (ofMackeySpace ℂ σ(M, P) x) := rfl

@[simp]
lemma toUltraweakₗ_fromMackeyₗ (x : MackeySpace ℂ σ(M, P)) :
    toUltraweakₗ (fromMackeyₗ x) = ofMackeySpace ℂ σ(M, P) x :=
  rfl

/-- The canonical map from the Mackey topology to the strong topology is continuous. -/
theorem continuous_fromMackeyₗ [CompleteSpace P] :
    Continuous (fromMackeyₗ : MackeySpace ℂ σ(M, P) → s(M, P)) := by
  let e := (toUltraweakEquiv (M := M) (P := P)).symm
  let B := (weakDualPairing ℂ σ(M, P)).flip
  have h : ∀ x y, pairing (e x) y = B x y := by
    intro x y
    change y (toUltraweakₗ (e x)) = y x
    rw [show toUltraweakₗ (e x) = x by
      change toUltraweakEquiv (e x) = x
      exact (toUltraweakEquiv (M := M) (P := P)).apply_symm_apply x]
  have hc := (continuous_ofMackey pairing).comp <|
    (Mackey.congrLeft B e h).continuous.comp (MackeySpace.mackeyCLE ℂ σ(M, P)).continuous
  convert hc using 1
  funext x
  change fromMackeyₗ x =
    ofMackey (Mackey.congrLeft B e h (MackeySpace.mackeyCLE ℂ σ(M, P) x))
  rw [Mackey.congrLeft_apply, ofMackey_toMackey]
  rfl

/-- The canonical continuous linear map from the Mackey topology to the strong topology. -/
noncomputable def fromMackeyL [CompleteSpace P] :
    MackeySpace ℂ σ(M, P) →L[ℂ] s(M, P) :=
  ⟨fromMackeyₗ, continuous_fromMackeyₗ⟩

@[simp]
lemma ofStrong_fromMackeyL [CompleteSpace P] (x : MackeySpace ℂ σ(M, P)) :
    ofStrong (fromMackeyL x) = ofUltraweak (ofMackeySpace ℂ σ(M, P) x) := rfl

@[simp]
lemma toUltraweakL_fromMackeyL [CompleteSpace P] (x : MackeySpace ℂ σ(M, P)) :
    toUltraweakL (fromMackeyL x) = ofMackeySpace ℂ σ(M, P) x :=
  rfl

end Strong

end

end Ultraweak
