module

public import LeanOA.Ultraweak.KaplanskyDensity

/-!
# Restricting the test space of an ultraweak topology

A submodule of a specified predual induces a weaker test topology on the dual algebra.  This file
exposes the canonical continuous identity from the full ultraweak topology to that restricted
weak topology, together with its closed-set consequence.  The underlying general restriction map
for `WeakBilin` lives in the Mathlib-shaped weak-bilinear module.
-/

@[expose] public section

open scoped Ultraweak

noncomputable section

namespace Ultraweak

variable {M P : Type*} [NormedAddCommGroup M] [NormedSpace ℂ M]
  [NormedAddCommGroup P] [NormedSpace ℂ P] [Predual ℂ M P]

/-- The canonical continuous linear identity from the full specified-predual topology to the weak
topology induced by a chosen predual test submodule. -/
def toTestWeakL (V : Submodule ℂ P) :
    σ(M, P) →L[ℂ] WeakBilin (testPairing (M := M) V) :=
  WeakBilin.restrictRightL
    (topDualPairing ℂ P ∘ₗ
      (Predual.equivDual (M := M) |>.toLinearEquiv.toLinearMap)) V.subtype

lemma toTestWeakL_apply (V : Submodule ℂ P) (x : σ(M, P)) :
    WeakBilin.linearEquiv ℂ (testPairing (M := M) V) (toTestWeakL V x) =
      ofUltraweak x :=
  rfl

/-- If one predual test submodule is contained in another, the identity from the weak topology
generated by the larger test space to that generated by the smaller one is continuous. -/
def testWeakRestrictionL {V W : Submodule ℂ P} (h : V ≤ W) :
    WeakBilin (testPairing (M := M) W) →L[ℂ]
      WeakBilin (testPairing (M := M) V) := by
  let i : V →ₗ[ℂ] W := Submodule.inclusion h
  have hpair :
      (((testPairing (M := M) W).flip.comp i).flip) =
        testPairing (M := M) V := by
    ext x p
    rfl
  rw [← hpair]
  exact WeakBilin.restrictRightL (testPairing (M := M) W) i

lemma testWeakRestrictionL_apply {V W : Submodule ℂ P} (h : V ≤ W)
    (x : WeakBilin (testPairing (M := M) W)) :
    WeakBilin.linearEquiv ℂ (testPairing (M := M) V) (testWeakRestrictionL h x) =
      WeakBilin.linearEquiv ℂ (testPairing (M := M) W) x :=
  rfl

/-- Closedness for a smaller family of predual tests implies closedness for a larger family. -/
theorem isClosed_testWeak_of_le {V W : Submodule ℂ P} (h : V ≤ W)
    (S : Set M)
    (hS : IsClosed ((WeakBilin.linearEquiv ℂ (testPairing (M := M) V)) ⁻¹' S)) :
    IsClosed ((WeakBilin.linearEquiv ℂ (testPairing (M := M) W)) ⁻¹' S) := by
  convert hS.preimage (testWeakRestrictionL h).continuous using 1
  ext x
  rfl

/-- A set closed for a restricted predual-test topology is closed for the full specified-predual
topology. -/
theorem isClosed_ultraweak_of_isClosed_testWeak (V : Submodule ℂ P) (S : Set M)
    (hS : IsClosed
      ((WeakBilin.linearEquiv ℂ (testPairing (M := M) V)) ⁻¹' S)) :
    IsClosed (ofUltraweak ⁻¹' S : Set σ(M, P)) := by
  convert hS.preimage (toTestWeakL (M := M) (P := P) V).continuous using 1
  ext x
  change ofUltraweak x ∈ S ↔
    WeakBilin.linearEquiv ℂ (testPairing (M := M) V) (toTestWeakL V x) ∈ S
  simp only [toTestWeakL_apply]

/-- A transported test-weak closure is ultraweakly closed in the original specified predual. -/
theorem isClosed_ultraweak_testWeakClosure (V : Submodule ℂ P) (S : Set M) :
    IsClosed (ofUltraweak ⁻¹' testWeakClosure (M := M) V S : Set σ(M, P)) :=
  isClosed_ultraweak_of_isClosed_testWeak V _
    (isClosed_preimage_testWeakClosure V S)

/-- A transported test-weak closure is norm closed in the original ambient algebra. -/
theorem isClosed_testWeakClosure (V : Submodule ℂ P) (S : Set M) :
    IsClosed (testWeakClosure (M := M) V S) := by
  have h := (isClosed_ultraweak_testWeakClosure (M := M) (P := P) V S).preimage
    (continuous_toUltraweak (𝕜 := ℂ) (M := M) (P := P))
  simpa only [Set.preimage_preimage, ofUltraweak_toUltraweak, Set.preimage_id'] using h

end Ultraweak
