module

public import Mathlib.RingTheory.Idempotents
public import Mathlib.Tactic.NoncommRing

@[expose] public section

/-- The four-corner, or Peirce, decomposition associated to an element of a ring. The identity
itself does not require the element to be idempotent. -/
lemma peirce_decomposition {R : Type*} [Ring R] (p a : R) :
    a = p * a * p + p * a * (1 - p) +
      (1 - p) * a * p + (1 - p) * a * (1 - p) := by
  noncomm_ring

namespace Ideal

variable {R : Type*} [Semiring R]

/-- The principal left ideal generated by an element is the range of right multiplication by
that element. -/
lemma range_mulRight (p : R) :
    LinearMap.range (LinearMap.mulRight R p) = Ideal.span {p} := by
  ext x
  rw [LinearMap.mem_range, Ideal.mem_span_singleton']
  exact exists_congr fun a ↦ by rw [LinearMap.mulRight_apply]

end Ideal

namespace IsIdempotentElem

variable {R : Type*} [Semiring R] {p q : R}

/-- Inclusion between principal left ideals generated by idempotents is characterized by right
absorption. Only the generator of the larger ideal needs to be idempotent. -/
lemma span_singleton_le_span_singleton_iff (hq : IsIdempotentElem q) :
    Ideal.span {p} ≤ Ideal.span {q} ↔ p * q = p := by
  rw [Ideal.span_singleton_le_iff_mem, Ideal.mem_span_singleton']
  constructor
  · rintro ⟨a, rfl⟩
    rw [mul_assoc, hq.eq]
  · exact fun h ↦ ⟨p, h⟩

end IsIdempotentElem
