module

public import LeanOA.LocallyConvexNhdsBasis
public import LeanOA.Lp.lpSpace
public import LeanOA.Mathlib.Analysis.LocallyConvex.WithSeminorms
public import Mathlib.Topology.Algebra.Module.Spaces.PointwiseConvergenceCLM

/-!
# Square-summable convergence of continuous linear maps

This file equips continuous linear maps with the topology generated by the seminorms

`T ↦ ‖(T (ξ n))ₙ‖_{ℓ²}`

for square-summable vector families `ξ`. On bounded operators on a Hilbert space this is the
ultrastrong operator topology, called the strongest operator topology by Sakai.

The coordinatewise application map and its seminorm are stated for arbitrary index types and
normed spaces. The topology-bearing synonym uses `ℕ`-indexed families, matching Sakai's
definition. No Hilbert-space structure is needed in this file.
-/

@[expose] public section

open scoped ComplexOrder ENNReal NNReal lp

noncomputable section

namespace lp

variable {ι E : Type*} [NormedAddCommGroup E]

/-- The squared norms of an `ℓ²` family are summable. -/
theorem summable_norm_sq (ξ : ℓ²(ι, E)) : Summable (fun i ↦ ‖ξ i‖ ^ 2) := by
  simpa only [ENNReal.toReal_ofNat, Real.rpow_two] using
    (lp.memℓp ξ).summable (by norm_num : 0 < (2 : ℝ≥0∞).toReal)

end lp

namespace ContinuousLinearMap

variable {ι 𝕜 E F : Type*} [NontriviallyNormedField 𝕜]
  [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  [NormedAddCommGroup F] [NormedSpace 𝕜 F]

/-- Apply a continuous linear map coordinatewise to an `ℓ²` family, linearly in the map. -/
def applyLpₗ (ξ : ℓ²(ι, E)) : (E →L[𝕜] F) →ₗ[𝕜] ℓ²(ι, F) where
  toFun T := lp.mapCLM 2 (fun _ ↦ T) (norm_nonneg T) (fun _ ↦ le_rfl) ξ
  map_add' T S := by ext i; simp
  map_smul' c T := by ext i; simp

@[simp]
lemma applyLpₗ_apply (ξ : ℓ²(ι, E)) (T : E →L[𝕜] F) (i : ι) :
    applyLpₗ ξ T i = T (ξ i) :=
  rfl

/-- The seminorm obtained by applying an operator to a square-summable vector family. -/
def squareSummableSeminorm (ξ : ℓ²(ι, E)) : Seminorm 𝕜 (E →L[𝕜] F) :=
  (normSeminorm 𝕜 ℓ²(ι, F)).comp (applyLpₗ ξ)

@[simp]
lemma squareSummableSeminorm_apply (ξ : ℓ²(ι, E)) (T : E →L[𝕜] F) :
    squareSummableSeminorm ξ T = ‖applyLpₗ ξ T‖ :=
  rfl

/-- The square-summable application seminorm in Sakai's explicit square-root formula. -/
theorem squareSummableSeminorm_apply_eq_sqrt_tsum
    (ξ : ℓ²(ι, E)) (T : E →L[𝕜] F) :
    squareSummableSeminorm ξ T = √(∑' i, ‖T (ξ i)‖ ^ 2) := by
  rw [squareSummableSeminorm_apply, lp.norm_eq_tsum_rpow
    (by norm_num : 0 < (2 : ℝ≥0∞).toReal)]
  simp only [applyLpₗ_apply, ENNReal.toReal_ofNat, Real.rpow_two]
  norm_num [Real.sqrt_eq_rpow]

end ContinuousLinearMap

/-- Continuous linear maps equipped with convergence on all `ℕ`-indexed square-summable vector
families. For Hilbert-space endomorphisms this is the ultrastrong operator topology. -/
@[nolint unusedArguments]
def SquareSummableConvergenceCLM (𝕜 E F : Type*) [NontriviallyNormedField 𝕜]
    [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    [NormedAddCommGroup F] [NormedSpace 𝕜 F] :=
  E →L[𝕜] F
deriving AddCommGroup, Module 𝕜

@[inherit_doc]
notation:25 E " →USOT[" 𝕜 "] " F => SquareSummableConvergenceCLM 𝕜 E F

namespace SquareSummableConvergenceCLM

variable {𝕜 E F : Type*} [NontriviallyNormedField 𝕜]
  [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  [NormedAddCommGroup F] [NormedSpace 𝕜 F]

/-- The underlying continuous linear map. -/
def toCLM (T : E →USOT[𝕜] F) : E →L[𝕜] F := T

/-- A continuous linear map regarded with the square-summable convergence topology. -/
def ofCLM (T : E →L[𝕜] F) : E →USOT[𝕜] F := T

/-- The algebraic identification with the space of continuous linear maps. -/
def linearEquiv : (E →USOT[𝕜] F) ≃ₗ[𝕜] (E →L[𝕜] F) :=
  LinearEquiv.refl 𝕜 _

@[simp]
lemma toCLM_ofCLM (T : E →L[𝕜] F) : toCLM (ofCLM T) = T := rfl

@[simp]
lemma ofCLM_toCLM (T : E →USOT[𝕜] F) : ofCLM (toCLM T) = T := rfl

/-- The defining seminorm indexed by a square-summable vector family. -/
def seminorm (ξ : ℓ²(ℕ, E)) : Seminorm 𝕜 (E →USOT[𝕜] F) :=
  (ContinuousLinearMap.squareSummableSeminorm ξ).comp linearEquiv.toLinearMap

@[simp]
lemma seminorm_apply (ξ : ℓ²(ℕ, E)) (T : E →USOT[𝕜] F) :
    seminorm ξ T = ‖ContinuousLinearMap.applyLpₗ ξ T.toCLM‖ :=
  rfl

/-- The family of seminorms defining square-summable convergence. -/
def seminormFamily : SeminormFamily 𝕜 (E →USOT[𝕜] F) ℓ²(ℕ, E) :=
  seminorm

noncomputable instance : TopologicalSpace (E →USOT[𝕜] F) :=
  seminormFamily.moduleFilterBasis.topology

/-- The topology is induced by its defining square-summable application seminorms. -/
lemma withSeminorms :
    WithSeminorms (seminormFamily (𝕜 := 𝕜) (E := E) (F := F)) :=
  ⟨rfl⟩

instance : IsTopologicalAddGroup (E →USOT[𝕜] F) :=
  withSeminorms.topologicalAddGroup

instance : ContinuousSMul 𝕜 (E →USOT[𝕜] F) :=
  withSeminorms.continuousSMul

section RCLike

variable {𝕜 : Type*} [RCLike 𝕜]
  {E F : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  [NormedAddCommGroup F] [NormedSpace 𝕜 F]

instance : LocallyConvexSpace 𝕜 (E →USOT[𝕜] F) :=
  let _ : Module ℝ (E →USOT[𝕜] F) := RestrictScalars.module ℝ 𝕜 (E →USOT[𝕜] F)
  let _ : IsScalarTower ℝ 𝕜 (E →USOT[𝕜] F) :=
    RestrictScalars.isScalarTower ℝ 𝕜 (E →USOT[𝕜] F)
  .to_rclike 𝕜 (E →USOT[𝕜] F) withSeminorms.toLocallyConvexSpace

end RCLike

/-- The algebraic identity from square-summable convergence to pointwise convergence. -/
def toPointwiseConvergenceCLMₗ : (E →USOT[𝕜] F) →ₗ[𝕜] (E →Lₚₜ[𝕜] F) where
  toFun T := T.toCLM
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

@[simp]
lemma toPointwiseConvergenceCLMₗ_apply (T : E →USOT[𝕜] F) (x : E) :
    toPointwiseConvergenceCLMₗ T x = T.toCLM x :=
  rfl

/-- Square-summable convergence is finer than pointwise convergence. -/
theorem continuous_toPointwiseConvergenceCLMₗ :
    Continuous (toPointwiseConvergenceCLMₗ : (E →USOT[𝕜] F) → (E →Lₚₜ[𝕜] F)) := by
  apply PointwiseConvergenceCLM.continuous_of_continuous_eval
  intro x
  let evalₗ : (E →USOT[𝕜] F) →ₗ[𝕜] F :=
    { toFun := fun T ↦ T.toCLM x
      map_add' := fun _ _ ↦ rfl
      map_smul' := fun _ _ ↦ rfl }
  change Continuous evalₗ
  apply withSeminorms.continuous_normedSpace_rng F evalₗ
  let ξ : ℓ²(ℕ, E) := lp.single 2 0 x
  refine ⟨{ξ}, 1, fun T ↦ ?_⟩
  simp only [Seminorm.comp_apply, one_smul, Finset.sup_singleton, seminormFamily]
  change ‖T.toCLM x‖ ≤ ‖ContinuousLinearMap.applyLpₗ ξ T.toCLM‖
  have happly : ContinuousLinearMap.applyLpₗ ξ T.toCLM = lp.single 2 0 (T.toCLM x) := by
    classical
    apply lp.ext
    funext i
    by_cases hi : i = 0
    · subst i
      simp [ξ]
    · simp [ξ, lp.single_apply, hi]
  rw [happly, lp.norm_single (by norm_num : (0 : ℝ≥0∞) < 2)]

/-- The continuous identity from square-summable convergence to pointwise convergence. -/
def toPointwiseConvergenceCLM : (E →USOT[𝕜] F) →L[𝕜] (E →Lₚₜ[𝕜] F) :=
  ⟨toPointwiseConvergenceCLMₗ, continuous_toPointwiseConvergenceCLMₗ⟩

@[simp]
lemma toPointwiseConvergenceCLM_apply (T : E →USOT[𝕜] F) (x : E) :
    toPointwiseConvergenceCLM T x = T.toCLM x :=
  rfl

instance : T2Space (E →USOT[𝕜] F) :=
  T2Space.of_injective_continuous
    (f := toPointwiseConvergenceCLM (𝕜 := 𝕜) (E := E) (F := F))
    (fun S T h ↦ by
      apply linearEquiv.injective
      apply ContinuousLinearMap.ext
      intro x
      exact congrArg (fun U : E →Lₚₜ[𝕜] F ↦ U x) h)
    toPointwiseConvergenceCLM.continuous

/-- A pointwise-closed operator set is closed for square-summable convergence. -/
theorem isClosed_squareSummable_of_isClosed_pointwise (S : Set (E →L[𝕜] F))
    (hS : IsClosed {T : E →Lₚₜ[𝕜] F | (T : E →L[𝕜] F) ∈ S}) :
    IsClosed {T : E →USOT[𝕜] F | T.toCLM ∈ S} := by
  change IsClosed (toPointwiseConvergenceCLM ⁻¹'
    {T : E →Lₚₜ[𝕜] F | (T : E →L[𝕜] F) ∈ S})
  exact hS.preimage toPointwiseConvergenceCLM.continuous

end SquareSummableConvergenceCLM
