module

public import LeanOA.Mathlib.RingTheory.Idempotents
public import Mathlib.Analysis.CStarAlgebra.Projection

@[expose] public section

namespace IsStarProjection

variable {A : Type*} {p q : A}

/-- Passing to the multiplicative opposite preserves star projections. -/
@[simp]
lemma _root_.isStarProjection_op_iff [Mul A] [Star A] :
    IsStarProjection (MulOpposite.op p) ↔ IsStarProjection p := by
  rw [isStarProjection_iff', isStarProjection_iff']
  constructor
  · rintro ⟨hid, hstar⟩
    exact ⟨MulOpposite.op_injective (by simpa only [MulOpposite.op_mul] using hid),
      MulOpposite.op_injective (by simpa only [MulOpposite.op_star] using hstar)⟩
  · rintro ⟨hid, hstar⟩
    exact ⟨by simpa only [← MulOpposite.op_mul] using congr_arg MulOpposite.op hid,
      by simpa only [← MulOpposite.op_star] using congr_arg MulOpposite.op hstar⟩

/-- Passing out of the multiplicative opposite preserves star projections. -/
@[simp]
lemma _root_.isStarProjection_unop_iff [Mul A] [Star A] {p : Aᵐᵒᵖ} :
    IsStarProjection p.unop ↔ IsStarProjection p := by
  simpa only [MulOpposite.op_unop] using
    (isStarProjection_op_iff (p := p.unop)).symm

/-- Inclusion between principal left ideals generated by projections agrees with the projection
order. -/
lemma span_singleton_le_span_singleton_iff [CStarAlgebra A] [PartialOrder A]
    [StarOrderedRing A] (hp : IsStarProjection p) (hq : IsStarProjection q) :
    Ideal.span {p} ≤ Ideal.span {q} ↔ p ≤ q :=
  hq.isIdempotentElem.span_singleton_le_span_singleton_iff.trans
    (hp.le_iff_mul_eq_left hq).symm

/-- Inclusion between ranges of right multiplication by projections agrees with the projection
order. -/
lemma range_mulRight_le_range_mulRight_iff [CStarAlgebra A] [PartialOrder A]
    [StarOrderedRing A] (hp : IsStarProjection p) (hq : IsStarProjection q) :
    LinearMap.range (LinearMap.mulRight A p) ≤
      LinearMap.range (LinearMap.mulRight A q) ↔ p ≤ q := by
  rw [Ideal.range_mulRight, Ideal.range_mulRight,
    hp.span_singleton_le_span_singleton_iff hq]

/-- A projection is determined by the principal left ideal that it generates. -/
lemma eq_of_span_singleton_eq [Semiring A] [StarMul A]
    (hp : IsStarProjection p) (hq : IsStarProjection q)
    (h : Ideal.span {p} = Ideal.span {q}) : p = q := by
  have hpq := hq.isIdempotentElem.span_singleton_le_span_singleton_iff.mp h.le
  have hqp := hp.isIdempotentElem.span_singleton_le_span_singleton_iff.mp h.ge
  calc
    p = star (p * q) := by rw [hpq, hp.isSelfAdjoint.star_eq]
    _ = q * p := by rw [star_mul, hp.isSelfAdjoint.star_eq, hq.isSelfAdjoint.star_eq]
    _ = q := hqp

end IsStarProjection
