module

public import LeanOA.Mathlib.RingTheory.Idempotents
public import Mathlib.Analysis.CStarAlgebra.Projection

import LeanOA.Mathlib.Analysis.CStarAlgebra.Basic
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Basic
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Projection

@[expose] public section

namespace IsStarProjection

variable {A : Type*} {p q : A}

/-- If `star u * u` is a projection, then `u` is fixed by its initial projection. -/
lemma mul_star_mul_self [NonUnitalCStarAlgebra A] {u : A}
    (hu : IsStarProjection (star u * u)) : u * star u * u = u := by
  rw [mul_assoc]
  exact hu.isSelfAdjoint.mul_eq_self_of_star_mul_self_mul_eq hu.isIdempotentElem.eq

/-- If `star u * u` is a projection, then it fixes `u` on the right. This is the
right-associated form of `IsStarProjection.mul_star_mul_self`. -/
lemma mul_star_mul_self_assoc [NonUnitalCStarAlgebra A] {u : A}
    (hu : IsStarProjection (star u * u)) : u * (star u * u) = u := by
  rw [← mul_assoc]
  exact hu.mul_star_mul_self

/-- If `star u * u` is a projection, then so is the final projection `u * star u`. -/
lemma mul_star_self [NonUnitalCStarAlgebra A] {u : A}
    (hu : IsStarProjection (star u * u)) : IsStarProjection (u * star u) :=
  ⟨isIdempotentElem_star_mul_self_iff_isIdempotentElem_self_mul_star.mp hu.isIdempotentElem,
    .mul_star_self u⟩

/-- Passing to the multiplicative opposite preserves star projections. -/
@[simp]
lemma _root_.isStarProjection_op_iff [Mul A] [Star A] :
    IsStarProjection (MulOpposite.op p) ↔ IsStarProjection p := by
  rw [isStarProjection_iff', isStarProjection_iff']
  constructor
  · rintro ⟨hid, hstar⟩
    exact ⟨MulOpposite.op_injective (by simpa only [MulOpposite.op_mul] using hid),
      MulOpposite.op_injective (by simpa only [MulOpposite.op_star] using hstar)⟩
  · rintro ⟨hid, hstar⟩
    exact ⟨by simpa only [← MulOpposite.op_mul] using congr_arg MulOpposite.op hid,
      by simpa only [← MulOpposite.op_star] using congr_arg MulOpposite.op hstar⟩

/-- Passing out of the multiplicative opposite preserves star projections. -/
@[simp]
lemma _root_.isStarProjection_unop_iff [Mul A] [Star A] {p : Aᵐᵒᵖ} :
    IsStarProjection p.unop ↔ IsStarProjection p := by
  simpa only [MulOpposite.op_unop] using
    (isStarProjection_op_iff (p := p.unop)).symm

/-- Inclusion between principal left ideals generated by projections agrees with the projection
order. -/
lemma span_singleton_le_span_singleton_iff [CStarAlgebra A] [PartialOrder A]
    [StarOrderedRing A] (hp : IsStarProjection p) (hq : IsStarProjection q) :
    Ideal.span {p} ≤ Ideal.span {q} ↔ p ≤ q :=
  hq.isIdempotentElem.span_singleton_le_span_singleton_iff.trans
    (hp.le_iff_mul_eq_left hq).symm

/-- Inclusion between ranges of right multiplication by projections agrees with the projection
order. -/
lemma range_mulRight_le_range_mulRight_iff [CStarAlgebra A] [PartialOrder A]
    [StarOrderedRing A] (hp : IsStarProjection p) (hq : IsStarProjection q) :
    LinearMap.range (LinearMap.mulRight A p) ≤
      LinearMap.range (LinearMap.mulRight A q) ↔ p ≤ q := by
  rw [Ideal.range_mulRight, Ideal.range_mulRight,
    hp.span_singleton_le_span_singleton_iff hq]

/-- Two projections are orthogonal exactly when the first lies below the complement of the
second. -/
lemma mul_eq_zero_iff_le_one_sub [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
    (hp : IsStarProjection p) (hq : IsStarProjection q) :
    p * q = 0 ↔ p ≤ 1 - q := by
  rw [hp.le_iff_mul_eq_left hq.one_sub, mul_sub, mul_one, sub_eq_self]

/-- Differences of nested star projections supported on disjoint order intervals are
orthogonal. -/
lemma sub_mul_sub_eq_zero_of_le [NonUnitalCStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
    {q r s : A} (hp : IsStarProjection p) (hq : IsStarProjection q)
    (hr : IsStarProjection r) (hs : IsStarProjection s)
    (hpq : p ≤ q) (hqr : q ≤ r) (hrs : r ≤ s) :
    (q - p) * (s - r) = 0 := by
  have hmul {x y : A} (hx : IsStarProjection x) (hy : IsStarProjection y)
      (hxy : x ≤ y) : x * y = x :=
    (hx.le_iff_mul_eq_left hy).mp hxy
  rw [mul_sub, sub_mul, sub_mul, hmul hq hs (hqr.trans hrs), hmul hq hr hqr,
    hmul hp hs (hpq.trans (hqr.trans hrs)), hmul hp hr (hpq.trans hqr), sub_self]

/-- If a projection acts as the identity on a positive element, then it acts as the identity on
every smaller positive element. -/
lemma mul_eq_self_of_nonneg_of_le_of_mul_eq_self [CStarAlgebra A] [PartialOrder A]
    [StarOrderedRing A] {a b : A} (hp : IsStarProjection p) (ha : 0 ≤ a) (hab : a ≤ b)
    (hpb : p * b = b) : p * a = a := by
  have hqb : (1 - p) * b * (1 - p) = 0 := by
    rw [sub_mul, one_mul, hpb, sub_self, zero_mul]
  have hqa_nonneg : 0 ≤ (1 - p) * a * (1 - p) := by
    simpa only [hp.one_sub.isSelfAdjoint.star_eq] using
      star_left_conjugate_nonneg ha (1 - p)
  have hqa_le : (1 - p) * a * (1 - p) ≤ (1 - p) * b * (1 - p) := by
    simpa only [hp.one_sub.isSelfAdjoint.star_eq] using
      star_left_conjugate_le_conjugate hab (1 - p)
  have hqa : (1 - p) * a * (1 - p) = 0 :=
    le_antisymm (hqa_le.trans_eq hqb) hqa_nonneg
  have hsqrt_self : IsSelfAdjoint (CFC.sqrt a) :=
    IsSelfAdjoint.of_nonneg (CFC.sqrt_nonneg a)
  have hsqrt : CFC.sqrt a * (1 - p) = 0 := by
    rw [← CStarRing.star_mul_self_eq_zero_iff]
    calc
      star (CFC.sqrt a * (1 - p)) * (CFC.sqrt a * (1 - p)) =
          (1 - p) * (CFC.sqrt a * CFC.sqrt a) * (1 - p) := by
        rw [star_mul, hp.one_sub.isSelfAdjoint.star_eq, hsqrt_self.star_eq]
        noncomm_ring
      _ = (1 - p) * a * (1 - p) := by rw [CFC.sqrt_mul_sqrt_self a ha]
      _ = 0 := hqa
  have hqsqrt : (1 - p) * CFC.sqrt a = 0 := by
    simpa only [star_mul, hp.one_sub.isSelfAdjoint.star_eq, hsqrt_self.star_eq, star_zero] using
      congr_arg star hsqrt
  have hqamul : (1 - p) * a = 0 := by
    rw [← CFC.sqrt_mul_sqrt_self a ha, ← mul_assoc, hqsqrt, zero_mul]
  rw [sub_mul, one_mul, sub_eq_zero] at hqamul
  exact hqamul.symm

/-- A projection is determined by the principal left ideal that it generates. -/
lemma eq_of_span_singleton_eq [Semiring A] [StarMul A]
    (hp : IsStarProjection p) (hq : IsStarProjection q)
    (h : Ideal.span {p} = Ideal.span {q}) : p = q := by
  have hpq := hq.isIdempotentElem.span_singleton_le_span_singleton_iff.mp h.le
  have hqp := hp.isIdempotentElem.span_singleton_le_span_singleton_iff.mp h.ge
  calc
    p = star (p * q) := by rw [hpq, hp.isSelfAdjoint.star_eq]
    _ = q * p := by rw [star_mul, hp.isSelfAdjoint.star_eq, hq.isSelfAdjoint.star_eq]
    _ = q := hqp

end IsStarProjection
