module

public import LeanOA.Mathlib.Topology.ContinuousMap.ContinuousMapZero
public import Mathlib.Analysis.CStarAlgebra.Hom
public import Mathlib.Analysis.CStarAlgebra.PositiveLinearMap
public import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Basic
public import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Order
public import Mathlib.Analysis.SpecialFunctions.ContinuousFunctionalCalculus.Abs
public import Mathlib.Analysis.RCLike.ContinuousMap
public import Mathlib.Topology.ContinuousMap.LocallyConstant
public import Mathlib.Topology.ExtremallyDisconnected

@[expose] public section

/-!
# C-star algebras with dense finite-spectrum self-adjoint elements

This file develops the finite-spectrum approximation property usually called real rank zero. It
shows that finite-spectrum self-adjoint elements lie in the real span of projections, and that
nonnegative finite-spectrum elements lie in the cone generated by projections. The corresponding
span and cone density results are then transported through star-algebra equivalences.
-/

variable {A Y 𝕜 : Type*} [RCLike 𝕜] [TopologicalSpace A] [TopologicalSpace Y]

namespace ContinuousMapZero

/-- The function supported at one point with value one is a star projection. -/
lemma isStarProjection_single_one [DiscreteTopology A] [Zero A] [DecidableEq A] (i : A) :
    IsStarProjection (single i (1 : 𝕜)) := by
  constructor <;> ext j <;> simp only [single_def]
  all_goals split_ifs <;> simp_all [Pi.single_apply]

@[simp] lemma mem_span_isStarProjection_of_finite [DiscreteTopology A] [Finite A] [Zero A]
    (f : C(A, 𝕜)₀) : f ∈ Submodule.span 𝕜 {p : C(A, 𝕜)₀ | IsStarProjection p} := by
  letI := Fintype.ofFinite A
  classical
  rw [show f = ∑ i, f i • single i 1 by aesop (add simp [Pi.single_apply])]
  exact Submodule.sum_mem _ fun i _ ↦ Submodule.smul_mem _ _ <| Submodule.mem_span_of_mem
    (isStarProjection_single_one (𝕜 := 𝕜) i)

/-- A nonnegative function on a finite discrete pointed space belongs to the cone generated by
star projections. -/
lemma mem_hull_isStarProjection_of_finite [DiscreteTopology A] [Finite A] [Zero A]
    (f : C(A, ℝ)₀) (hf : 0 ≤ f) :
    f ∈ ConvexCone.hull ℝ {p : C(A, ℝ)₀ | IsStarProjection p} := by
  letI := Fintype.ofFinite A
  classical
  rw [show f = ∑ i, f i • single i 1 by aesop (add simp [Pi.single_apply])]
  let C := ConvexCone.hull ℝ {p : C(A, ℝ)₀ | IsStarProjection p}
  have hz : (0 : C(A, ℝ)₀) ∈ C := ConvexCone.subset_hull (by simp)
  have hi (i : A) : f i • single i 1 ∈ C := by
    obtain (hi | hi) := (hf i).eq_or_lt
    · change (0 : ℝ) = f i at hi
      rw [← hi]
      have hzero : (0 : ℝ) • single i (1 : ℝ) = 0 := by ext; simp
      rwa [hzero]
    · exact C.smul_mem hi <| ConvexCone.subset_hull (isStarProjection_single_one i)
  change ∑ i, f i • single i 1 ∈ C
  induction (Finset.univ : Finset A) using Finset.induction_on with
  | empty => simpa using hz
  | @insert i s his ih =>
    rw [Finset.sum_insert his]
    exact C.add_mem (hi i) ih

end ContinuousMapZero

variable (A) in
/-- A C⋆-algebra has **real rank zero** if its self-adjoint elements can be approximated by
self-adjoint elements with finite quasispectrum. -/
@[mk_iff]
class CStarAlgebra.IsRealRankZero [NonUnitalRing A] [Module ℝ A] [Star A] : Prop where
  finite_quasispectrum_dense :
    {x : A | IsSelfAdjoint x} ⊆ closure {x : A | IsSelfAdjoint x ∧ (quasispectrum ℝ x).Finite}

theorem CStarAlgebra.isRealRankZero_iff_spectrum [Ring A] [Algebra ℝ A] [Star A] :
    CStarAlgebra.IsRealRankZero A ↔
      {x : A | IsSelfAdjoint x} ⊆ closure {x | IsSelfAdjoint x ∧ (spectrum ℝ x).Finite} := by
  simp [quasispectrum_eq_spectrum_union_zero, CStarAlgebra.isRealRankZero_iff]

/-- Real rank zero transfers backwards across a complex star-algebra equivalence. -/
theorem CStarAlgebra.IsRealRankZero.of_starAlgEquiv
    {A B : Type*} [NonUnitalCStarAlgebra A] [NonUnitalCStarAlgebra B]
    [CStarAlgebra.IsRealRankZero B] (e : A ≃⋆ₐ[ℂ] B) :
    CStarAlgebra.IsRealRankZero A := by
  refine ⟨fun x hx ↦ ?_⟩
  have hx' : e x ∈ closure {y : B | IsSelfAdjoint y ∧ (quasispectrum ℝ y).Finite} :=
    CStarAlgebra.IsRealRankZero.finite_quasispectrum_dense (A := B) (hx.map e)
  have hmap : Set.MapsTo e.symm
      {y : B | IsSelfAdjoint y ∧ (quasispectrum ℝ y).Finite}
      {y : A | IsSelfAdjoint y ∧ (quasispectrum ℝ y).Finite} := fun y hy ↦
    ⟨hy.1.map e.symm, hy.2.subset <|
      NonUnitalAlgHom.quasispectrum_apply_subset' (R := ℝ) ℂ e.symm y⟩
  simpa using map_mem_closure (StarAlgEquiv.isometry e.symm).continuous hx' hmap

instance [NonUnitalRing A] [Module ℝ A] [StarRing A] [IsScalarTower ℝ A A] [SMulCommClass ℝ A A]
    [NonUnitalContinuousFunctionalCalculus ℝ A IsSelfAdjoint] [Subsingleton A] :
    CStarAlgebra.IsRealRankZero A where
  finite_quasispectrum_dense := by simp [Subsingleton.eq_zero, CFC.quasispectrum_zero_eq]

instance [Ring A] [Algebra ℝ A] [Star A] [Subsingleton A] :
    CStarAlgebra.IsRealRankZero A where
  finite_quasispectrum_dense := by simp [quasispectrum_eq_spectrum_union_zero]

open ContinuousMap LocallyConstant in
instance [TotallySeparatedSpace A] [CompactSpace A] : CStarAlgebra.IsRealRankZero C(A, 𝕜) :=
  CStarAlgebra.isRealRankZero_iff_spectrum.mpr fun x hx ↦ by
    obtain ⟨y, rfl⟩ := range_realToRCLike_eq_isSelfAdjoint A 𝕜 ▸ hx
    have : realToRCLike 𝕜 '' {x : C(A, ℝ) | IsSelfAdjoint x ∧ (spectrum ℝ x).Finite} ⊆
      {x | IsSelfAdjoint x ∧ (spectrum ℝ x).Finite} := by aesop
    refine closure_mono this
      (mem_closure_image (isometry_realToRCLike A 𝕜).continuous.continuousAt ?_)
    have : .range toContinuousMap ⊆ {x : C(A, ℝ) | IsSelfAdjoint x ∧ (spectrum ℝ x).Finite} :=
      fun _ ⟨f, hf⟩ ↦ by simp [← hf, spectrum_eq_range, range_finite, IsSelfAdjoint]
    apply closure_mono this
    simpa using! Subalgebra.ext_iff.mp (subalgebra_topologicalClosure_eq_top_of_separatesPoints _
      (separatesPoints_range_toContinuousMapAlgHom ℝ)) y

variable [NonUnitalRing A] [StarRing A] [Module ℝ A] [IsScalarTower ℝ A A] [SMulCommClass ℝ A A]
  [NonUnitalContinuousFunctionalCalculus ℝ A IsSelfAdjoint]

/-- A self-adjoint element with finite quasispectrum in a non-unital C⋆-algebra is in the span of
star projections. -/
lemma IsSelfAdjoint.mem_span_isStarProjection_of_finite_quasispectrum {x : A}
    (hx : IsSelfAdjoint x) (h : (quasispectrum ℝ x).Finite) :
    x ∈ Submodule.span ℝ {p : A | IsStarProjection p} := by
  have : Finite (quasispectrum ℝ x) := Set.finite_coe_iff.mpr h
  refine Submodule.mem_span.mpr fun p hp ↦ ?_
  simpa [cfcₙHom_id] using Submodule.mem_span.mp
    (ContinuousMapZero.id (quasispectrum ℝ x)).mem_span_isStarProjection_of_finite
    (.comap (cfcₙHom (R := ℝ) hx : _ →ₗ[ℝ] A) p)
    (by simp_all [Set.subset_def, IsStarProjection.map])

/-- A nonnegative self-adjoint element with finite quasispectrum belongs to the cone generated by
star projections. -/
lemma IsSelfAdjoint.mem_hull_isStarProjection_of_nonneg_of_finite_quasispectrum
    [PartialOrder A] [NonnegSpectrumClass ℝ A] {x : A} (hx : IsSelfAdjoint x) (hx0 : 0 ≤ x)
    (h : (quasispectrum ℝ x).Finite) :
    x ∈ ConvexCone.hull ℝ {p : A | IsStarProjection p} := by
  have : Finite (quasispectrum ℝ x) := Set.finite_coe_iff.mpr h
  let C := ConvexCone.hull ℝ {p : A | IsStarProjection p}
  have hmap : ConvexCone.hull ℝ
      {p : ContinuousMapZero (quasispectrum ℝ x) ℝ | IsStarProjection p} ≤
      C.comap (cfcₙHom (R := ℝ) hx : _ →ₗ[ℝ] A) :=
    ConvexCone.hull_min fun p hp ↦ ConvexCone.subset_hull (hp.map <| cfcₙHom hx)
  have hid : (0 : ContinuousMapZero (quasispectrum ℝ x) ℝ) ≤ ContinuousMapZero.id _ :=
    fun r ↦ quasispectrum_nonneg_of_nonneg (𝕜 := ℝ) x hx0 r r.2
  simpa [C, cfcₙHom_id] using
    hmap (ContinuousMapZero.mem_hull_isStarProjection_of_finite _ hid)

/-- In a real-rank-zero C⋆-algebra, the topological closure of the span of star
projections is exactly the submodule of the self-adjoint elements. -/
@[simp] theorem CStarAlgebra.IsRealRankZero.topologicalClosure_span_isStarProjection
    [ContinuousConstSMul ℝ A] [ContinuousAdd A] [StarModule ℝ A] [T2Space A]
    [ContinuousStar A] [h : CStarAlgebra.IsRealRankZero A] :
    (Submodule.span ℝ {x : A | IsStarProjection x}).topologicalClosure =
      selfAdjoint.submodule ℝ A := by
  refine le_antisymm (fun x hx ↦ closure_minimal (fun x hx ↦ ?_) ?_ hx) fun x hx ↦ ?_
  · refine Submodule.span_induction (fun _ hx ↦ hx.isSelfAdjoint) ?_ ?_ ?_ hx <;> aesop
  · exact isClosed_eq continuous_id'.star continuous_id'
  · exact closure_mono (fun y hy ↦ hy.1.mem_span_isStarProjection_of_finite_quasispectrum hy.2)
      (h.finite_quasispectrum_dense hx)

/-- Density of the real span of projections transfers backwards across a complex star-algebra
equivalence. -/
lemma IsSelfAdjoint.mem_topologicalClosure_span_isStarProjection_of_equiv
    {A' B : Type*} [NonUnitalCStarAlgebra A'] [NonUnitalCStarAlgebra B]
    [CStarAlgebra.IsRealRankZero B]
    (e : A' ≃⋆ₐ[ℂ] B) {x : A'} (hx : IsSelfAdjoint x) :
    x ∈ closure (Submodule.span ℝ {p : A' | IsStarProjection p} : Set A') := by
  letI := CStarAlgebra.IsRealRankZero.of_starAlgEquiv e
  change x ∈ (Submodule.span ℝ {p : A' | IsStarProjection p}).topologicalClosure
  rw [CStarAlgebra.IsRealRankZero.topologicalClosure_span_isStarProjection]
  exact hx

section PositiveCone

variable {B : Type*} [NonUnitalCStarAlgebra B] [PartialOrder B] [StarOrderedRing B]

/-- In a real-rank-zero C-star algebra, every nonnegative element belongs to the closure of the cone
generated by star projections. -/
lemma CStarAlgebra.IsRealRankZero.mem_topologicalClosure_hull_isStarProjection
    [hRR0 : CStarAlgebra.IsRealRankZero B] {x : B} (hx : 0 ≤ x) :
    x ∈ closure (ConvexCone.hull ℝ {p : B | IsStarProjection p} : Set B) := by
  let f : B → B := fun y => (2 : ℝ)⁻¹ • (CFC.abs y + y)
  have hf : Continuous f := (CFC.continuous_abs.add continuous_id').const_smul _
  have hfy {y : B} (hy : IsSelfAdjoint y) : f y = y⁺ := by
    simp only [f]
    rw [CFC.abs_add_self y hy, two_smul]
    module
  rw [← CFC.posPart_eq_self x |>.2 hx, ← hfy hx.isSelfAdjoint]
  exact map_mem_closure hf (hRR0.finite_quasispectrum_dense hx.isSelfAdjoint) fun y hy => by
    rw [hfy hy.1]
    exact (CFC.posPart_nonneg y).isSelfAdjoint
      |>.mem_hull_isStarProjection_of_nonneg_of_finite_quasispectrum (CFC.posPart_nonneg y) <| by
        rw [CFC.posPart_def, cfcₙ_map_quasispectrum (·⁺) y (by fun_prop) (by simp) hy.1]
        exact hy.2.image _

/-- In a real-rank-zero C-star algebra, the positive cone is the closure of the cone generated by
star projections. -/
@[simp] theorem CStarAlgebra.IsRealRankZero.topologicalClosure_hull_isStarProjection
    [CStarAlgebra.IsRealRankZero B] :
    closure (ConvexCone.hull ℝ {p : B | IsStarProjection p} : Set B) = {x | 0 ≤ x} := by
  apply le_antisymm
  · exact closure_minimal
      (ConvexCone.hull_min (C := ConvexCone.positive ℝ B) fun _ hp ↦ hp.nonneg)
      CStarAlgebra.isClosed_nonneg
  · exact fun _ hx ↦
      CStarAlgebra.IsRealRankZero.mem_topologicalClosure_hull_isStarProjection hx

variable {C : Type*} [NonUnitalCStarAlgebra C] [PartialOrder C] [StarOrderedRing C]

/-- Positive linear maps from a real-rank-zero C-star algebra into an ordered C-star algebra are
ordered on the whole positive cone as soon as they are ordered on projections. -/
theorem PositiveLinearMap.le_on_nonneg_of_le_on_isStarProjection
    [CStarAlgebra.IsRealRankZero B] (φ ψ : B →ₚ[ℂ] C)
    (h : ∀ p : B, IsStarProjection p → φ p ≤ ψ p) {x : B} (hx : 0 ≤ x) :
    φ x ≤ ψ x := by
  let K : ConvexCone ℝ B := {
    carrier := {x | φ x ≤ ψ x}
    smul_mem' c hc x hx := by
      simpa only [Set.mem_setOf_eq, PositiveLinearMap.map_smul_of_tower] using
        smul_le_smul_of_nonneg_left hx hc.le
    add_mem' {x} hx {y} hy := by
      simpa only [Set.mem_setOf_eq, map_add] using add_le_add hx hy }
  refine closure_minimal (ConvexCone.hull_min (C := K) fun p hp ↦ h p hp) ?_
    (CStarAlgebra.IsRealRankZero.mem_topologicalClosure_hull_isStarProjection hx)
  exact isClosed_le (map_continuous φ) (map_continuous ψ)

end PositiveCone
